export type SeedOpportunity = {
  id: string;
  company: string;
  role: string;
  tracks: string[];
  ownership: string;
  scale: string;
  city: string;
  applyUrl: string;
  sourceUrl: string;
  sourceLabel: string;
  startDate: string | null;
  endDate: string | null;
  deadlineNote: string;
  recommendation: number;
  fitReason: string;
  riskNote: string;
  degreeGate: string;
  verifiedAt: string;
  compensation?: string;
  initialStage?: string;
  initialAppliedAt?: string | null;
};

export const retiredSeedIds = [
  'wondershare-ai-pm-2027',
  'ct-digital-life-pm-2027',
  'cecloud-pm-2027',
  'amazon-program-2027',
  'oppo-display-pm-2027',
  'hello-momo-product-2027',
  'sungrow-campus-2027',
];

export const seedOpportunities: SeedOpportunity[] = [
  {
    id: 'hundsun-requirements-ai-2027',
    company: '恒生电子',
    role: '需求分析师 / AI应用开发工程师（金融IT）',
    tracks: ['B端软件/平台', 'AI应用产品', '知识图谱/数据产品'],
    ownership: '私企',
    scale: '中厂',
    city: '杭州 / 北京 / 武汉等',
    applyUrl: 'https://campus.hundsun.com/jobs',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/459402',
    sourceLabel: '恒生电子2027需求分析师具体岗位 + 官方校招入口',
    startDate: '2026-08-12',
    endDate: '2026-10-31',
    deadlineNote: '2027校招当前仍在官方岗位页开放；学校发布的校招日程至10月31日，按该日作保守提醒并优先投递',
    recommendation: 5,
    fitReason: '需求分析师直接负责理解、判断和引导用户需求，并在金融科技项目中连接业务、开发和测试；AI应用岗还覆盖RAG与智能体，与你的B端和AI应用经历都能衔接。',
    riskNote: '金融IT项目可能同时包含版本维护或客户项目属性；优先需求分析/AI应用，不选技术支持，并在面试中确认产品规划、需求分析与现场支持占比。',
    degreeGate: '2027届本科及以上，需求分析师明确要求计算机相关专业；未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '12–25K/月 × 14薪（本届需求分析师具体岗位公开）',
  },
  {
    id: 'pylontech-cloud-product-2027',
    company: '派能科技',
    role: '云平台产品工程师（储能 / 智慧能源）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '上海',
    applyUrl: 'https://pylontech1.zhiye.com/campus/jobs',
    sourceUrl: 'https://bebee.com/cn/jobs/2027j11749-shanghai--fj-2387379377',
    sourceLabel: '派能科技2027云平台产品工程师J11749岗位转载 + 官方校招入口',
    startDate: '2026-09-11',
    endDate: '2026-10-13',
    deadlineNote: '具体岗位转载标注截至2026年10月13日，官方校招岗位页仍开放；属于临近截止项，建议优先核验并投递',
    recommendation: 5,
    fitReason: '岗位负责储能云平台路标、APP/WEB竞品、客户访谈、需求池、原型和优先级，是计算机背景可投的能源B端产品岗，不是电气设计岗。',
    riskNote: '英语需作为工作语言，且车联网、光伏运维、智慧能源或储能云平台经历为偏好项；用现有B端/AI项目说明场景迁移能力，不要把自己包装成电力硬件候选人。',
    degreeGate: '2027届本科及以上，明确接受信息技术类或人工智能相关专业；未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '12–23K/月（本届J11749岗位招聘转载）',
  },
  {
    id: 'techen-ai-energy-application-2027',
    company: '青岛乾程科技',
    role: 'AI应用工程师 / 全球产品工程师（数字能源）',
    tracks: ['能源数字化/央国企', 'AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '青岛 / 杭州 / 西安',
    applyUrl: 'https://job.tiangong.edu.cn/correcruit/content/id/56177.html',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80511.html',
    sourceLabel: '乾程科技2027全球校招岗位表与网申说明',
    startDate: '2026-09-18',
    endDate: null,
    deadlineNote: '2027全球校招当前开放，未公布统一截止；通过“乾程招聘”公众号进入N计划校招投递，岗位滚动处理',
    recommendation: 5,
    fitReason: '数字能源公司本届单列AI应用、AI数据和全球产品工程岗位，计算机背景可从AI应用或软件产品切入，而不是投电力、电气或交付岗位。',
    riskNote: '全球产品工程师偏好英语，AI岗位可能有一定开发深度；优先核对AI应用与产品工程JD，避开硬件、电气、客户服务和全球交付岗位。',
    degreeGate: '2027届本科及以上；AI/研发专业范围明确包含计算机、软件工程、人工智能和数据科学，未写985/211硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '10K+/月（本届校招项目公开口径，具体岗位以Offer为准）',
  },
  {
    id: 'iwhalecloud-product-trainee-2027',
    company: '浩鲸科技',
    role: '产品经理管培生（通信 / 政企数字化）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '福州 / 南京 / 广州等',
    applyUrl: 'https://iwhalecloud1.zhiye.com/',
    sourceUrl: 'https://xiaozhaobao.com.cn/job/2880816',
    sourceLabel: '浩鲸科技2027产品经理管培生J18117具体岗位',
    startDate: '2026-08-29',
    endDate: null,
    deadlineNote: '官方2027校招正在滚动招聘，未公布统一截止；每人最多投2个且提交后不可修改，优先锁定产品经理管培生',
    recommendation: 5,
    fitReason: '面向通信、政企和行业数字化的B端产品岗，包含用户调研、竞品、PRD、原型、研发测试上线和数据复盘，与你现有产品经历最容易形成完整叙事。',
    riskNote: '不同城市和业务线可能混有海外交付、售前或运营咨询；只选产品经理管培生，并在面试中确认是否长期驻场、出差及产品决策权。',
    degreeGate: '2027届本科及以上，计算机/互联网/产品相关专业优先；未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '约15–25K/月招聘平台参考；本届具体产品管培岗位未单独公开，投递前需向HR确认',
  },
  {
    id: 'pudurobotics-product-manager-2027',
    company: '普渡机器人',
    role: '产品经理（商用机器人 / 智能硬件）',
    tracks: ['智能硬件/IoT', 'B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳 / 成都',
    applyUrl: 'https://pudutech1.zhiye.com/campus/jobs',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/460236',
    sourceLabel: '普渡机器人2027产品经理具体岗位 + 官方校招入口',
    startDate: '2026-08-17',
    endDate: '2026-12-31',
    deadlineNote: '具体产品经理岗位投递期为2026年8月17日至12月31日，当前可申请；建议尽早占用产品类名额',
    recommendation: 4,
    fitReason: '岗位覆盖B端客户调研、产品规划、PRD、业务流程、软硬件协同和上线迭代，属于产品经理而非项目经理，且商用机器人有明确企业客户场景。',
    riskNote: '英语流利是明确要求，且会参与客户支持和定制化方案；确认客户现场占比，并准备智能硬件全生命周期和B端需求拆解案例。',
    degreeGate: '2027届本科及以上；校招简章主要面向计算机、软件工程、人工智能等专业，未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '15–30K/月 × 14薪（本届产品经理具体岗位公开）',
  },
  {
    id: 'cnnc-huahui-ai-product-2027',
    company: '中核华辉',
    role: 'AI产品经理（大模型 / RAG）',
    tracks: ['AI应用产品', 'B端软件/平台', '能源数字化/央国企'],
    ownership: '央企',
    scale: '中厂',
    city: '北京',
    applyUrl: 'https://cnnc.zhiye.com/campus/detail?jobAdId=0d9141c3-c6c5-48eb-a7cd-a548ed7ad4e9',
    sourceUrl: 'https://jobs.uhomes.com/jobs/Wk2jnwkr',
    sourceLabel: '中核人才官方职位链接与2027 AI产品经理岗位详情',
    startDate: '2026-09-18',
    endDate: null,
    deadlineNote: '官方招聘系统近期仍在招，岗位标注招满即止且未公布固定截止；央企流程较长，建议尽早投递',
    recommendation: 5,
    fitReason: '中核体系的具体AI产品经理岗位，明确接受计算机本科并看重大模型、RAG和AI产品项目，比泛央企信息化入口更贴合你的产品经历。',
    riskNote: '央企岗位可能增加政审、材料和较长流程，且需要输出较规范的产品文档；投递前核对劳动关系主体、部门业务和是否涉及涉密要求。',
    degreeGate: '2027届本科及以上，明确接受计算机、软件工程、人工智能等专业；未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '薪资未公开；央企具体AI产品岗按高匹配例外保留',
  },
  {
    id: 'sundray-enterprise-ai-development-2027',
    company: '信锐技术',
    role: 'AI应用开发工程师（企业级AI产品）',
    tracks: ['AI应用产品', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'https://hr.sundray.com.cn',
    sourceUrl: 'https://neau.bysjy.com.cn/detail/job?career_id=709303&id=3226133',
    sourceLabel: '信锐技术2027 AI应用开发工程师具体岗位',
    startDate: '2026-08-14',
    endDate: null,
    deadlineNote: '官方2027校招仍开放且未公布统一截止，按官网岗位状态滚动处理；岗位热度较高，建议本轮优先投递',
    recommendation: 4,
    fitReason: '服务企业无线、物联网和交换机客户，岗位直接参与企业级AI产品后端与AI能力落地，适合用计算机专业和AI应用项目切入B端赛道。',
    riskNote: '这是研发岗而非产品经理，需能证明编码、数据结构和AI工程落地能力；若简历技术项目较弱，优先级放在需求分析与产品岗之后。',
    degreeGate: '2027届本科及以上；岗位面向计算机/软件/AI能力且未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '20–35K/月（本届具体岗位公开）',
  },
  {
    id: 'rigol-it-ai-application-2027',
    company: '普源精电（RIGOL）',
    role: 'IT开发工程师（企业AI应用 / 内部数字化）',
    tracks: ['AI应用产品', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 苏州',
    applyUrl: 'https://rigolportal.jobs.feishu.cn/campus',
    sourceUrl: 'https://campus.51job.com/rigol/about3.html',
    sourceLabel: '普源精电2027官方IT开发工程师岗位页',
    startDate: '2026-09-01',
    endDate: null,
    deadlineNote: '2027校招官方岗位页当前可投，未公布统一截止；按岗位状态滚动处理，优先选IT开发而非硕士限定的AI算法岗',
    recommendation: 4,
    fitReason: '岗位负责理解内部业务需求并把AI、智能助手和数据处理落到企业系统，兼具需求分析和AI应用开发，计算机本科条件清晰。',
    riskNote: '工作包含内部IT系统运维与快节奏交付，不是纯产品岗位；面试时确认AI应用建设与日常运维的比例，并准备Python/Java及AI工具项目。',
    degreeGate: '2027届本科及以上，明确接受计算机、人工智能、软件工程等专业；未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '15–25K/月（本届IT开发工程师岗位招聘转载）',
  },
  {
    id: 'streamax-platform-product-2027',
    company: '锐明技术',
    role: '产品工程师（商用车AI / 车联网平台）',
    tracks: ['B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'https://streamax.zhiye.com/campus',
    sourceUrl: 'https://scc.hnu.edu.cn/detail/job?career_id=708727&id=3228523',
    sourceLabel: '锐明技术2027产品工程师具体岗位 + 官方校招入口',
    startDate: '2026-08-26',
    endDate: null,
    deadlineNote: '2027秋招官方岗位当前开放，未公布统一截止；每人最多3个平行志愿，建议优先产品工程师',
    recommendation: 5,
    fitReason: '实质是商用车AI和车联网平台产品岗，职责含用户需求、PRD、原型、交互、新品验证和缺陷闭环；岗位明确接受计算机本科且薪资达标。',
    riskNote: '产品工程会比互联网PM更强调测试验证和软硬件协同，海外方向还可能要求语言与出差；优先国内平台方向并确认测试工作占比。',
    degreeGate: '2026/2027届本科及以上，明确接受计算机、信息、软件工程等专业；未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '14–20K/月（本届具体产品工程师岗位公开）',
  },
  {
    id: 'chinsoft-requirements-analysis-2027',
    company: '中国软件',
    role: '需求分析师（信创 / 行业信息化）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '央企',
    scale: '大型科技企业',
    city: '北京 / 上海 / 天津 / 广州 / 成都 / 沈阳',
    applyUrl: 'https://mp.weixin.qq.com/s/fLnb3K95tmtNq1FhbNEt9g',
    sourceUrl: 'https://xiaozhaobao.com.cn/job/17764024',
    sourceLabel: '中国软件2027需求分析师岗位聚合页与官方招聘公告',
    startDate: '2026-09-19',
    endDate: '2026-11-19',
    deadlineNote: '2027届需求分析师岗位标注2026年11月19日截止；投递入口以中国软件官方招聘公告为准',
    recommendation: 5,
    fitReason: '央企“软件国家队”的具体需求分析岗位，比泛研发入口更适合用B端需求、业务流程和产品文档经历切入，业务覆盖党政与关键行业信息化。',
    riskNote: '不同子公司可能有项目制或驻场属性，薪资未公开；投递时确认劳动关系主体、工作城市、客户现场频率和需求分析是否独立于实施交付。',
    degreeGate: '2027届本科起，计算机及软件方向可投；公开岗位未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '薪资未公开；央企B端需求分析具体岗按匹配度保留',
  },
  {
    id: 'ztccloud-b2b-product-2027',
    company: '中兴新云',
    role: 'B端产品经理（财务云 / 企业数智化）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 西安 / 长沙 / 上海 / 广州 / 成都 / 长春',
    applyUrl: 'https://www.wenjuan.com/s/UZBZJvhceK/',
    sourceUrl: 'https://www.ztccloud.com.cn/careers/campus-product-manager.html',
    sourceLabel: '中兴新云官方2027届产品经理岗位页',
    startDate: '2026-09-16',
    endDate: '2026-12-31',
    deadlineNote: '官方岗位页明确网申截至2026年12月31日；可直接通过岗位页所列问卷投递',
    recommendation: 5,
    fitReason: '明确的企业财务云B端产品岗，职责包含需求梳理、原型与产品逻辑架构、规格说明和UAT，与你的B端产品经历直接对口。',
    riskNote: '岗位要求能接受中短期出差，且财务信息系统经历优先；面试前补企业财务流程基础，并确认产品工作与客户现场的时间占比。',
    degreeGate: '2027届本科及以上，多数岗位不限专业；未写985/211或研究生硬门槛，B端产品实习/项目经历优先',
    verifiedAt: '2026-10-09',
    compensation: '约10–14K/月参考；本届官网未公开，采用公司当前初级产品岗公开区间，仅作投递前估算',
  },
  {
    id: 'seichitech-product-information-2027',
    company: '精智达',
    role: '产品信息工程师（半导体B端 / 知识管理 / UAT）',
    tracks: ['B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'https://www.nowcoder.com/jobs/detail/467167',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/467167',
    sourceLabel: '精智达校招HR发布的2027产品信息工程师岗位',
    startDate: '2026-09-07',
    endDate: '2026-12-31',
    deadlineNote: '岗位页标注投递时间为2026年9月7日至12月31日；当前可直接申请',
    recommendation: 5,
    fitReason: '不是传统“产品经理”命名，但实质覆盖B端产品全生命周期、UAT、研发知识库和AI知识管理，能突出需求结构化与产品工程能力。',
    riskNote: '英语六级是明确要求，且职责包含技术文档和内部培训；如果没有六级或不愿做知识资产沉淀，应降低优先级。',
    degreeGate: '2027届本科及以上，理工科背景，通信/电子信息优先；未写985/211或研究生硬门槛，但明确要求英语六级',
    verifiedAt: '2026-10-09',
    compensation: '10–20K/月 × 13薪（本届具体岗位公开）',
  },
  {
    id: 'kingdee-ai-product-2027',
    company: '金蝶',
    role: 'AI产品经理 / 产品经理（企业管理AI）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '深圳 / 北京 / 上海 / 南京 / 厦门 / 长沙等',
    applyUrl: 'https://app.mokahr.com/campus-recruitment/kingdeehr/166565?locale=zh-CN#/jobs',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2448099.htm',
    sourceLabel: '金蝶2027届校园招聘简章与官方网申入口',
    startDate: '2026-09-10',
    endDate: null,
    deadlineNote: '2027校招当前开放，公告未给统一截止；岗位滚动处理，每人优先锁定AI产品经理或产品管培方向',
    recommendation: 4,
    fitReason: '企业管理AI和Agent场景属于强B端产品，岗位表明确列AI产品经理、AI产品体验设计和产品管培生，能承接AI应用与企业软件经历。',
    riskNote: '不同业务线职责和城市差异较大，实施顾问不等同产品岗；投递时只选AI产品/产品管培，并确认是否需要长期驻场。',
    degreeGate: '2027届本科及以上；计算机、人工智能等相关专业可投，招聘简章未写985/211或研究生统一硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '10–15K/月（本届校招项目公开区间，具体AI产品子岗以Offer为准）',
  },
  {
    id: 'goldwind-product-rd-2027',
    company: '金风科技',
    role: '产品研发类（风电 / 储能 / 数字能源）',
    tracks: ['能源数字化/央国企', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '北京 / 无锡 / 新疆等',
    applyUrl: 'https://goldwind.zhiye.com/jobs',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/81511.html',
    sourceLabel: '金风科技2027届校园招聘简章 + 官方岗位入口',
    startDate: '2026-09-23',
    endDate: null,
    deadlineNote: '官方岗位当前开放且未公布统一截止；招聘简章建议在对应校园宣讲前完成投递，按官网岗位状态滚动处理',
    recommendation: 5,
    fitReason: '风电、储能与零碳业务高度贴合能源垂直，产品研发大类明确接受计算机本科；优先筛数字化平台、数据、控制与产品工程岗位。',
    riskNote: '产品研发是岗位大类，不代表每个子岗都适合计算机本科；避开明确要求硕士的算法岗，逐岗核对学历、现场测试和新疆地点要求。',
    degreeGate: '2027届本科及以上；产品研发类明确接受计算机、自动化、电子、控制等专业，未写985/211统一硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '10K+/月（本届校招项目公开口径，具体子岗与城市以Offer为准）',
  },
  {
    id: 'nsfocus-security-product-2027',
    company: '绿盟科技',
    role: '产品经理（企业级网络安全 / AI安全）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 成都 / 西安 / 武汉 / 南京等',
    applyUrl: 'https://app.mokahr.com/campus_apply/nsfocus/29118#/',
    sourceUrl: 'https://job.hdu.edu.cn/campus/view?id=10011',
    sourceLabel: '绿盟科技2027届校园招聘公告与官方网申入口',
    startDate: '2026-07-28',
    endDate: '2026-11-15',
    deadlineNote: '公告写网申持续至11月中旬；页面有效期到11月24日，按较早的11月15日作为保守截止提醒',
    recommendation: 4,
    fitReason: '企业级网络安全产品覆盖政府、金融、能源等B端客户，并已布局大模型安全产品；本届岗位表明确单列产品经理。',
    riskNote: '非电力垂直，产品岗可能要求安全基础与英语四级；优先选择产品经理，不把售前、服务或产品支持当成同一岗位。',
    degreeGate: '2027届本科及以上，产品经理接受计算机/工商管理等背景；未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '15–20K/月（本届产品经理岗位公开转载区间）',
  },
  {
    id: 'ygsoft-ai-requirements-2027',
    company: '远光软件',
    role: 'AI应用工程师 / 需求分析师（智慧能源企业软件）',
    tracks: ['能源数字化/央国企', 'AI应用产品', 'B端软件/平台'],
    ownership: '央企',
    scale: '中厂',
    city: '珠海 / 武汉',
    applyUrl: 'https://sgdt.iguopin.com',
    sourceUrl: 'https://yjsjob.91wllm.cn/campus/view/id/1005888',
    sourceLabel: '远光软件2027提前批具体岗位表 + 国网数科官方网申',
    startDate: '2026-09-30',
    endDate: '2026-10-30',
    deadlineNote: '提前批报名截至2026年10月30日；本科优先选珠海AI应用或武汉需求分析，统一招聘后续仍有批次',
    recommendation: 5,
    fitReason: '国家电网体系的智慧能源与企业管理软件公司；珠海AI应用和武汉需求分析均明确本科，正好覆盖AI+电力与B端需求分析。',
    riskNote: '北京、上海及部分同名AI岗位可能要求硕士，不能跨城市套用；需求分析师下限9.5K，但央企电力垂直不设私企薪资门槛。',
    degreeGate: '珠海AI应用工程师和武汉需求分析师明确本科可投；未写985/211硬门槛，北京/上海等其他岗位需另核学历',
    verifiedAt: '2026-10-09',
    compensation: 'AI应用10.5–15K/月；需求分析9.5–10.5K/月（本届具体岗位公开）',
  },
  {
    id: 'sgdt-ai-energy-digital-2027',
    company: '国网数科控股',
    role: '电子信息 / AI应用 / 数据与数字能源岗位（提前批）',
    tracks: ['能源数字化/央国企', 'AI应用产品', 'B端软件/平台'],
    ownership: '央企',
    scale: '中厂',
    city: '北京 / 上海 / 浙江 / 湖北 / 广东',
    applyUrl: 'https://sgdt.iguopin.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/119501.html',
    sourceLabel: '国网数科控股2027校园招聘公告与官方提前批入口',
    startDate: '2026-10-06',
    endDate: '2026-10-30',
    deadlineNote: '官方提前批报名截至2026年10月30日；提前批未获面试仍可参加11—12月统一招聘第一批',
    recommendation: 5,
    fitReason: '国家电网全资数字科技平台，电子信息类直接覆盖计算机、AI、大数据和信息安全，是本轮最贴近“AI+电力能源”的央企入口。',
    riskNote: '集团岗位量大但具体职责分散，工程管理/项目管理也在同一入口；只选电子信息、AI应用、数据或数字能源技术岗位。',
    degreeGate: '2027届本科、硕士、博士均有岗位；电子信息类接受计算机、人工智能、大数据等专业，未写985/211统一硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '15–20K/月（高校发布的本届校招项目口径，具体子岗以Offer为准）',
  },
  {
    id: 'czbank-ai-application-2027',
    company: '浙商银行',
    role: '总行科技类（AI应用研发 / 智能数据）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '国企',
    scale: '中厂',
    city: '杭州',
    applyUrl: 'https://zp.czbank.com.cn',
    sourceUrl: 'https://zp.czbank.com.cn/zpweb/zpPostController/planDetailPage.mvc?planId=8a8340e9a033d10501a06502133f0014',
    sourceLabel: '浙商银行官方2027校园招聘计划与科技岗位列表',
    startDate: '2026-09-16',
    endDate: '2026-10-25',
    deadlineNote: '官方招聘计划及岗位页明确2026年10月25日截止；优先AI应用研发或智能数据，不选纯运维',
    recommendation: 4,
    fitReason: '总行科技类岗位把AI应用研发和智能数据单独列出，本科可投；比泛分行岗位更接近金融科技产品与AI落地。',
    riskNote: '岗位偏研发和数据，不是纯产品经理；投递前核对编程要求和具体职责，不把智能运维作为第一志愿。',
    degreeGate: '2027届本科及以上；总行AI应用研发、智能数据岗位明确本科开放，未写985/211统一硬门槛',
    verifiedAt: '2026-10-09',
    compensation: '未公开；国企银行科技岗不设私企月薪下限，固定薪资和绩效需面试确认',
  },
  {
    id: 'cmbc-tech-ai-development-2027',
    company: '民生科技',
    role: '启航校招岗—软件开发（金融科技与AI应用）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '混合所有制',
    scale: '中厂',
    city: '成都',
    applyUrl: 'http://career.cmbc.com.cn:8080/index.jsp#/app/recruitment/campus',
    sourceUrl: 'https://www.yinhangzhaopin.com/msyhzp/2026-09-04/224962.htm',
    sourceLabel: '中国民生银行2027届民生科技岗位转载（原文链接官方校招系统）',
    startDate: '2026-09-04',
    endDate: '2026-10-25',
    deadlineNote: '官方校招系统岗位截至2026年10月25日；本科只选“启航”软件开发，勿投要求硕士的“扬帆”AI/数据岗位',
    recommendation: 3,
    fitReason: '本科计算机明确可投，职责涉及银行核心系统、金融科技和AI应用设计开发；适合作为银行科技路线补充。',
    riskNote: '这是软件开发而非产品岗，且含上线后运维支持；仅在愿意用技术岗切入金融科技时投，优先级低于产品和AI+能源岗位。',
    degreeGate: '启航软件开发方向明确本科及以上、计算机相关专业；扬帆AI/数据方向要求硕士，已在说明中排除',
    verifiedAt: '2026-10-09',
    compensation: '未公开；银行科技子公司岗位按例外收录，需面试确认固定薪资、绩效与加班情况',
  },
  {
    id: 'huaneng-beijing-digital-2027',
    company: '华能北京热电',
    role: '计算机 / 电子信息技术岗（热电生产数字化）',
    tracks: ['能源数字化/央国企', 'B端软件/平台'],
    ownership: '央企',
    scale: '中厂',
    city: '北京',
    applyUrl: 'https://zhaopin.chng.com.cn/InternRecruit?aId=2000235',
    sourceUrl: 'https://zhaopin.chng.com.cn/InternRecruit?aId=2000235',
    sourceLabel: '中国华能官方2027校园招聘公告',
    startDate: '2026-09-15',
    endDate: '2026-10-31',
    deadlineNote: '中国华能官方页面明确2026年10月31日18:00截止；选择华能北京热电并核对计算机/电子信息岗位',
    recommendation: 4,
    fitReason: '本科计算机在京能源央企的直接入口，可把电力场景和信息化经历用于热电生产数字化、系统与数据相关工作。',
    riskNote: '公告按专业大类发布，未细分产品职责；投递前必须确认具体部门和信息化工作占比，避免被分到与计算机无关的生产岗位。',
    degreeGate: '2027届全日制本科及以上；计算机、电子信息专业明确在招，未写985/211或研究生硬门槛，但要求英语四级425分以上',
    verifiedAt: '2026-10-09',
    compensation: '未公开；能源央企不设私企月薪下限，五险二金与具体岗位待遇以面试为准',
  },
  {
    id: 'boc-digital-tech-2027',
    company: '中国银行',
    role: '信息科技 / 数字金融岗位（2027全球校园招聘）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '央企',
    scale: '大厂',
    city: '全国分支机构 / 信息科技中心',
    applyUrl: 'https://campus.chinahr.com/pages/2027-boc',
    sourceUrl: 'https://www.boc.cn/aboutboc/bi4/202609/t20260903_25689311.html',
    sourceLabel: '中国银行官方2027全球校园招聘公告',
    startDate: '2026-09-03',
    endDate: '2026-10-09',
    deadlineNote: '官方公告明确北京时间10月9日24:00截止；最多可申请5个岗位，先筛信息科技/数字金融相关岗位',
    recommendation: 3,
    fitReason: '央企银行正式校招，信息科技、数字金融和综合经营岗位能承接计算机本科、B端流程与AI产品经历；适合作为稳定性保底。',
    riskNote: '岗位按机构和分支差异很大，未必是纯产品经理；投递时优先信息科技、数据、数字金融，避开与目标无关的柜面/营销岗。',
    degreeGate: '2027届本科及以上，具体机构要求不同；官方未写985/211统一硬门槛，需逐岗核对专业和英语要求',
    verifiedAt: '2026-10-08',
    compensation: '未公开；央企银行不设私企月薪下限，福利和机构差异需面试确认',
  },
  {
    id: 'cmb-chengdu-digital-finance-2027',
    company: '招商银行成都分行',
    role: '数字金融岗（成都分行）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '混合所有制',
    scale: '大厂',
    city: '成都',
    applyUrl: 'https://cmb-recruitment-mobile.paas.cmbchina.com/positionList/school?orgId=102518&recruitmentTypeId=96574F8D-C7ED-4772-AE7C-BAC896D190C',
    sourceUrl: 'https://cmb-recruitment-mobile.paas.cmbchina.com/positionList/school?orgId=102518&recruitmentTypeId=96574F8D-C7ED-4772-AE7C-BAC896D190C',
    sourceLabel: '招商银行官方校园招聘岗位列表 + 成都分行公告',
    startDate: '2026-09-24',
    endDate: '2026-10-10',
    deadlineNote: '官方岗位列表显示10月10日截止；最多投递5家机构，数字金融岗优先于柜面和泛营销岗',
    recommendation: 3,
    fitReason: '本科可投，专业不限且数字金融岗优先IT/DT等理工科；可把平台产品、企业客户需求和数据/AI经历迁移到银行数字化场景。',
    riskNote: '分行岗位可能包含轮岗和业务培养，不等同于互联网产品经理；面试确认是否进入数字金融产品/数据团队以及是否需要营销轮岗。',
    degreeGate: '2027届本科及以上；专业不限，数字金融岗IT/DT等理工科优先，未写985/211硬门槛',
    verifiedAt: '2026-10-08',
    compensation: '未公开；银行岗位不设私企月薪下限，具体按分行和岗位核实',
  },
  {
    id: 'hzbank-ai-tech-2027',
    company: '杭州银行',
    role: '总行信息技术部培训生（人工智能 / 软件研发 / 数据研发）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '国企',
    scale: '中厂',
    city: '杭州 / 北京 / 上海 / 深圳 / 南京 / 合肥',
    applyUrl: 'https://myjob.hzbank.com.cn/hzzp-apply-web/static/index.html',
    sourceUrl: 'https://jobs.tiangong.edu.cn/correcruit/content/id/56188.html',
    sourceLabel: '杭州银行官方招聘入口 + 2027秋招公告',
    startDate: '2026-09-16',
    endDate: '2026-10-25',
    deadlineNote: '官方公告明确报名截止2026年10月25日24:00；最多投递2个志愿',
    recommendation: 4,
    fitReason: '本科开放，信息技术部单列人工智能、软件研发和数据研发方向；银行数字化平台稳定，和计算机专业及AI产品作品有较强结合点。',
    riskNote: '公告是培训生序列，入职后可能有培养和轮岗，不保证直接做产品；投递时优先人工智能/数据研发，确认是否有需求分析或平台产品岗位。',
    degreeGate: '境内外2027届本科及以上；专业详见具体岗位，未写985/211或研究生统一硬门槛',
    verifiedAt: '2026-10-08',
    compensation: '公告标注10000元以上；具体固定薪资、绩效和人才补贴按岗位核实',
  },
  {
    id: 'nbcb-fintech-product-2027',
    company: '宁波银行',
    role: '总行金融科技定向生（产品经理 / 应用研发 / 数据研发）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '国企',
    scale: '中厂',
    city: '宁波',
    applyUrl: 'https://zhaopin.nbcb.com.cn/#/campus-recruitment',
    sourceUrl: 'https://job.zzu.edu.cn/campus/view/id/1018779',
    sourceLabel: '宁波银行官方招聘入口 + 2027总行金融科技定向生公告',
    startDate: '2026-08-01',
    endDate: '2026-10-31',
    deadlineNote: '招聘汇总将总行金融科技部截止标为10月31日；官方流程写网申8月至12月滚动，最终以官网岗位状态为准',
    recommendation: 4,
    fitReason: '官方明确列出产品经理、应用研发、数据研发、算法与安全等方向，本科计算机/软件/人工智能可投，金融科技B端平台匹配度高。',
    riskNote: '岗位池很宽，技术岗比例高；优先选择产品经理、数据研发和AI应用相关方向，避免只投运维或纯开发岗位。',
    degreeGate: '2027届本科及以上；计算机、软件工程、人工智能、电子通信、信息安全、自动化、数学统计等可投，未写985/211硬门槛',
    verifiedAt: '2026-10-08',
    compensation: '未公开；国企银行不设私企月薪下限，金融科技定向生福利和定岗需面试确认',
  },
  {
    id: 'suzhou-bank-ai-tech-2027',
    company: '苏州银行',
    role: '信息科技类（AI / 智能体应用 / 需求分析）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '国企',
    scale: '中厂',
    city: '苏州',
    applyUrl: 'https://suzhoubank.zhiye.com/',
    sourceUrl: 'https://jy.tust.edu.cn/correcruit/content/id/46770.html',
    sourceLabel: '苏州银行官方招聘入口 + 2027秋招公告',
    startDate: '2026-09-21',
    endDate: '2026-10-25',
    deadlineNote: '公告明确简历投递截至2026年10月25日；全行及附属公司最多投递2个岗位',
    recommendation: 3,
    fitReason: '本科开放，信息科技类明确涉及AI新技术、内部智能体应用试点、系统需求分析、开发与测试，适合从产品工程/需求分析切入银行科技。',
    riskNote: '岗位培养包含技术支持响应和项目跟踪，产品属性弱于纯产品岗；面试时确认智能体应用和需求分析占比，避免被分到长期运维。',
    degreeGate: '2027届普通高校本科及以上；信息科技类接受计算机等相关背景，未写985/211硬门槛',
    verifiedAt: '2026-10-08',
    compensation: '未公开；国企银行不设私企月薪下限，苏州本地岗位福利需面试确认',
  },
  {
    id: 'citic-card-product-ai-2027',
    company: '中信银行信用卡中心',
    role: '产品经理 / AI应用开发（产品及渠道、信息技术类）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '央企',
    scale: '大厂',
    city: '深圳 / 北京 / 重庆 / 广州 / 成都',
    applyUrl: 'https://t.zhaopin.com/07SiIF',
    sourceUrl: 'https://jobs.tiangong.edu.cn/correcruit/content/id/55652.html',
    sourceLabel: '中信银行信用卡中心官方校园招聘入口 + 2027秋招公告',
    startDate: '2026-09-01',
    endDate: '2026-10-18',
    deadlineNote: '公告写明网申结束时间暂定10月18日；产品及渠道类、AI应用开发均需在官网逐岗选择',
    recommendation: 4,
    fitReason: '明确列出产品经理、研究分析和AI应用开发，本科计算机/电子信息/自动化等专业可投；金融+生活场景能积累产品和数据能力。',
    riskNote: '信用卡业务偏消费金融，可能有运营、渠道和营销协同；优先产品及渠道、AI应用开发，不投纯营销管理和客服运营。',
    degreeGate: '2027届本科及以上；工学、理学、经管等相关专业可投，一般要求英语四级425，未写985/211硬门槛',
    verifiedAt: '2026-10-08',
    compensation: '公告标注10000元以上；央企金融机构不设私企月薪下限，具体城市和绩效需核实',
  },
  {
    id: 'sf-tech-product-data-2027',
    company: '顺丰科技',
    role: '产品经理 / 数据产品经理（企业物流与AI数据平台）',
    tracks: ['B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳 / 武汉 / 成都',
    applyUrl: 'https://campus.sf-express.com/#/homePage',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/119482.html',
    sourceLabel: '顺丰科技官方校园招聘入口 + 2027届秋招公告',
    startDate: '2026-09-30',
    endDate: null,
    deadlineNote: '官方公告写“即日起”投递，未公布统一截止；产品经理、数据产品经理仍在全岗开放列表，建议尽快提交',
    recommendation: 4,
    fitReason: '企业物流、供应链和数据平台是典型B端场景，产品经理与数据产品经理均明确开放本科，且AI/大数据方向能承接你的AI产品与需求分析经历。',
    riskNote: '顺丰科技业务规模较大、节奏可能偏快；岗位可能靠近物流运营和数据交付，投递时优先产品/数据产品，确认是否有纯项目管理或长期驻场要求。',
    degreeGate: '2027届本科及以上，公告未写985/211或研究生统一硬门槛；计算机、软件、数据和理工背景可投',
    verifiedAt: '2026-10-08',
    compensation: '公告标注20000元以上；为招聘页面综合口径，需以具体城市和Offer确认固定月薪与绩效',
  },
  {
    id: 'bankcomm-fintech-2027',
    company: '交通银行',
    role: '金融科技岗（IT系统 / 软件开发 / 数据安全）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '央企',
    scale: '大厂',
    city: '上海 / 全国省直分行',
    applyUrl: 'https://job.bankcomm.com/queryPosition.do',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/119027.html',
    sourceLabel: '交通银行官方校园招聘入口 + 2027年度校招公告',
    startDate: '2026-09-18',
    endDate: '2026-10-18',
    deadlineNote: '公告明确简历投递截至2026年10月18日；总行金融科技岗可与省直分行科技岗兼报，但总数不超过6个',
    recommendation: 3,
    fitReason: '央企银行明确设置IT系统管理、软件开发、安全技术、数据安全和分行金融科技方向，本科计算机专业可投，适合作为金融科技稳定性保底。',
    riskNote: '岗位以技术和安全为主，未必直接做产品；投递时锁定金融科技/数据安全/系统建设，避开纯运营、柜面和营销岗位。',
    degreeGate: '2027届本科及以上；IT技术、数理分析、电子通信等专业优先，公告未写985/211统一硬门槛',
    verifiedAt: '2026-10-08',
    compensation: '未公开；央企银行不设私企月薪下限，具体薪酬和轮岗安排按机构核实',
  },
  {
    id: 'cgb-fintech-product-2027',
    company: '广发银行',
    role: '金融科技 / 产品管理（含广银理财产品方向）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '国企',
    scale: '大厂',
    city: '广州 / 北京 / 上海 / 全国分行',
    applyUrl: 'https://www.cgbchina.com.cn/',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80750.html',
    sourceLabel: '广发银行官方招聘入口 + 2027年度校园招聘公告',
    startDate: '2026-09-17',
    endDate: '2026-10-15',
    deadlineNote: '总行报名截止2026年10月15日；分支机构截止2026年11月15日，官网按机构和职位类别选择',
    recommendation: 3,
    fitReason: '国有股份制银行明确招聘金融科技、产品管理、市场数据分析和广银理财产品类岗位，本科理工科可投，能把B端需求和AI数据能力迁移到金融产品。',
    riskNote: '不同机构岗位差异很大，部分岗位偏营销或运营；优先总行金融科技、广银理财产品管理和数据分析，避开纯营销服务类。',
    degreeGate: '主要招聘2027届本科及以上，重点招收理学、工学等背景；未写985/211统一硬门槛，但需逐岗确认',
    verifiedAt: '2026-10-08',
    compensation: '未公开；国有股份制银行不设私企月薪下限，招聘转载标注8–11K仅作参考，具体以Offer为准',
  },
  {
    id: 'bankofbeijing-ai-tech-2027',
    company: '北京银行',
    role: '科技英才（AI产品 / 软件开发 / 云计算）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '国企',
    scale: '中厂',
    city: '北京 / 顺义科技研发中心',
    applyUrl: 'https://bankofbeijing.zhiye.com',
    sourceUrl: 'https://career.cup.edu.cn/campus/view/id/460568',
    sourceLabel: '北京银行官方校园招聘平台 + 2027校园招聘公告',
    startDate: '2026-09-28',
    endDate: '2026-10-15',
    deadlineNote: '官方公告明确报名截止北京时间2026年10月15日24:00；科技英才岗位标注本科、15–25K',
    recommendation: 4,
    fitReason: '城市商业银行科技研发中心明确覆盖人工智能、产品研发、软件开发、云计算和数字金融，本科计算机可投，待遇公开且产品技术结合度高。',
    riskNote: 'AI产品经理具体岗位可能在北银金科子公司，需在官网选择“总行科技英才/科技研发”并确认产品分析占比；不投泛金融英才和柜面岗。',
    degreeGate: '所有岗位本科及以上，计算机科学与技术、电子信息工程等专业可投；公告未写985/211或研究生硬限制',
    verifiedAt: '2026-10-08',
    compensation: '科技英才公告公开15–25K/月；实际以岗位、绩效和工作地点Offer为准',
  },
  {
    id: 'mingyang-smart-energy-ai-2027',
    company: '明阳智慧能源',
    role: '智慧能源数据分析 / BI算法 / 数字化平台方向',
    tracks: ['能源数字化/央国企', 'AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '中山 / 深圳 / 北京等',
    applyUrl: 'https://mywind.zhiye.com/Campus/jobs',
    sourceUrl: 'https://mywind.zhiye.com/jobs?activityGuid=b5d9aa2a-3f28-46ca-95a2-7034c8e32bab',
    sourceLabel: '明阳智慧能源官方2027校园岗位列表',
    startDate: '2026-09-23',
    endDate: '2026-11-24',
    deadlineNote: '官方岗位页显示9月23日持续发布，公开校招汇总标注11月24日；官网未给统一截止，岗位状态优先',
    recommendation: 5,
    fitReason: '风电与智慧能源垂直度很高，岗位直接做风场数据治理、AI预测、BI算法、运维分析和平台迭代；官方岗位明确本科计算机可投，是AI+电力能源的优先补充。',
    riskNote: '算法岗中有硕士门槛，投递时只选明确本科的27届数据分析工程师、BI算法或数据平台岗位；部分岗位可能需要现场/风场支持，面试确认出差比例。',
    degreeGate: '27届本科及以上；数据分析/BI岗位明确接受计算机、信息技术、统计、自动化等本科背景，人工智能算法岗另有硕士要求',
    verifiedAt: '2026-10-08',
    compensation: '27届未公开；同公司26校招智慧能源系统算法岗公开15–25K/月，但更早BI/智慧运维数据岗曾为9–13万/年。岗位差异大，只在确认固定月薪≥10K后继续流程',
  },
  {
    id: 'flypai-ai-agent-product-2027',
    company: '飞派科技',
    role: 'AI Agent产品经理（企业AI应用）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '成长公司',
    city: '广州',
    applyUrl: 'https://www.flypai.com/jobs.html',
    sourceUrl: 'https://www.flypai.com/jobs.html',
    sourceLabel: '飞派科技官方校招岗位页',
    startDate: '2026-09-15',
    endDate: null,
    deadlineNote: '官网面向2027届校招/转正实习，未公布统一截止；简历发送至contact@flypai.com，招满即止',
    recommendation: 4,
    fitReason: '岗位直接覆盖企业知识库、RAG、工作流、工具调用、需求探索、PRD和上线复盘，计算机本科即可投，和你的AI产品/知识图谱叙事很贴。',
    riskNote: '团队规模较小、薪资未公开，且官网同时强调行业解决方案交付；投前必须确认基本月薪、转正机制和客户现场比例。弹性工作和不打卡是加分项，但不能替代薪资核实。',
    degreeGate: '2027届本科及以上，专业不限；计算机、人工智能、设计、商科等相关背景优先，未写985/211或研究生硬门槛',
    verifiedAt: '2026-10-08',
    compensation: '未公开；按广州同类AI产品校招岗位估计约10–16K/月，须以书面Offer核实；五险一金、弹性工作、不打卡',
  },
  {
    id: 'xiaopeng-embodied-data-product-2027',
    company: '小鹏集团',
    role: '具身智能数据硬件产品经理',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '广州 / 北京 / 上海',
    applyUrl: 'https://xiaopeng.jobs.feishu.cn/campus/position/7678640648783022390/detail',
    sourceUrl: 'https://xiaopeng.jobs.feishu.cn/campus/position/7678640648783022390/detail',
    sourceLabel: '小鹏集团官方2027具身智能产品岗位页',
    startDate: '2026-09-01',
    endDate: null,
    deadlineNote: '官方岗位仍开放，未公布统一截止；按探索者计划滚动筛选，建议尽早投递',
    recommendation: 3,
    fitReason: '岗位名称虽不是传统产品经理，但明确做机器人/数据采集硬件需求、方案和产品细节，计算机本科可投，适合把AI项目和硬件/物联网经历结合。',
    riskNote: '公司体量大、现场和动手验证较多，竞争会高于中厂；这是AI硬件破格项，面试前确认是否接受深入现场和较强研发节奏。',
    degreeGate: '2027届本科及以上；机器人、自动化、电子信息、机械、计算机等相关专业，研究生仅优先，未写985/211硬门槛',
    verifiedAt: '2026-10-08',
    compensation: '2027具体岗位未公开；公开招聘资料中本科应届年薪约15–17W（往届参考，折合约12.5–14.2K/月），以本届Offer为准',
  },
  {
    id: 'hyperstrong-energy-solution-2027',
    company: '海博思创',
    role: '解决方案工程师 / 电力交易工程师（储能与算力能源）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 西安 / 武汉 / 南京 / 珠海 / 海外区域',
    applyUrl: 'https://campus.51job.com/hyperstrong2027/job.html',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80177.html',
    sourceLabel: '海博思创2027校招岗位公告 + 官方校招页',
    startDate: '2026-09-07',
    endDate: null,
    deadlineNote: '校招网申仍开放；优先选择解决方案/电力交易，不投项目管理',
    recommendation: 4,
    fitReason: '储能系统服务电网、发电侧、终端电力用户和智能微网，业务直接连接AI算力能源；计算机本科可从解决方案、交易和系统软件方向切入。',
    riskNote: '解决方案岗客户沟通和海外/现场支持较多；电力交易岗位需补电价、负荷预测和储能优化知识，先确认实际岗位地点。',
    degreeGate: '2027届本科及以上；专业含计算机科学与技术，未写985/211限制',
    verifiedAt: '2026-10-06',
    compensation: '公告标注10K以上；六险一金、公租房/宿舍、餐补、交通补和年终奖',
  },
  {
    id: 'bluetti-energy-product-2027',
    company: '德兰明海（BLUETTI）',
    role: '产品经理（储能 / 微电网）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳 / 惠州',
    applyUrl: 'https://campus.51job.com/poweroak2027/job.html',
    sourceUrl: 'https://campus.51job.com/poweroak2027/job.html',
    sourceLabel: '德兰明海2027校招官方岗位页',
    startDate: '2026-09-01',
    endDate: '2026-11-30',
    deadlineNote: '岗位页持续更新；优先选产品经理，不投软件项目工程师',
    recommendation: 4,
    fitReason: '岗位职责覆盖用户/市场调研、竞品分析、产品定义、需求文档、功能规划和上市反馈，业务是户用/工商业储能与微电网，和能源产品方向高度匹配。',
    riskNote: '待遇按综合年薪公布而非基本月薪，且要求理工背景和CET-6；投前确认产品线、月度固定薪资和加班节奏。',
    degreeGate: '2027届本科及以上；产品经理要求理工科，计算机/电子信息/电气等可关注，未写985/211限制',
    verifiedAt: '2026-10-06',
    compensation: '首年本科综合年薪12–25W，第2–3年18–30W；五险一金、补贴、海外业务平台',
  },
  {
    id: 'inbo-energy-product-engineer-2027',
    company: '英博电气',
    role: '产品工程师 / 解决方案工程师（储能PCS与电力装备）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 深圳 / 廊坊 / 惠州 / 武汉 / 浙江',
    applyUrl: 'https://career.hebut.edu.cn/recruitment/content/type/2/id/5308.html',
    sourceUrl: 'https://career.hebut.edu.cn/recruitment/content/type/2/id/5308.html',
    sourceLabel: '英博电气2027秋招岗位公告（含邮箱/内推投递说明）',
    startDate: '2026-09-23',
    endDate: null,
    deadlineNote: '秋招岗位仍可通过公告邮箱或内推投递；注明英博智储/英博智源和意向区域',
    recommendation: 2,
    fitReason: '储能PCS、电力装备和智慧能源垂直度很高，技术类明确开放产品工程师、国内/海外解决方案工程师，本科计算机也在可投专业范围。',
    riskNote: '本科薪资按院校层次公布，普通一本口径为年薪8–15W，可能低于你的常规月薪目标；仅作为能源垂直破格项，先确认固定薪资。',
    degreeGate: '2027届全日制本科及以上；本科方向含计算机、电子信息、通信、电气等，未写985/211硬门槛',
    verifiedAt: '2026-10-06',
    compensation: '本科年薪8–20W（按院校层次）；食宿、五险一金、年终奖、交通/餐补、差旅支持',
  },
  {
    id: 'zhiguang-bms-software-2027',
    company: '智光电气',
    role: '嵌入式软件工程师（BMS / 数字能源产品）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '广州 / 西安',
    applyUrl: 'https://www.gzzg.com.cn/SocialRecruitment/index.aspx',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2413795.htm',
    sourceLabel: '智光电气2027储能校招公告 + 官方招聘入口',
    startDate: '2026-09-08',
    endDate: null,
    deadlineNote: '通过“智光招聘”公众号/校园网申入口投递；建议尽快确认BMS软件名额',
    recommendation: 3,
    fitReason: '公司核心是数字能源、储能、微电网、源网荷储和虚拟电厂，BMS嵌入式软件岗位接受计算机/软件专业，能沉淀能源产品和系统能力。',
    riskNote: '不是纯产品经理岗位，偏嵌入式研发；薪资未在本届公告公开，投前确认固定薪资、工作地点和是否需要电气基础。',
    degreeGate: '2027届本科及以上；嵌入式软件工程师BMS方向明确接受软件工程、计算机等专业，未写985/211限制',
    verifiedAt: '2026-10-06',
    compensation: '本届未公开；六险一金、年终奖金、双休、宿舍/食堂/班车、广州户口支持',
  },
  {
    id: 'xinyueneng-cim-energy-2027',
    company: '芯粤能半导体',
    role: 'IT / CIM工程师（MES、APC、EAP数字化工厂）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '广州南沙',
    applyUrl: 'https://career.gdut.edu.cn/campus/view/id/1020897',
    sourceUrl: 'https://career.gdut.edu.cn/campus/view/id/1020897',
    sourceLabel: '芯粤能2027校招公告与网申二维码页面',
    startDate: '2026-09-15',
    endDate: '2026-12-01',
    deadlineNote: '高校页面标注12月1日过期；需通过公众号/二维码进入校招渠道',
    recommendation: 3,
    fitReason: '碳化硅芯片产品服务新能源汽车、工控、光伏储能和智能电网；IT/CIM工程师负责MES/APC/EAP系统、自动化脚本和数字化工厂集成，属于能源制造B端软件入口。',
    riskNote: '工作更偏制造IT/系统集成，不是传统产品经理；但双休和数字化工厂经验是破格理由，需确认是否有夜班/产线支持。',
    degreeGate: '2027届本科/硕士；计算机应用、软件工程、通信、自动化控制可投，未写985/211限制',
    verifiedAt: '2026-10-06',
    compensation: '公告写明有竞争力薪酬、六险一金、双休、宿舍和三餐；往届公开年薪参考10–25W，投前确认本届口径',
  },
  {
    id: 'hkaco-software-solution-2027',
    company: '虹科电子',
    role: '解决方案工程师（企业软件 / AI应用方向）',
    tracks: ['B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 苏州 / 广州 / 北京 / 成都 / 西安',
    applyUrl: 'https://job.hkaco.com/technologyandrdpost/',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80647.html',
    sourceLabel: '虹科2027校招岗位表 + 官方技术岗页面',
    startDate: '2026-09-17',
    endDate: null,
    deadlineNote: '2027校招技术岗仍在开放；官方页面以邮件投递为主，建议尽快发送简历',
    recommendation: 3,
    fitReason: '岗位不是传统产品经理，但核心工作是企业软件、数据管理和AI应用的需求访谈、方案设计、产品选型、Demo/POC与竞品文档，适合B端产品/解决方案路线。',
    riskNote: '客户侧、售前、短期出差和项目交付占比高；只投软件方向，不投纯销售、售后或低空/汽车技术传播岗。',
    degreeGate: '2027届本科及以上；计算机、软件、网络安全、人工智能、数据科学等相关专业，未写985/211限制',
    verifiedAt: '2026-10-06',
    compensation: '15–20K/月（高校招聘平台公开区间）；五险一金、补充商业保险、绩效奖金和出差补贴',
  },
  {
    id: 'shining3d-product-reserve-2027',
    company: '先临三维',
    role: '产品经理储备 / 产品应用工程师（3D视觉与智能制造）',
    tracks: ['AI应用产品', '智能硬件/IoT', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '杭州 / 成都 / 深圳 / 北京 / 天津 / 全国技术支持区域',
    applyUrl: 'https://shining3d.zhiye.com/campus',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80710.html',
    sourceLabel: '先临三维2027校园招聘公告 + 官方投递入口',
    startDate: '2026-09-17',
    endDate: '2026-12-17',
    deadlineNote: '高校页面标注12月17日过期；产品/产品应用岗位可能分批关闭，建议尽早投递',
    recommendation: 3,
    fitReason: '3D视觉、AI与工业数字化产品覆盖汽车、能源重工、工程机械等行业，公开岗位包含产品经理储备和产品应用工程师，能积累硬件+软件产品经验。',
    riskNote: '产品经理储备的具体业务线和学历口径需在官网岗位页确认；不要选择项目管理工程师，产品应用岗可能含客户现场支持。',
    degreeGate: '2026/2027届本科及以上；公告开放产品经理储备、产品应用工程师等方向，未写985/211限制',
    verifiedAt: '2026-10-06',
    compensation: '10K以上（高校招聘公告公开下限）；五险一金、带薪年假、交通/餐补、员工持股及研发奖励',
  },
  {
    id: 'beisen-ai-saas-product-2027',
    company: '北森云计算',
    role: '软件产品经理（AI HR SaaS）',
    tracks: ['B端软件/平台', 'AI应用产品', '知识图谱/数据产品'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 成都',
    applyUrl: 'https://beisen.zhiye.com/campus/jobs',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/89658.html',
    sourceLabel: '北森云计算2027软件产品经理校招公告',
    startDate: '2026-09-18',
    endDate: null,
    deadlineNote: '校招通道已开放；以官方岗位状态为准，建议尽早投递',
    recommendation: 4,
    fitReason: '企业级HR SaaS与AI HR专家平台，工作包含用户研究、需求分析、功能设计、数据反馈和产品运营，属于明确的B端产品主岗。',
    riskNote: '行业是HR SaaS而非能源；优先投软件产品经理，不要误投交付经理、系统支持顾问等实施服务岗。',
    degreeGate: '2027届本科及以上；计算机、软件、心理学、人力资源、管理学等相关专业，未写985/211限制',
    verifiedAt: '2026-09-30',
    compensation: '15–20K/月（校招公告）；招聘人数40人，北京/成都，产品岗实习经验优先',
  },
  {
    id: 'jiufang-ai-data-product-2027',
    company: '九方云',
    role: 'AI产品经理（数据与智能运营）',
    tracks: ['AI应用产品', 'B端软件/平台', '知识图谱/数据产品'],
    ownership: '私企',
    scale: '中厂',
    city: '上海',
    applyUrl: 'https://www.nowcoder.com/jobs/detail/466589?urlSource=sitemap',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/466589?urlSource=sitemap',
    sourceLabel: '九方云2027 AI产品经理具体岗位页',
    startDate: '2026-09-09',
    endDate: '2026-12-31',
    deadlineNote: '岗位页标注投递至12月31日；具体状态以岗位页为准',
    recommendation: 3,
    fitReason: '负责智能化运营中台、用户分层、智能匹配、自动化触达与数据指标体系，岗位名称虽偏运营但核心是AI数据产品规划。',
    riskNote: '业务更偏金融/运营增长，不是能源；工作节奏和业务属性需在沟通时确认，作为高薪AI产品备选。',
    degreeGate: '2027届本科及以上；计算机、人工智能、大数据、统计学、软件工程、金融、数据分析等相关专业，未写985/211限制',
    verifiedAt: '2026-09-30',
    compensation: '20–30K/月×12薪（岗位页）；上海，AI/数据产品或平台产品实习优先',
  },
  {
    id: 'mingyuan-b2b-ai-product-2027',
    company: '明源云',
    role: '产品经理（B端SaaS / AI企业管理）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳 / 北京 / 上海 / 广州',
    applyUrl: 'https://www.mingyuanyun.com/recruit',
    sourceUrl: 'https://career.hebut.edu.cn/correcruit/content/id/80636.html',
    sourceLabel: '明源云2027校招公告 + 高校就业网',
    startDate: '2026-09-16',
    endDate: null,
    deadlineNote: '产品经理岗位已开放；产研岗位滚动更新，建议尽早投递',
    recommendation: 4,
    fitReason: '7000+企业客户的PaaS/SaaS产品，产品经理直接做需求调研、功能设计、研发协同和数据反馈；AI CRM、AI客服等场景与B端AI经历可对接。',
    riskNote: '行业垂直是不动产数字化，不是能源；项目顾问岗偏实施交付不要误投，优先选择产品经理/产品运营。',
    degreeGate: '2027届本科及以上；专业不限，计算机/软件/数据类优先，未写985/211限制',
    verifiedAt: '2026-09-20',
    compensation: '转正10K以上；五险一金、住房/餐补/通讯补贴、商业意外险、带薪假期',
  },
  {
    id: 'threatbook-ai-product-2027',
    company: '微步在线',
    role: '产品经理 / 产品运营（威胁情报与AI安全）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 上海 / 杭州 / 武汉 / 成都等',
    applyUrl: 'https://app.mokahr.com/m/campus_apply/threatbook/39679?recommendCode=DSkqt7Cx#/jobs',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116958.html',
    sourceLabel: '微步在线2027校招公告 + 官方投递入口',
    startDate: '2026-08-27',
    endDate: null,
    deadlineNote: '校招通道已开放；以官方岗位状态为准，建议尽早完成投递',
    recommendation: 3,
    fitReason: '威胁情报TI+AI的企业级安全产品，产品经理/运营属于明确的B端产品序列；公开本科起薪18万，符合高薪中厂例外。',
    riskNote: '破格推荐：公告写明政治面貌为中共党员或共青团员，投前确认自己是否满足；安全行业知识和北京/一线城市适应度也很重要。',
    degreeGate: '2027届本科/硕士/博士；专业不限，计算机/信息安全等更匹配；公告含党员或团员要求',
    verifiedAt: '2026-09-20',
    compensation: '本科18万起、冲刺35万（官方校招公告）；八险一金、期权、特别假期',
  },
  {
    id: 'qiyuan-energy-product-2027',
    company: '启源芯动力',
    role: '产品经理 / 产品运营（新能源商用车能源服务）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品'],
    ownership: '混合所有制',
    scale: '中厂',
    city: '上海 / 全国多城市',
    applyUrl: 'https://spicqyxdl.zhiye.com/campus/jobs?shareId=77171b07-0895-4668-a643-0ab247ef5265&shareSource=2',
    sourceUrl: 'https://career.hebut.edu.cn/correcruit/content/id/79135.html',
    sourceLabel: '启源芯动力2027校招岗位公告 + 官方入口',
    startDate: '2026-08-14',
    endDate: null,
    deadlineNote: '岗位滚动招聘，招满可能提前关闭；优先投产品经理、产品运营、能源管理',
    recommendation: 5,
    fitReason: '新能源商用车、电池银行、换电网络、智能微电网和能源服务平台，产品经理职责含需求分析、竞品研究、数据分析和功能迭代，和电力能源+B端经历高度重合。',
    riskNote: '破格推荐：岗位池还包含运营、场站和客户服务，投递时只选产品/产品运营/能源管理；部分岗位可能有区域运营和出差。',
    degreeGate: '2027届本科开放；经管、能源动力、机械、电气、自动化等专业为主，未写985/211限制',
    verifiedAt: '2026-09-20',
    compensation: '实习及转正均标注10K以上；六险一金、年假、节礼、体检、餐补/通讯补贴',
  },
  {
    id: 'novastar-product-solution-2027',
    company: '诺瓦星云',
    role: '产品与解决方案工程师（显示/硬件产品）',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '西安 / 北京 / 深圳 / 全国办事处',
    applyUrl: 'https://novastar.zhiye.com/campus/jobs?shareId=3155d34e-7412-4ac3-805f-228299ae331f&shareSource=2&qr=1&memory=%7B%7D&silence=1',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/462610',
    sourceLabel: '诺瓦星云2027具体岗位页 + 校招入口',
    startDate: '2026-08-21',
    endDate: null,
    deadlineNote: '具体岗位当前可投；官网未公布统一截止，岗位可能滚动关闭',
    recommendation: 3,
    fitReason: '岗位名称不是产品经理，但负责产品与解决方案设计、客户需求机会挖掘、竞品分析和向研发反馈优化，属于典型技术产品/售前产品化工作。',
    riskNote: '破格推荐：薪资未公开，且要求理工科电路基础、接受全国办事处；投前先确认月薪下限和长期出差比例。',
    degreeGate: '2027届本科及以上；电子、电气、自动化、通信等理工科优先，未写985/211限制',
    verifiedAt: '2026-09-20',
    compensation: '面议；投前确认月薪与补贴，岗位页未公开具体区间',
  },
  {
    id: 'sifang-power-service-2027',
    company: '四方股份',
    role: '调试 / 工程服务工程师（电网、新能源与电力电子）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 保定 / 南京 / 深圳 / 湖州等',
    applyUrl: 'https://sf-auto1.zhiye.com/campus/jobs?shareId=6ae9525a-b100-487e-b3e6-9c20c72f6a90&shareSource=2&qr=1&memory=%7B%7D&silence=1',
    sourceUrl: 'https://career.hebut.edu.cn/recruitment/content/type/2/id/5230.html',
    sourceLabel: '四方股份2027全球校招岗位表',
    startDate: '2026-08-24',
    endDate: '2026-11-30',
    deadlineNote: '官方岗位表标注11月30日前完成；计算机本科可投调试/工程服务',
    recommendation: 3,
    fitReason: '电网自动化、配网、新能源和电力电子场景非常垂直；本科计算机可投调试和工程服务，能够积累电力产品、客户现场和系统联调经验。',
    riskNote: '破格推荐：不是纯产品且现场属性明显；不投项目管理，只有接受电力现场与技术服务时再投。',
    degreeGate: '2027届本科及以上；计算机、电子信息等专业可投调试/工程服务，未写985/211限制',
    verifiedAt: '2026-09-20',
    compensation: '调试工程师10–15K/月（岗位表）；工程服务约8–10K，八险一金与补贴',
  },
  {
    id: 'vivo-platform-product-2027',
    company: 'vivo',
    role: '产品经理（平台方向）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '东莞 / 深圳 / 杭州等',
    applyUrl: 'https://hr-campus.vivo.com/campus/jobs?shareId=307651af-8827-443a-9fe0-ebd5a0f3e724&shareSource=2',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116682.html',
    sourceLabel: 'vivo官方网申入口 + 2027校招公告',
    startDate: '2026-08-11',
    endDate: '2026-09-15',
    deadlineNote: '已于9月15日12:00截止；你已完成投递，后续只按实际通知提醒',
    recommendation: 4,
    fitReason: '已投递的平台产品方向，能承接平台需求分析、跨团队协作和AI应用经验；作为真实流程继续跟踪。',
    riskNote: '竞争强且非能源垂直；等待筛选结果即可，不把研发岗笔试时间误当作你的流程提醒。',
    degreeGate: '2027届本科及以上开放；本次具体岗位已成功投递',
    verifiedAt: '2026-09-15',
    compensation: '本届未公开；以面试或Offer沟通为准',
    initialStage: '已投递',
    initialAppliedAt: '2026-09-15',
  },
  {
    id: 'engergy-ai-energy-solution-2027',
    company: '英集动力',
    role: '解决方案 / 技术咨询工程师（AI+能源）',
    tracks: ['能源数字化/央国企', 'AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '成长公司',
    city: '杭州 / 常州 / 郑州 / 北京 / 西安 / 无锡等',
    applyUrl: 'https://job.zut.edu.cn/module/position_brief_detail/id-113985/nid-6287',
    sourceUrl: 'https://job.zut.edu.cn/module/position_brief_detail/id-113985/nid-6287',
    sourceLabel: '高校就业网2027具体岗位与待遇页',
    startDate: '2026-09-08',
    endDate: null,
    deadlineNote: '2027校招已开放；招聘页未公布统一截止，支持招聘平台或内推投递',
    recommendation: 5,
    fitReason: '物理AI、能源数字孪生、源网荷储与B端方案高度集中；岗位参与方案设计、产品规划与需求沉淀，是典型的“非产品经理名称、产品化工作”。',
    riskNote: '破格推荐：包含客户现场和项目实践；岗位专业偏能源/控制/计算机，投递前强调电力场景、AI建模与需求抽象，不选择纯项目经理。',
    degreeGate: '2027届应届生；计算机、AI、控制、能源动力等专业开放，解决方案岗公开信息含本科路径，未写名校硬门槛',
    verifiedAt: '2026-09-15',
    compensation: '10–15K/月；六险一金、双休、弹性考勤、带薪年假',
  },
  {
    id: 'fanruan-fde-ai-solution-2027',
    company: '帆软',
    role: 'FDE解决方案工程师（AI / RAG / Agent）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '南京 / 无锡 / 杭州 / 上海 / 北京 / 成都等',
    applyUrl: 'https://join.fanruan.com/campus/detail?id=9889',
    sourceUrl: 'https://join.fanruan.com/campus/detail?id=9889',
    sourceLabel: '帆软官方2027具体岗位页',
    startDate: '2026-09-01',
    endDate: null,
    deadlineNote: '官方岗位当前可投，未公布统一截止；招满可能提前关闭',
    recommendation: 4,
    fitReason: '不叫产品经理，但工作覆盖AI解决方案设计、客户需求洞察、产品反馈闭环和可复用方案沉淀，RAG/Agent/私有化部署与B端AI方向贴合。',
    riskNote: '破格推荐：归属客户服务类项目岗位，包含售前、POC、培训和客户赋能；若不接受客户侧工作则降低优先级。',
    degreeGate: '2027届本科及以上；计算机、人工智能等专业优先，未写985/211限制',
    verifiedAt: '2026-09-15',
    compensation: '13–17K/月 + 绩效奖金（官方岗位页）',
  },
  {
    id: 'siemens-sales100-2027',
    company: '西门子',
    role: '数字化工业 Sales100 培训生（工业数字化解决方案）',
    tracks: ['B端软件/平台', '智能硬件/IoT', 'AI应用产品'],
    ownership: '外企',
    scale: '大型科技企业',
    city: '北京 / 上海 / 深圳 / 南京 / 苏州 / 杭州 / 西安等',
    applyUrl: 'https://jobs.siemens.com.cn/',
    sourceUrl: 'https://www.siemens.com/zh-cn/company/jobs/campus-recruiting/',
    sourceLabel: '西门子官方2027校园招聘页',
    startDate: '2026-09-14',
    endDate: null,
    deadlineNote: '官方建议10月下旬前完成投递；可同时申请最多3个岗位',
    recommendation: 4,
    fitReason: '本科计算机/AI可投，直接面向工业数字化和智能制造客户做解决方案；外企官方写明混合办公、拒绝996与系统培训，符合工作节奏例外。',
    riskNote: '破格推荐：本质是解决方案销售培养项目，有客户和业绩属性；若更看重纯产品路线，应排在能源产品岗之后。',
    degreeGate: '2027届本科及以上；计算机、人工智能、电气、自动化等理工科优先，未写名校硬门槛',
    verifiedAt: '2026-09-15',
    compensation: '未公开；混合办公、官方“拒绝996”、员工股票计划等福利',
  },
  {
    id: 'ronds-software-product-2027',
    company: '容知日新',
    role: '软件产品经理（AI工业监测 / 电力场景）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品'],
    ownership: '私企', scale: '中厂', city: '合肥',
    applyUrl: 'https://career.scnu.edu.cn/detail/job?id=2581456&online_id=3591408',
    sourceUrl: 'https://career.scnu.edu.cn/detail/online?id=3591408',
    sourceLabel: '企业发布的2027高校简章与独立岗位',
    startDate: '2026-08-31', endDate: null,
    deadlineNote: '开始日期为岗位发布日期；9月10日页面提供投递，未公布截止',
    recommendation: 5,
    fitReason: '工业状态监测平台覆盖电力等场景，产品工作包含需求、平台规划和大模型应用探索，可承接能源与B端AI经历。',
    riskNote: '软件产品岗仅1人；需补设备预测性维护场景。电力是客户行业之一，不承诺分配电力业务。',
    degreeGate: '2027届本科及以上；计算机、AI、统计、通信、电子信息等；未写985/211限制',
    verifiedAt: '2026-09-10', compensation: '14–20K/月（本届软件产品岗）；五险一金及餐/房等补贴',
  },
  {
    id: 'huice-b2b-product-2027',
    company: '慧策（掌上先机 / 旺店通）',
    role: '产品经理—2027届高潜校招（J15116）',
    tracks: ['B端软件/平台'],
    ownership: '私企', scale: '中厂', city: '北京',
    applyUrl: 'https://www.nowcoder.com/jobs/detail/459148?urlSource=sitemap',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/459148?urlSource=sitemap',
    sourceLabel: '企业招聘人员发布的2027高潜产品岗位',
    startDate: '2026-08-11', endDate: null,
    deadlineNote: '招聘页可申请；平台2029长有效期不当作秋招截止，具体截止未公布',
    recommendation: 5,
    fitReason: '企业级ERP/WMS场景，主要做需求分析、产品规划设计和数据迭代；B端业务流程与产品实习经验可迁移。',
    riskNote: '不是能源垂直，需补电商库存/订单履约；校招与实习同时招，选择2027高潜全职，不误选实施管培生。',
    degreeGate: '本科及以上、专业不限，明确欢迎计算机类；未写名校硬门槛',
    verifiedAt: '2026-09-10', compensation: '15–25K/月×13薪（2027高潜岗公开；非实习日薪）',
  },
  {
    id: 'intsig-data-product-2027',
    company: '合合信息',
    role: '数据产品经理—27届秋招（J14511）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企', scale: '中厂', city: '苏州',
    applyUrl: 'https://intsig.zhiye.com/campus/jobs',
    sourceUrl: 'https://cn.linkedin.com/jobs/view/27届秋招-数据产品经理-j14511-at-合合信息-4460900438',
    sourceLabel: '本届具体岗位（领英/猎聘）+ 官方校招入口',
    startDate: null, endDate: null,
    deadlineNote: '9月10日核实岗位在招；官网搜索J14511，未公布统一截止',
    recommendation: 4,
    fitReason: '启信宝企业数据产品，包含需求挖掘、产品设计、数据治理及大模型应用；与B端数据/AI经验相关，不是项目经理。',
    riskNote: '需要SQL与数据治理能力；投前体验启信宝。不误选名称相近的纯质检岗或学历要求不同的其他AI岗。',
    degreeGate: '本科及以上；未限定专业、未写名校硬门槛，SQL/数据库与大模型经验重要',
    verifiedAt: '2026-09-10', compensation: '13–18K/月（本届J14511岗位公开基本薪酬范围）',
  },
  {
    id: 'kylin-product-2027',
    company: '麒麟软件',
    role: '2027校招产品经理（国产OS / AI融合）',
    tracks: ['B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '央企', scale: '中厂', city: '北京 / 上海 / 长沙',
    applyUrl: 'https://kylinos.zhiye.com/campus/detail?jobAdId=dec97eba-f7eb-4397-8b2a-9c1f543bd429',
    sourceUrl: 'https://www.kylinos.cn/about/job/campusRecruitment/index.html',
    sourceLabel: '麒麟软件官网2027独立产品岗位及投递链接',
    startDate: '2026-09-04', endDate: null,
    deadlineNote: '开始日期为官方岗位发布日期；9月10日仍展示投递地址，截止未公布',
    recommendation: 3,
    fitReason: '中国电子旗下软件子公司，做产品规划、用户需求、OS与端侧AI融合；计算机本科是官方明确要求。',
    riskNote: '有版本配置、生态适配协调和技术文档工作，不是纯业务PRD岗；需补Linux/开源知识。不投同页科技创新项目助理。',
    degreeGate: '2027届本科及以上；计算机/软件工程/电子信息相关；未写985/211硬限制',
    verifiedAt: '2026-09-10', compensation: '未公开；央企不设薪资下限，未找到同岗可靠参考，不编数字',
  },
  {
    id: 'richinfo-ai-product-2027',
    company: '彩讯科技',
    role: 'AI产品经理（大模型 / 智能体方向）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企', scale: '中厂', city: '北京 / 广州 / 深圳 / 杭州 / 成都',
    applyUrl: 'https://www.richinfo.cn/jobs/campus',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/111001.html',
    sourceLabel: '彩讯官网校招页 + 南开就业网2027独立岗位',
    startDate: '2026-09-09', endDate: '2026-12-08',
    deadlineNote: '岗位9月9日发布；12月8日为高校就业网公示过期时间，官网可能提前关闭，建议尽早投递',
    recommendation: 5,
    fitReason: '面向政企客户做Agent能力、RAG知识库、产品原型、评测与数据迭代，属于明确的B端AI产品岗；公司业务覆盖能源等重点行业。',
    riskNote: '职责包含协调研发、设计和交付团队推进落地，但主体是产品方案、知识库与评测，不是项目经理或实施交付岗；面试时确认是否长期驻场。',
    degreeGate: '2027届本科及以上；计算机、人工智能、信息管理等相关专业；未写985/211或研究生硬门槛',
    verifiedAt: '2026-09-14', compensation: '月薪参考10.5K起；校招公开年薪18–30万+期权（不同渠道口径，投前确认基本月薪）',
  },
  {
    id: 'autohome-b2b-product-2027',
    company: '车之家',
    role: 'B端产品经理（车商CRM / SaaS / 供应链）',
    tracks: ['B端软件/平台'],
    ownership: '私企', scale: '中厂', city: '北京',
    applyUrl: 'https://www.nowcoder.com/jobs/detail/466943',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/466943',
    sourceLabel: '企业校园招聘人员发布的2027具体岗位',
    startDate: '2026-09-10', endDate: '2026-12-31',
    deadlineNote: '招聘页标注投递至12月31日；岗位可能提前招满，建议9月内投递',
    recommendation: 4,
    fitReason: '直接面向车商与内部运营团队，覆盖商家管理、CRM、SaaS、供应链和结算系统，核心是复杂B端流程抽象与产品设计。',
    riskNote: '汽车交易而非能源垂直；需要准备商家入驻、车源、订单履约和结算的业务流程拆解，不要误投同公司的C端内容岗位。',
    degreeGate: '2027届统招本科及以上；计算机、软件工程、信息管理、人工智能等优先；未写985/211或研究生硬门槛',
    verifiedAt: '2026-09-14', compensation: '18–22K/月×16薪（本届具体岗位公开）',
  },
  {
    id: 'cmic-ai-product-2027',
    company: '中移互联网',
    role: '产品经理（AI产品方向）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '央企', scale: '中厂', city: '广州',
    applyUrl: 'https://www.hotjob.cn/wt/zyhl/web/index/webPosition210!getOnePosition?brandCode=1&columnId=1&lanType=1&postIdEnc=fe48b1e41eba8de4&recruitType=1',
    sourceUrl: 'https://www.hotjob.cn/wt/zyhl/web/index/webPosition210!getOnePosition?brandCode=1&columnId=1&lanType=1&postIdEnc=fe48b1e41eba8de4&recruitType=1',
    sourceLabel: '中移互联网官方2027独立岗位页',
    startDate: '2026-09-03', endDate: null,
    deadlineNote: '官方岗位仍可申请，未公布统一截止；进入页面后需登录/注册投递',
    recommendation: 3,
    fitReason: '岗位直接做AI需求挖掘、产品方案、数据看板和迭代，明确涉及大模型、知识库与智能体；央企子公司且计算机本科可投。',
    riskNote: '业务可能偏个人互联网产品，不保证进入政企B端；面试时确认具体产品线，并重点展示RAG知识库和AI评测案例。',
    degreeGate: '本科及以上；计算机、电子信息、数学类优先；无经验可投，未写985/211或研究生硬门槛',
    verifiedAt: '2026-09-14', compensation: '未公开；央企不设薪资下限，未找到本届同岗可靠报价，不编数字',
  },
  {
    id: 'lalamove-strategy-product-2027',
    company: '货拉拉',
    role: '策略产品经理（货运装卸货点）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企', scale: '大型科技企业', city: '深圳',
    applyUrl: 'https://app.mokahr.com/m/campus-recruitment/huolalahr/98660?recommendCode=DSAFE5Ua#/jobs',
    sourceUrl: 'https://m.zhipin.com/zhaopin/298301ce32a28e331nV_2tW9FQ~~/',
    sourceLabel: '2027校招项目页 + 当前具体产品岗位',
    startDate: '2026-08-12', endDate: '2026-10-12',
    deadlineNote: '校招项目公开网申期；内推码 DSAFE5Ua，岗位可能提前招满',
    recommendation: 3,
    fitReason: '具体工作是货运装卸货点推荐策略、需求分析和数据迭代，属于真实产品岗，不是项目管理或客户交付。',
    riskNote: '物流平台而非能源电力，竞争偏强；投前在内推页确认“策略产品经理”仍开放，不要误选运营或履约项目岗。',
    degreeGate: '2027校招，本科可投；具体岗位未写985/211或研究生硬门槛',
    verifiedAt: '2026-09-14', compensation: '16–26K/月（当前同届具体岗位公开）',
  },
  {
    id: 'ninebot-navimow-product-2027',
    company: '九号公司旗下未岚大陆（Navimow）',
    role: '软件产品经理（智能割草机器人）',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企', scale: '中厂', city: '北京',
    applyUrl: 'https://app.mokahr.com/campus-recruitment/weilandalu',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/465296',
    sourceLabel: '企业招聘人员发布的2027具体岗位 + 官方校招入口',
    startDate: '2026-08-04', endDate: '2026-11-30',
    deadlineNote: '具体岗位公开投递期；这是未岚大陆独立入口，不使用九号集团通用内推码',
    recommendation: 4,
    fitReason: '软件全生命周期、PRD与算法/软件协作，计算机本科可投；机器人软硬件与AI产品经历可直接迁移。',
    riskNote: '不是能源/B端方向，需补智能割草机器人场景；职责中的研发里程碑协作属于产品推进，不是客户实施交付。',
    degreeGate: '2027届本科及以上；计算机相关专业；未写985/211或研究生硬门槛',
    verifiedAt: '2026-09-14', compensation: '15–30K/月×15薪（本届具体岗位公开）',
  },
  {
    id: 'dji-digital-2027',
    company: '大疆创新',
    role: '数字管理构建者计划',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 上海 / 北京',
    applyUrl: 'https://careers.dji.com/zh-CN/campus/digital-recruitment',
    sourceUrl: 'https://careers.dji.com/zh-CN/campus/digital-recruitment',
    sourceLabel: '官方项目页',
    startDate: '2026-08-07',
    endDate: null,
    deadlineNote: '招满即止；不占常规校招投递次数',
    recommendation: 2,
    fitReason: '规则拆解、复杂B端系统、AI与业务协同都高度贴合清能和达观经历。',
    riskNote: '强调理工背景与把业务逻辑转成可运行规则，需准备可量化案例。',
    degreeGate: '2027届及优秀2026届，理工背景优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'oppo-ai-pm-2027',
    company: 'OPPO',
    role: '互联网产品经理（AI方向）',
    tracks: ['AI应用产品'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '深圳 / 成都',
    applyUrl: 'https://careers.oppo.com/university/oppo/campus/post?shareId=19939',
    sourceUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1825?recruitType=Graduate',
    sourceLabel: '官方2027具体岗位页 + 内推入口',
    startDate: '2026-07-15',
    endDate: null,
    deadlineNote: '招满即止；内推码 X1757111。你提供的提醒：9月18日发笔试，具体岗位是否笔试以邮件为准',
    recommendation: 2,
    fitReason: 'AI PRD、Agent、评测和AI Coding要求，能承接达观与个人AI MVP。',
    riskNote: '没有能源/B端垂直，竞争强，放在后排；明确要求能读懂代码并展示AI Coding案例，需准备可运行Demo。',
    degreeGate: '2027届本科及以上；人工智能、软件工程、计算机相关；未写985/211限制',
    verifiedAt: '2026-09-14',
    compensation: '参考20–40K/月（深圳经验不限AI产品岗；本届官方未公开）',
  },
  {
    id: 'oppo-internet-pm-2027',
    company: 'OPPO',
    role: '互联网产品经理',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 成都',
    applyUrl: 'https://careers.oppo.com/university/oppo/campus/post/1860',
    sourceUrl: 'https://careers.oppo.com/university/oppo/campus/post/1860',
    sourceLabel: '官方岗位页',
    startDate: '2026-07-15',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 1,
    fitReason:
      '互联网、数据产品与手机软件场景，匹配平台产品和设备—软件协同能力。',
    riskNote: 'C端产品Sense与数据分析要求较强，面试需准备手机/IoT产品拆解。',
    degreeGate: '本科及以上；理工专业优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'baidu-ai-pm-2027',
    company: '百度',
    role: 'AI产品经理（J100665）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '北京',
    applyUrl: 'https://talent.baidu.com/jobs/list?projectType=1',
    sourceUrl: 'https://talent.baidu.com/jobs/list?projectType=1',
    sourceLabel: '官方岗位列表',
    startDate: '2026-07-21',
    endDate: null,
    deadlineNote: '官网未公布，岗位滚动处理',
    recommendation: 1,
    fitReason:
      '大模型产品规划、跨算法研发协作和数据反馈闭环与现有AI经历高度一致。',
    riskNote: '竞争强，需要能讲清RAG质量、Agent边界和核心指标。',
    degreeGate: '2027届；学历要求以岗位页为准',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'alibaba-cloud-product-2027',
    company: '阿里云',
    role: '产品类（2027届应届生）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '杭州 / 北京 / 上海 / 深圳 / 成都 / 广州 / 南京',
    applyUrl:
      'https://campus-talent.alibaba.com/campus/position?batchId=100000760001',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116681.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-11',
    endDate: null,
    deadlineNote: '官网未公布；最多2个意向',
    recommendation: 1,
    fitReason: '云与AI+B端平台是达观、清能两段经历最自然的交集。',
    riskNote: '大厂竞争强，投递后意向不可修改，需先核具体团队JD。',
    degreeGate: '2026.11—2027.10毕业；逐岗核对学历',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'alibaba-group-product-2027',
    company: '阿里巴巴集团',
    role: '产品类（16个业务团队）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '杭州 / 北京 / 上海 / 深圳等',
    applyUrl: 'https://campus-talent.alibaba.com/campus/gov',
    sourceUrl: 'https://campus-talent.alibaba.com/campus/gov',
    sourceLabel: '官方校招页',
    startDate: null,
    endDate: null,
    deadlineNote: '已开放；具体批次时间未公布',
    recommendation: 1,
    fitReason: '产品职类覆盖AI、云与多业务平台，可按具体JD选择B端或AI版简历。',
    riskNote: '业务跨度大，必须逐岗定向；毕业时间口径为2026.11—2027.10。',
    degreeGate: '海内外应届毕业生，逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'xiaomi-product-2027',
    company: '小米集团',
    role: '策略产品经理（视频会员 / 内容产品）',
    tracks: ['智能硬件/IoT', 'AI应用产品'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '北京 / 南京',
    applyUrl: 'https://xiaomi.jobs.f.mioffice.cn/s/Mz6F5e_P6mA',
    sourceUrl: 'https://hireportal.us.com/cn/job/63t1ccktvf6t/job',
    sourceLabel: '2027具体岗位招聘转载 + 官方内推入口',
    startDate: '2026-09-01',
    endDate: null,
    deadlineNote: '官网未公布统一截止；内推码 88FQ6SE，选择校园大使推荐',
    recommendation: 2,
    fitReason: '2027具体产品岗，本科接受计算机相关专业，职责包含产品策略、数据分析、PRD和用户转化。',
    riskNote:
      '偏C端会员增长，不是B端或能源，竞争强，放在后排；薪资为2027校招项目区间而非该子岗基本月薪承诺。',
    degreeGate: '2027届本科及以上；计算机或相关理工科；未写985/211限制',
    verifiedAt: '2026-09-14',
    compensation: '15–20K/月（2027校招项目公开区间；具体子岗以Offer为准）',
  },
  {
    id: 'pdd-campus-2027',
    company: '拼多多',
    role: '2027校园招聘—产品/运营方向（官网筛选）',
    tracks: ['B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '上海 / 广州等',
    applyUrl: 'https://careers.pddglobalhr.com/campus/',
    sourceUrl: 'https://careers.pddglobalhr.com/campus/',
    sourceLabel: '官方校招页',
    startDate: null,
    endDate: null,
    deadlineNote: '已开放；具体岗位滚动更新',
    recommendation: 1,
    fitReason: '平台与商业产品可使用B端版简历，但现有经历偏产业和知识产品。',
    riskNote: '业务强度与C端/商业化偏好较高，先确认具体产品岗再投。',
    degreeGate: '2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'dji-campus-2027',
    company: '大疆创新',
    role: '拓疆者校招—产品/数字化方向（官网筛选）',
    tracks: ['智能硬件/IoT', 'B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 上海 / 北京',
    applyUrl: 'https://careers.dji.com/zh-CN/campus/recruitment?from=sec_nav',
    sourceUrl: 'https://careers.dji.com/zh-CN/campus/recruitment?from=sec_nav',
    sourceLabel: '官方项目页',
    startDate: '2026-06-25',
    endDate: null,
    deadlineNote: '不设截止，招满即止；限投1个职位',
    recommendation: 1,
    fitReason: '智能硬件、端云协同和数字化场景契合IoT背景。',
    riskNote: '常规校招仅一次投递且不能改，先对比数字管理计划再决定。',
    degreeGate: '2027届高校毕业生',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'anker-campus-2027',
    company: '安克创新',
    role: '硬件产品经理（智能硬件）',
    tracks: ['智能硬件/IoT'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '深圳',
    applyUrl: 'https://anker-in.jobs.feishu.cn/s/HjlCjzsg4Rc',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/463092?urlSource=sitemap',
    sourceLabel: '企业招聘人员发布的2027具体岗位 + 内推入口',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布统一截止；内推码 5X21NAN，选择校园大使推荐',
    recommendation: 3,
    fitReason: '2027具体硬件产品岗，本科理工科可投；用户洞察、产品定义、技术方案与IoT软硬件经历能形成证据链。',
    riskNote: '消费电子而非B端/能源，更重商业化、供应链和量产意识；薪资采用深圳经验不限同岗参考，本届岗位仍是面议。',
    degreeGate: '2027届本科及以上；理工科优先；未写985/211或研究生硬门槛',
    verifiedAt: '2026-09-14',
    compensation: '参考18–30K/月×16薪（深圳经验不限同岗；本届具体岗位面议）',
  },
  {
    id: 'lenovo-product-2027',
    company: '联想集团',
    role: '产品与项目方向',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '混合所有制',
    scale: '大厂',
    city: '北京 / 上海 / 深圳 / 天津 / 武汉等',
    applyUrl: 'https://talent.lenovo.com.cn/home',
    sourceUrl: 'https://job.wzu.edu.cn/campus/view/id/494874',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-05',
    endDate: '2026-11-13',
    deadlineNote: '简章称11月13日结束；建议10月前完成',
    recommendation: 1,
    fitReason: '智能设备、企业服务与项目协同都能承接B端和IoT版简历。',
    riskNote: '岗位差异大，优先找软件产品、设备平台或AI PC相关。',
    degreeGate: '本科及以上；2026.09.01—2027.08.31毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'xiaopeng-ai-product-2027',
    company: '小鹏集团',
    role: 'AI产品经理 / 产品方向',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '广州 / 深圳 / 上海 / 北京 / 武汉',
    applyUrl: 'https://xiaopeng.jobs.feishu.cn/campus',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116251.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-07-07',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 1,
    fitReason: 'AI、Agent、RAG与智能设备理解可同时发挥，物联网专业也加分。',
    riskNote: '汽车/物理AI竞争强，需用可运行AI应用和软硬件链路证明技术理解。',
    degreeGate: '本科及以上；2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'li-auto-product-2027',
    company: '理想汽车',
    role: '产品 / 整车与智能硬件方向',
    tracks: ['智能硬件/IoT', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京 / 上海 / 深圳 / 杭州 / 常州',
    applyUrl: 'https://www.lixiang.com/employ/campus/list.html?fromJob=1',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116875.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-21',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 1,
    fitReason: '产品、智能硬件、软件与具身智能多方向开放。',
    riskNote:
      '缺汽车行业项目，优先选座舱/设备软件/数字化产品，避免整车量产强门槛岗。',
    degreeGate: '本科及以上；2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'wondershare-ai-pm-2027',
    company: '万兴科技',
    role: 'AI产品经理',
    tracks: ['AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '长沙 / 深圳 / 杭州 / 北京 / 东京',
    applyUrl: 'https://bsurl.cn/v2/DBo3MpGj',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116994.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布；含秋招直招与实习转正',
    recommendation: 5,
    fitReason: 'AI Native软件产品、MVP与用户洞察非常贴合AI版简历。',
    riskNote: '部分岗位有产品体验报告，需提前拆解万兴喵影/PDF等产品。',
    degreeGate: '本科及以上；2026.09—2027.12毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'kedacom-pm-2027',
    company: '科达科技',
    role: '产品经理（2027校园招聘）',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '苏州',
    applyUrl: 'https://kedacom.zhiye.com/zpdetail/511187502',
    sourceUrl: 'https://kedacom.zhiye.com/zpdetail/511187502',
    sourceLabel: '官方2027产品经理独立岗位页',
    startDate: '2026-07-20',
    endDate: null,
    deadlineNote: '官网未公布，滚动处理',
    recommendation: 4,
    fitReason: '视讯安防、软件平台与硬件协同，比纯消费硬件更适配现有经历。',
    riskNote: '需展示原型、PRD与方案作品；涉及政企客户培训和出差，不是纯内部平台岗。官网面议，转载薪资不代表Offer。',
    degreeGate: '官方明确2027届本科及以上；未写985/211限制，政企产品经历优先',
    verifiedAt: '2026-09-10',
    compensation: '参考13–23K/月（同届同岗招聘转载；官网面议）',
  },
  {
    id: 'spirit-ai-product-2027',
    company: '千寻智能',
    role: '具身智能产品经理 / 机器人产品经理',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '成长公司',
    city: '北京 / 杭州 / 深圳',
    applyUrl: 'https://nwd4iy9rd2s.jobs.feishu.cn/campusofSpiritAI',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116725.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-10',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 2,
    fitReason: 'AI与硬件交叉方向高度相关，GreenAuto可作基础证据。',
    riskNote: '团队门槛很高，偏好顶会/专利或顶级工程项目；作为冲刺项。',
    degreeGate: '本科/硕士/博士；2026.09—2027.12毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'chinatelecom-campus-2027',
    company: '中国电信',
    role: '行业/区域解决方案经理（产数类）',
    tracks: ['B端软件/平台', '能源数字化/央国企'],
    ownership: '央企',
    scale: '大厂',
    city: '全国',
    applyUrl: 'https://job.chinatelecom.com.cn/wt/TELE/web/index?_refluxos=a10',
    sourceUrl: 'https://www.chinatelecom.com.cn/ct/zp/168256.html',
    sourceLabel: '集团招聘公告 + 官方岗位页',
    startDate: '2026-08-24',
    endDate: null,
    deadlineNote: '各分子公司自行确定截止',
    recommendation: 3,
    fitReason: '岗位直接负责行业客户需求、场景化方案、招投标和售前交付，B端经历与物联网专业都能复用。',
    riskNote: '央企大平台但不是电力垂直，优先投普通产数岗位，避开明确面向重点高校的“优才计划”。',
    degreeGate: '本科及以上；2027届，部分单位接受未就业2026届',
    verifiedAt: '2026-09-02',
    compensation: '未公开；各分子公司口径不同',
  },
  {
    id: 'ct-digital-life-pm-2027',
    company: '天翼数字生活',
    role: '产品经理 / 产品运营',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '央企',
    scale: '中厂',
    city: '上海 / 南京 / 广州',
    applyUrl: 'https://job.chinatelecom.com.cn/wt/TELE/web/index?_refluxos=a10',
    sourceUrl:
      'https://m.fenbi.com/page/exam-information-detail/468756891196416',
    sourceLabel: '官方网申 + 招聘公告汇总',
    startDate: '2026-08-31',
    endDate: '2026-09-07',
    deadlineNote: '公告口径：9月7日截止',
    recommendation: 1,
    fitReason: '数字家庭、智慧社区和产品运营方向本身契合。',
    riskNote:
      '当前公告标注硕士/博士，与你本科学历不符；仅保留作提醒，不建议投入时间。',
    degreeGate: '硕士/博士（明确硬门槛）',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'cecloud-pm-2027',
    company: '中国电子云',
    role: '产品经理',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '央企',
    scale: '中厂',
    city: '北京 / 武汉 / 南京 / 杭州 / 成都',
    applyUrl: 'https://www.cecloud.com',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407567.htm',
    sourceLabel: '公司入口 + 高校招聘简章',
    startDate: '2026-08-27',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 3,
    fitReason: '政企云、AI平台与本体构建贴合企业知识产品和B端经历。',
    riskNote:
      '公告正文称本科可投，但高校需求表写硕士，必须先在官网核具体产品岗。',
    degreeGate: '口径冲突：招聘范围含本科，需求表写硕士',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'envision-product-2027',
    company: '远景能源',
    role: '产品类（优先新电网 / AI能源产品）',
    tracks: ['能源数字化/央国企', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '上海 / 江阴 / 全国及海外',
    applyUrl: 'https://app.mokahr.com/m/campus_apply/envisiongroup/43123?recommendCode=DSqDB4Mx#/jobs',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116772.html',
    sourceLabel: '2027校招简章（高校就业网）+ 内推入口',
    startDate: '2026-08-20',
    endDate: null,
    deadlineNote: '官网未公布统一截止，滚动招聘；内推码 DSqDB4Mx',
    recommendation: 5,
    fitReason:
      '2027项目明确开放产品类，业务覆盖新型电力系统、能源大模型和源网荷储；是本轮与AI+电力经历最贴合的机会。',
    riskNote: '只投产品类，不投解决方案、工程管理或项目交付；产品子岗名称、专业条件和基本月薪仍要在官网逐条确认。',
    degreeGate: '2027届本科/硕士/博士；集团项目未写985/211限制，具体产品子岗逐项核专业',
    verifiedAt: '2026-09-14',
    compensation: '20K+/月（2027校招项目公开口径；具体产品子岗基本月薪以Offer为准）',
  },
  {
    id: 'sungrow-campus-2027',
    company: '阳光电源',
    role: '2027全球校招—产品/解决方案方向（官网筛选）',
    tracks: ['能源数字化/央国企', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '合肥 / 上海 / 南京等',
    applyUrl: 'https://jobs.sungrowpower.com/',
    sourceUrl: 'https://jobs.sungrowpower.com/',
    sourceLabel: '官方招聘页',
    startDate: '2026-08-10',
    endDate: null,
    deadlineNote: '正式批已启动；官网未公布统一截止',
    recommendation: 5,
    fitReason: '新能源硬件、智慧能源和行业数字化与清能经历互补。',
    riskNote: '先筛产品/解决方案/数字化岗位，纯电气研发岗不匹配。',
    degreeGate: '2027届；逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'catl-campus-2027',
    company: '宁德时代',
    role: '计算机与AI / 市场 / 运营方向（官网筛选）',
    tracks: ['能源数字化/央国企', 'B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '宁德 / 上海 / 北京 / 杭州 / 武汉等',
    applyUrl: 'https://talent.catl.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116814.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布；3次志愿机会',
    recommendation: 3,
    fitReason:
      '新能源产业和计算机/AI方向开放，可寻找数字化产品、业务系统或项目岗。',
    riskNote: '公开简章未列明确产品经理，需以岗位列表为准，不要为凑方向盲投。',
    degreeGate: '本科及以上；2026.07—2027.12毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'amazon-program-2027',
    company: '亚马逊中国',
    role: 'Program Manager / Tech Business Developer',
    tracks: ['B端软件/平台'],
    ownership: '外企',
    scale: '大厂',
    city: '北京 / 上海 / 深圳',
    applyUrl:
      'https://www.amazon.jobs/content/zh/career-programs/university?country%5B%5D=CN',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116983.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布；最多申请3个职位',
    recommendation: 3,
    fitReason: '项目管理、技术业务与云服务方向可承接B端系统和跨团队协作。',
    riskNote:
      '不是标准产品经理，英语和学历要求需逐岗位核对；优先看深圳Program Manager。',
    degreeGate: '部分岗位可能偏硕士；逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'oppo-display-pm-2027',
    company: 'OPPO',
    role: '多媒体屏显产品经理',
    tracks: ['智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳',
    applyUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1829?recruitType=Graduate',
    sourceUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1829?recruitType=Graduate',
    sourceLabel: '官方岗位页',
    startDate: '2026-07-15',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 1,
    fitReason: '产品规划与硬件模块协同方向相关。',
    riskNote: '岗位明确要求硕士及以上，与本科学历不符；不建议投。',
    degreeGate: '硕士及以上（明确硬门槛）',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'duxiaoman-ai-pm-2027',
    company: '度小满',
    role: 'AI应用产品经理 / 信贷产品经理',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 上海',
    applyUrl: 'https://campus.duxiaoman.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116782.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-18',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 3,
    fitReason:
      '明确开放AI应用产品经理，金融AI、复杂规则和业务闭环与达观、清能经历都能衔接。',
    riskNote:
      '金融产品强调风险与指标意识，需准备模型能力如何转化为业务收益和合规边界。',
    degreeGate: '本科及以上；2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'insta360-ai-pm-2027',
    company: '影石 Insta360',
    role: 'AI软件产品经理（2027校招）',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'https://www.insta360.com/cn/jobs',
    sourceUrl: 'https://www.shushuqiuzhi.com/position/423563',
    sourceLabel: '官网入口 + 当前岗位页',
    startDate: '2026-06-30',
    endDate: '2026-10-31',
    deadlineNote: '招聘汇总口径10月31日截止，岗位可能提前招满',
    recommendation: 2,
    fitReason:
      'AI工具、App、多端设备体验同时匹配AI MVP、IoT专业和GreenAuto，属于非常好的交叉型中厂机会。',
    riskNote:
      '需要产品作品集与交互敏感度，建议准备AI工作流Demo和影像产品体验拆解。',
    degreeGate: '本科及以上；专业不限，软件/交互/计算机背景优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'emdoor-product-2027',
    company: '亿道数码',
    role: '产品经理（智能终端）',
    tracks: ['智能硬件/IoT', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'mailto:CR@emdoor.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116842.html',
    sourceLabel: '高校官方就业网岗位页',
    startDate: '2026-08-20',
    endDate: null,
    deadlineNote: '邮箱投递；未公布截止时间',
    recommendation: 2,
    fitReason:
      '负责智能终端产品定义、客户需求和场景分析，计算机/IoT背景可用；只看产品经理，不看项目工程师。',
    riskNote:
      '要求CET-6并重视量产与营销意识，需补充选型、测试、供应链协同案例。',
    degreeGate: '本科及以上；电子/通信/计算机/软件相关，CET-6为明确要求；未写名校限制',
    verifiedAt: '2026-09-10',
    compensation: '15–20K/月（招聘页公开区间）',
  },
  {
    id: 'yangteng-product-2027',
    company: '扬腾创新',
    role: '产品经理（技术研发序列 / 供应链数智化）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '福州',
    applyUrl: 'https://yangtenginnovation-compus.zhiye.com',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407468.htm',
    sourceLabel: '网申入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '已正式启动；官网未公布截止',
    recommendation: 4,
    fitReason:
      '2027简章在技术研发序列单列产品经理，招计算机/软件专业，业务系统与供应链数据经验可迁移。',
    riskNote: '跨境汽配场景较陌生，面试前要补供应链、库存和履约指标框架。',
    degreeGate: '2027届；计算机/软件工程相关，本科可投；名校补贴不是招聘硬门槛',
    verifiedAt: '2026-09-10',
    compensation: '13–20K/月（招聘简章公开区间）',
  },
  {
    id: 'hello-momo-product-2027',
    company: '挚文集团',
    role: '社交 / 商业 / 海外产品经理',
    tracks: ['AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '北京',
    applyUrl: 'https://campus.immomo.com',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407229.htm',
    sourceLabel: '高校招聘简章',
    startDate: '2026-08-10',
    endDate: null,
    deadlineNote: '8月10日网申启动；未公布截止',
    recommendation: 3,
    fitReason:
      '产品岗位明确开放，AI与亿级用户产品能提供产品Sense训练和冲刺机会。',
    riskNote:
      '偏C端社交与商业化，与你当前B端/行业产品证据不完全同构，需要独立准备C端案例。',
    degreeGate: '本科及以上；2026.12—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'metax-product-2027',
    company: '沐曦股份',
    role: '产品管理 / 项目管理（GPU平台）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 北京 / 南京 / 成都',
    applyUrl: 'https://www.metax-tech.com/join.html',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407387.htm',
    sourceLabel: '官方招聘页 + 高校招聘简章',
    startDate: '2026-07-31',
    endDate: null,
    deadlineNote: '7月底起网申，滚动发放Offer',
    recommendation: 3,
    fitReason:
      '国产GPU与AI基础设施是高质量B端产品场景，能发挥技术理解和平台产品能力。',
    riskNote: '产品管理岗位可能偏技术且逐岗学历不同，务必先确认是否接受本科。',
    degreeGate: '招聘范围含本科；具体产品岗需逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'ke-product-2027',
    company: '贝壳找房',
    role: '产品经理 / 策略产品 / 数据产品',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京 / 上海 / 杭州 / 广州等',
    applyUrl: 'https://campus.ke.com/campus/jobs',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117001.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-26',
    endDate: '2026-10-31',
    deadlineNote: '高校就业网标注10月31日；每类招聘项目限投1岗',
    recommendation: 1,
    fitReason:
      '产业互联网、策略与数据产品方向可直接使用B端版简历，业务复杂度也适合需求拆解优势。',
    riskNote:
      '产品细分多且只限投一个岗位，先对比策略、数据和业务产品JD再提交。',
    degreeGate: '本科及以上；2026.09.01—2027.08.31毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'fanruan-product-2027',
    company: '帆软软件',
    role: '产品经理（一体化平台）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '无锡 / 南京 / 杭州',
    applyUrl: 'https://join.fanruan.com/campus/detail?id=9869',
    sourceUrl: 'https://join.fanruan.com/campus/detail?id=9869',
    sourceLabel: '官方岗位页',
    startDate: '2026-08-01',
    endDate: null,
    deadlineNote: '9月10日官方2027岗位页仍提供投递；未公布本岗位截止',
    recommendation: 5,
    fitReason:
      '明确偏好ToB软件产品实习，企业BI、流程设计、需求到交付与你的经历直接同构，且不设名校/研究生硬门槛。',
    riskNote: '需要把清能与达观经历讲成客户价值、模块指标和0→1/1→N迭代闭环。',
    degreeGate: '2027届本科及以上，理工科背景；未写985/211限制',
    verifiedAt: '2026-09-10',
    compensation: '16–20.5K/月，SP另议（官方岗位公开）',
  },
  {
    id: 'hand-ai-consultant-2027',
    company: '汉得信息',
    role: '数智化咨询顾问（AI方向）',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '私企',
    scale: '中厂',
    city: '天津 / 河北 / 武汉 / 成都 / 西安',
    applyUrl: 'https://career.hebut.edu.cn/correcruit/content/id/73275.html',
    sourceUrl: 'https://job.hdu.edu.cn/campus/view?id=9568',
    sourceLabel: '高校招聘简章 + 岗位页',
    startDate: '2026-08-28',
    endDate: null,
    deadlineNote: '已开放，未公布统一截止',
    recommendation: 5,
    fitReason:
      '岗位明确偏好“能源+AI”复合经验，工作本质是B端需求、方案、数据/AI落地，与你的电力交易和AI经历高度重合。',
    riskNote:
      '岗位是咨询顾问而非标准产品经理，出差较多；优势是成功率和垂直复用度更高。',
    degreeGate: '本科及以上；未写985/211限制',
    verifiedAt: '2026-09-01',
    compensation: '转正8–10K/月；实习3–4.5K/月',
  },
  {
    id: 'transwarp-ai-delivery-2027',
    company: '星环科技',
    role: 'AI交付 / 售前（认知数据库与知识图谱）',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 北京 / 南京 / 广州 / 成都',
    applyUrl: 'https://app.mokahr.com/campus_apply/transwarp',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116990.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-18',
    endDate: '2026-12-31',
    deadlineNote: '8月18日—12月31日',
    recommendation: 4,
    fitReason:
      '企业级AI、GPU原生认知数据库、知识图谱及能源行业客户都能复用达观本体构建与B端交付证据。',
    riskNote:
      '当前校招未列产品经理，建议把AI交付/售前作为高匹配曲线救国岗位，不投纯研发。',
    degreeGate: '2027届本科及以上；计算机/通信/电子/网络',
    verifiedAt: '2026-09-01',
    compensation: '薪资未公开；全额五险一金、补充公积金/商保、搬家费与签字费',
  },
  {
    id: 'nio-energy-product-2027',
    company: '蔚来',
    role: '产品经理（充电/能源产品，A136978）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '上海',
    applyUrl: 'https://campus.nio.com/',
    sourceUrl:
      'https://www.recruit.net/job/%E4%BA%A7%E5%93%81%E7%BB%8F%E7%90%86-jobs/CFD4273E2B2C0766',
    sourceLabel: '官方校招入口 + 岗位镜像',
    startDate: '2026-08-27',
    endDate: null,
    deadlineNote: '正式批已开放；官网未公布统一截止，建议优先投',
    recommendation: 5,
    fitReason: '岗位同时覆盖充电硬件、能源产品、充电管理系统、PRD与AI/机器学习，和你的电力+产品+AI经历高度同构。',
    riskNote: '要求读懂电力电子基础和硬件规格；面试前补DC/DC、DC/AC、充电拓扑与能源云产品案例。',
    degreeGate: '具体岗位明确本科及以上；电气/新能源优先，计算机/AI且有电力电子经历也可',
    verifiedAt: '2026-09-14',
    compensation: '本届未公开；往届产品岗Offer参考17.5–18.5K/月×14.5薪（仅作量级参考，最终以Offer为准）',
  },
  {
    id: 'ampace-aidc-solution-2027',
    company: 'Ampace新能安',
    role: 'AIDC解决方案售前 / 储能交付',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '厦门',
    applyUrl: 'https://www.ampace.com/join-us',
    sourceUrl: 'https://career.hebut.edu.cn/correcruit/content/id/79145.html',
    sourceLabel: '官网招聘入口 + 高校招聘简章',
    startDate: '2026-08-17',
    endDate: null,
    deadlineNote: '全球校招已开放；招满为止',
    recommendation: 5,
    fitReason: 'AIDC供电、储能系统、EMS/BMS、IoT与客户方案是AI+能源的直接交叉，适合用清能和达观经历组合投递。',
    riskNote: '售前岗要求较强电力电子知识、英语和出差适应度；不要误投明确硕士的嵌入式EMS岗。',
    degreeGate: '项目面向本硕博；AIDC解决方案售前具体岗位明确本科及以上，未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '10K+/月；实习3–4.5K/月（高校页面）',
  },
  {
    id: 'sigenergy-sales-service-2027',
    company: '思格新能源',
    role: 'AI+光储 销售与服务 / 市场营销',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 南通 / 珠海',
    applyUrl: 'https://jobs.sigenergy.com/campus',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116730.html',
    sourceLabel: '官方校招入口 + 高校招聘简章',
    startDate: '2026-08-17',
    endDate: '2026-11-30',
    deadlineNote: '网申8—11月；每人2次投递机会',
    recommendation: 5,
    fitReason: '公司主线就是全场景AI+光储，销售与服务岗位可直接讲电力市场、能源客户需求和AI产品方案。',
    riskNote: '简章只公布职类，投递时优先解决方案、销售支持、客户成功类，逐岗确认专业和学历。',
    degreeGate: '2027届本硕博；校招总项目明确本科开放，未写名校硬限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开',
  },
  {
    id: 'nrec-support-2027',
    company: '南瑞继保',
    role: '技术支持 / 国内营销 / 信息技术',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '国企',
    scale: '中厂',
    city: '南京 / 常州 / 成都 / 西安 / 济南等',
    applyUrl: 'https://nrec.zhiye.com/campus',
    sourceUrl:
      'https://www.wondercv.com/xiaozhao/nanrui-jibao-2027-campus-recruitment-13172-8ca5ea/',
    sourceLabel: '官方招聘入口 + 2027校招公告汇总',
    startDate: '2026-08-24',
    endDate: '2026-10-24',
    deadlineNote: '本科生通常随对应学校宣讲截止；无宣讲学校建议10月前完成',
    recommendation: 4,
    fitReason: '电力系统自动化、储能/氢能与技术支持场景高度垂直，央国企背景不再是唯一卖点，电力实习能真正形成差异。',
    riskNote: '不是标准产品经理，优先技术支持、国内营销、信息技术；研发/设计岗通常更看专业深度。',
    degreeGate: '2027届本科明确开放；本科对应技术支持/营销/信息类方向，未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开；七险二金、宿舍等福利',
  },
  {
    id: 'yonyou-b2b-product-2027',
    company: '用友网络',
    role: '产品经理（B端，高潜）-27届',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京',
    applyUrl: 'http://career.yonyou.com',
    sourceUrl:
      'https://www.hotjob.cn/wt/yonyou/mobweb/v8/position/list?brandCode=1&recruitType=1',
    sourceLabel: '官方招聘系统',
    startDate: '2026-08-07',
    endDate: null,
    deadlineNote: '官方岗位仍在更新；未公布统一截止',
    recommendation: 5,
    fitReason: 'JD直接写ToB产品规划、企业需求抽象、应用模型与跨研发推进，和你现有B端产品证据几乎逐项对应。',
    riskNote: '标注“高潜”且抗压要求高；重点准备企业流程抽象、平台化取舍和客户需求标准化案例。',
    degreeGate: '具体岗位明确统招本科及以上；未写985/211或研究生限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开',
  },
  {
    id: 'sitech-ai-product-2027',
    company: '思特奇',
    role: 'AI产品经理（产品生态类）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '成都优先；其他城市岗位与待遇另核',
    applyUrl: 'https://mp.weixin.qq.com/s/nLFzDdUuJujXRJUKf7S1hw',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117169.html',
    sourceLabel: '官方投递说明 + 高校招聘简章',
    startDate: '2026-08-28',
    endDate: null,
    deadlineNote: '官网未公布；可通过公众号或campus邮箱投递',
    recommendation: 3,
    fitReason: '2027简章单列AI产品经理，可承接B端需求与AI应用经历；不再混入方案、项目管理和综合职能。',
    riskNote: '具体AI产品岗城市/学历须确认。原15–20K是整份简章区间，不能当作产品岗承诺；成都以2026届同类产品岗11–17K作参考，其他城市不套用。',
    degreeGate: '2027简章面向本硕博并列计算机/软件专业；具体AI产品岗要求仍须核对',
    verifiedAt: '2026-09-10',
    compensation: '往届参考11–17K/月×13薪（成都产品岗；本届待确认）',
  },
  {
    id: 'teld-solution-2027',
    company: '特来电',
    role: '售前 / 解决方案 / 项目工程师（电气类）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '青岛 / 西安 / 南京 / 全国大区',
    applyUrl: 'https://hr.teld.cn/recruit',
    sourceUrl: 'https://myjob.dlmu.edu.cn/campus/view/id/868552',
    sourceLabel: '官方招聘入口 + 高校招聘简章',
    startDate: '2026-08-29',
    endDate: '2026-11-20',
    deadlineNote: '高校页面标注11月20日；建议优先总部售前/解决方案',
    recommendation: 5,
    fitReason: '数字化充电网、电力交易、能源业务和B端方案与你的电力产品实习直接同构，是比泛互联网产品更值得优先的岗位。',
    riskNote: '总部售前偏电气技术，部分全国岗位偏销售；根据你对出差和业绩指标的接受度排序。',
    degreeGate: '总部电气类明确招本科；售前/解决方案岗列在本科开放类别，未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '总部电气类10.5–15K/月（高校职位表）',
  },
  {
    id: 'byd-energy-digital-2027',
    company: '比亚迪',
    role: '新能源解决方案 / 数字化 / 产品策略',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 西安 / 长沙 / 合肥等',
    applyUrl: 'https://job.byd.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117011.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-26',
    endDate: null,
    deadlineNote: '官网未公布统一截止；岗位量大，建议先锁新能源产业/电池/闪充',
    recommendation: 3,
    fitReason: '虽然是大厂，但储能、光伏、构网、电网技术、闪充运营和数字化方向属于你的垂直例外，可选择性投递。',
    riskNote: '岗位池非常宽且团队差异大；不投泛汽车研发，优先储能解决方案、闪充运营、信息化平台与产品策略。',
    degreeGate: '2027届本科/硕士/博士；项目明确本科开放，具体岗位逐项核专业',
    verifiedAt: '2026-09-02',
    compensation: '10–15K/月（高校页面总区间）',
  },
  {
    id: 'voyah-product-digital-2027',
    company: '岚图汽车',
    role: '产品企划与体验 / 智能产品平台 / 数字化发展',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '央企',
    scale: '中厂',
    city: '武汉 / 北京',
    applyUrl: 'https://app.mokahr.com/campus-recruitment/voyah/146293',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/79130.html',
    sourceLabel: '官方校招入口 + 高校招聘简章',
    startDate: '2026-08-13',
    endDate: null,
    deadlineNote: '官网未公布统一截止；按岗位滚动处理',
    recommendation: 3,
    fitReason: '央企新能源例外，且明确开放产品企划、智能产品平台和数字化发展，可作为汽车能源方向的补充投递。',
    riskNote: '偏C端汽车和用户体验，竞争与行业门槛仍高；只投与你产品/IoT经历能形成证据链的岗位。',
    degreeGate: '项目明确面向2027届本硕博，高校页面学历要求本科；未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '10.5–15K/月（高校页面）',
  },
  {
    id: 'inovance-b2b-market-2027',
    company: '汇川技术',
    role: '市场类（工业自动化/新能源解决方案）',
    tracks: ['B端软件/平台', '能源数字化/央国企', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '深圳 / 苏州 / 东莞 / 西安',
    applyUrl: 'https://recruit.inovance.com/',
    sourceUrl:
      'https://jy.scu.edu.cn/index/index/employjobdetail.html?data=MDAwMDAwMDAwMJG6n3_Ed6imi4qQtLh4Y9yK0dTOs4bddricp9CWi5qikaeWacSdqLqGfaK2w4iil5C4zNbGiL-E',
    sourceLabel: '官方招聘入口 + 高校具体岗位页',
    startDate: '2026-08-18',
    endDate: '2027-08-17',
    deadlineNote: '岗位页有效期至2027年8月17日；校招滚动筛选',
    recommendation: 4,
    fitReason: '面向设备制造商的工业自动化与新能源方案，本质是B端产品理解、客户需求和方案推介，垂直价值高。',
    riskNote: '市场类含销售目标且出差较多，不是纯产品经理；适合接受客户一线和业绩导向时投递。',
    degreeGate: '具体市场类岗位明确本科，电气/自动化/机械/电力电子相关本科或硕士；无名校硬限制',
    verifiedAt: '2026-09-15',
    compensation: '12–20K/月（具体市场类职位页）',
  },
  {
    id: 'foxess-solution-2027',
    company: '麦田能源（FOX ESS）',
    role: '解决方案工程师 / 产品文档 / 项目管理',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 无锡 / 温州 / 东莞',
    applyUrl: 'https://fox-ess.zhiye.com/',
    sourceUrl: 'https://career.gdut.edu.cn/campus/view/id/1020697',
    sourceLabel: '官方招聘入口 + 高校招聘简章',
    startDate: '2026-08-24',
    endDate: null,
    deadlineNote: '2027全球校招已开放；官网未公布统一截止',
    recommendation: 4,
    fitReason: '储能逆变器与能源解决方案是明确B端场景，规模适中，比无垂直经验去泛大厂更能利用电力经历。',
    riskNote: '解决方案岗偏电力电子且可能要求英语；高校信息页已到展示期，但官方招聘站仍需再次确认岗位状态。',
    degreeGate: '2027届本硕博；解决方案/产品文档在本科开放校招清单，未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '面议；五险一金、年终奖',
  },
  {
    id: 'kehua-digital-energy-2027',
    company: '科华数据',
    role: '产品工程师（国内/海外）/ IT产品助理 / 微网EMS',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '厦门 / 深圳 / 漳州',
    applyUrl:
      'https://app.mokahr.com/campus-recruitment/kehua/92510#/jobs?page=1&anchorName=jobsList',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80200.html',
    sourceLabel: '官方校招入口 + 2027岗位与福利表',
    startDate: '2026-08-25',
    endDate: '2026-11-25',
    deadlineNote: '高校页面标注11月25日；网申后需完成线上测评',
    recommendation: 4,
    fitReason: '本届不只开放产品经理名称：产品研发序列有产品工程师、微网/EMS与电力通信，职能序列还有IT产品助理，覆盖AI+数字能源和B端产品化工作。',
    riskNote: '产品工程师专业更偏电力电子/自动化；计算机背景优先IT产品助理、微网EMS软件或电力通信，并在投递页逐项核专业。',
    degreeGate: '2027届本科明确开放；校招简章未写985/211限制，普通本科亦列地方补贴',
    verifiedAt: '2026-09-15',
    compensation: '本届招聘页标注10K以上；月薪+年终奖+利润奖，六险一金',
  },
  {
    id: 'sac-power-ai-service-2027',
    company: '国电南自',
    role: '调试服务（储能/新能源）/ AI与系统软件',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '央企',
    scale: '中厂',
    city: '南京',
    applyUrl: 'https://sac2027.zhaopin.com/',
    sourceUrl: 'https://nj.bendibao.com/job/2026825/182644.shtm',
    sourceLabel: '官方投递入口 + 2027校招岗位汇总',
    startDate: '2026-08-25',
    endDate: '2026-10-24',
    deadlineNote: '第三方汇总标注10月24日；需同时完成国电南自与华电集团系统投递',
    recommendation: 4,
    fitReason: '央企电力自动化核心场景，储能/新能源调试、AI和系统软件都能放大你的电力与AI交叉经历。',
    riskNote: '不是产品岗，技术实操要求高；优先本科开放的调试服务，AI/研发岗位必须在官网逐岗确认学历。',
    degreeGate: '2027校招面向本科及以上；调试服务（电气/储能/新能源）具体岗位明确本科可投',
    verifiedAt: '2026-09-02',
    compensation: '未公开；六险二金、餐补、住房政策及安家费',
  },
  {
    id: 'wisdom-power-solution-marketing-2027',
    company: '东方威思顿',
    role: '国内方案营销（数字电力 / 智慧能源）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '国企',
    scale: '中厂',
    city: '烟台 / 全国',
    applyUrl: 'http://bjxapp.cn/t/NjM0NDQyNA/',
    sourceUrl: 'https://www.fenbi.com/page/exam-information-detail/468601157997568',
    sourceLabel: '2027校招公告 + 高校具体岗位页',
    startDate: '2026-08-24',
    endDate: null,
    deadlineNote: '2027校招已开放；未公布统一截止，建议优先投',
    recommendation: 5,
    fitReason: '国企中少见的“数字电力+智慧能源+方案营销”本科岗位，客户覆盖电网、能源与工业企业，和清能B端经历高度同构。',
    riskNote: '岗位带市场拓展属性，并要求接受长期驻外或短期出差；适合愿意走客户方案路线时重点投。',
    degreeGate: '具体营销序列明确本科及以上；未写985/211或研究生硬限制',
    verifiedAt: '2026-09-02',
    compensation: '5–10K/月；五险二金（具体岗位页）',
  },
  {
    id: 'wisdri-automation-technical-marketing-2027',
    company: '中冶南方自动化',
    role: '技术工程师 / 营销管培生（工业自动化）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '央企',
    scale: '中厂',
    city: '武汉 / 项目现场',
    applyUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/79331.html',
    sourceUrl: 'https://www.fenbi.com/page/exam-information-detail/468506749195266',
    sourceLabel: '2027校招公告（含岗位学历表）',
    startDate: '2026-08-20',
    endDate: null,
    deadlineNote: '邮箱滚动接收：autohr@wisdri.com',
    recommendation: 4,
    fitReason: '央企工业数字化与电力电子场景，岗位直接做自动化系统设计调试、技术支持或数智化项目市场，能复用B端需求和交付经验。',
    riskNote: '不是标准产品经理，技术岗有现场调试，营销岗有市场目标；不要投明确要求硕士的产品技术研发工程师。',
    degreeGate: '技术工程师、营销管培生均明确本科及以上；一般岗未写名校限制',
    verifiedAt: '2026-09-02',
    compensation: '一般岗未公开；七险一金、绩效奖金、单身公寓等',
  },
  {
    id: 'hoymiles-product-engineer-2027',
    company: '禾迈股份',
    role: '产品工程师 / 技术支持工程师（光伏储能）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '杭州 / 苏州 / 成都 / 海宁 / 丽水',
    applyUrl: 'https://www.hoymiles.com/',
    sourceUrl: 'https://job.hdu.edu.cn/campus/view?id=9558',
    sourceLabel: '2027校招岗位学历明细',
    startDate: '2026-08-24',
    endDate: '2026-11-23',
    deadlineNote: '高校招聘页标注11月23日到期；从官网“招贤纳士”进入校招投递',
    recommendation: 4,
    fitReason: '光伏逆变器与储能系统的产品技术岗，既贴电力能源又面向客户与产品落地，比泛互联网产品更能利用垂直经历。',
    riskNote: '产品工程师偏技术产品，需要电气/自动化/电力电子基础；若专业不完全匹配，优先技术支持或投标管理。',
    degreeGate: '产品工程师、技术支持工程师均明确本科及以上；未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '本科：研发12–33万/年，非研发12–23万/年',
  },
  {
    id: 'ecoflow-presales-2027',
    company: '正浩创新 EcoFlow',
    role: '售前工程师（储能解决方案）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'https://www.nowcoder.com/jobs/detail/464341',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/464341',
    sourceLabel: '2027校招具体岗位页',
    startDate: '2026-08-31',
    endDate: '2026-11-01',
    deadlineNote: '高校秋招页标注11月1日到期；岗位页当前可投',
    recommendation: 4,
    fitReason: '直接做清洁能源产品演示、客户场景方案、需求反馈与产品迭代，是储能行业里很接近B端产品的本科机会。',
    riskNote: '要求英语可作为工作语言，专业偏电气/电力电子/新能源；若英语或技术基础不足，优先级下调。',
    degreeGate: '具体岗位明确2027届本科及以上；未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '14–17K/月 × 12薪（岗位页）',
  },
  {
    id: 'cetc-digital-project-client-2027',
    company: '中电科数字',
    role: '工程/运维项目经理 / 客户经理（数字新基建）',
    tracks: ['B端软件/平台', '能源数字化/央国企', '智能硬件/IoT'],
    ownership: '央企',
    scale: '中厂',
    city: '上海 / 全国',
    applyUrl: 'https://www.shecc.com/job.html',
    sourceUrl: 'https://www.shecc.com/job.html',
    sourceLabel: '公司官方2027校园招聘页',
    startDate: '2026-09-02',
    endDate: null,
    deadlineNote: '官方明确不设统一截止时间，滚动处理；简历投至campus@shecc.com',
    recommendation: 3,
    fitReason: '央企B端数字化平台，数据中心、物联感知与行业解决方案场景明确，可用项目管理和企业客户经历切入。',
    riskNote: '当前开放的是项目/客户岗位而非产品经理，且非电力垂直；作为央企B端补充，不要排在能源中厂之前。',
    degreeGate: '官方岗位页明确2027届本科及以上；未写985/211或双一流限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开；五险一金、补充公积金、商业保险及补贴',
  },
  {
    id: 'chnenergy-xinjiang-digital-2027',
    company: '国能新疆电力',
    role: '专业技术岗T类（软件 / 大数据 / AI）',
    tracks: ['能源数字化/央国企', 'AI应用产品', 'B端软件/平台'],
    ownership: '央企',
    scale: '大厂',
    city: '新疆',
    applyUrl: 'https://zhaopin.chnenergy.com.cn/',
    sourceUrl: 'https://www.fenbi.com/page/exam-information-detail/468777906491392',
    sourceLabel: '2027秋招岗位学历表 + 集团官网入口',
    startDate: '2026-09-01',
    endDate: null,
    deadlineNote: '国家能源集团系统已开放；具体截止以职位页为准',
    recommendation: 3,
    fitReason: '能源央企里明确向本科开放的软件、大数据与AI技术岗，专业与清洁能源经历可形成垂直证据链。',
    riskNote: '不是产品岗且工作地点在新疆；仅在接受地点和技术路线时投，推荐度低于能源产品/解决方案中厂。',
    degreeGate: '专业技术岗T类明确本科/硕士；本科专业含计算机、软件、大数据、人工智能，未写名校硬限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开；央企标准福利以具体单位为准',
  },
  {
    id: 'sany-digital-energy-2027',
    company: '三一集团',
    role: '产品规划 / AI应用 / 业务分析 / 数字化营销',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大型科技企业',
    city: '长沙 / 北京 / 上海 / 昆山 / 湖州 / 珠海等',
    applyUrl: 'https://sany.zhiye.com/campus/jobs',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117034.html',
    sourceLabel: '官方校招入口 + 高校招聘简章',
    startDate: '2026-08-26',
    endDate: null,
    deadlineNote: '2027秋招已开放；官网未公布统一截止，具体岗位与地点以网申系统为准',
    recommendation: 4,
    fitReason: '三一同时推进数智化、低碳化，业务覆盖风电、新能源和储能；计算机及AI序列又包含AI应用、数据治理和业务分析，能把电力实习与B端产品能力放在同一条叙事里。',
    riskNote: '集团体量大、岗位池宽；优先搜三一重能、储能、数字化平台、产品规划和AI应用，不要把时间分散到泛工程机械岗位。',
    degreeGate: '2027届本科/硕士/博士；本科明确开放，未写985/211或研究生硬门槛',
    verifiedAt: '2026-09-07',
    compensation: '8–20K/月（高校页面区间，岗位差异较大）',
  },
  {
    id: 'star-net-product-2027',
    company: '星网锐捷',
    role: '产品经理 / 营销管培生（ICT与AI应用方案）',
    tracks: ['B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '国企',
    scale: '大厂',
    city: '福州 / 成都 / 一线城市及全国省会',
    applyUrl: 'https://www.star-net.cn/career/',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/79477.html',
    sourceLabel: '官方招聘页 + 2027校招岗位明细',
    startDate: '2026-08-25',
    endDate: '2026-10-31',
    deadlineNote: '招聘简章明确10月31日截止；产品经理与技术岗位分开核对',
    recommendation: 3,
    fitReason: '母公司直接开放产品经理，做ICT基础设施和AI应用方案，属于可复用B端需求分析、软硬件协同和方案表达的国企产品机会。',
    riskNote: 'AI应用架构师明确偏硕士，不要误投；本科优先产品经理，若愿意转技术也可看Java、移动应用、测试等岗位。',
    degreeGate: '产品经理明确2027届本/硕、专业不限；开发测试岗本/硕且接受计算机相关专业，无名校硬限制',
    verifiedAt: '2026-09-07',
    compensation: '产品经理8–12K/月；开发测试10–16K/月',
  },
  {
    id: 'sifang-power-solution-2027',
    company: '四方继保',
    role: '解决方案与产品营销 / 工程服务 / 计划管理',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 保定 / 南京 / 武汉 / 湖州 / 全国',
    applyUrl: 'http://www.sifang.com/campus',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/79787.html',
    sourceLabel: '2027校招岗位学历明细',
    startDate: '2026-08-31',
    endDate: '2026-11-30',
    deadlineNote: '高校页面标注11月30日到期；官网选择2027届校招',
    recommendation: 5,
    fitReason: '电网、电厂、新能源、储能与智慧物联全覆盖，营销及支持岗直接做行业解决方案、产品销售和运营，本科计算机专业可投，是当前最贴合的电力B端机会之一。',
    riskNote: '研发岗多要求硕士；本科应把重点放在营销及支持、工程服务、调试、计划管理，不要把“产品”理解成纯互联网产品经理。',
    degreeGate: '营销及支持、工程服务、调试、计划管理均明确本科及以上；计算机专业在可投范围，未写名校限制',
    verifiedAt: '2026-09-07',
    compensation: '本科技术/工程岗约8–15K/月；八险一金及多项补贴',
  },
  {
    id: 'dongfang-electric-solution-2027',
    company: '东方电子',
    role: '项目实施 / 研发技术储备 / 销售工程师（电力系统）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '国企',
    scale: '中厂',
    city: '烟台 / 北京 / 上海 / 江苏 / 广东等',
    applyUrl: 'https://www.dongfangelec.com/join/xiao-yuan-zhao-pin.jsp',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/57374.html',
    sourceLabel: '公司官方校招岗位页 + 高校具体岗位页',
    startDate: '2026-09-01',
    endDate: null,
    deadlineNote: '当前校招岗位开放，官网未公布统一截止；亦可邮件投至zhaopin@dongfang-china.com',
    recommendation: 5,
    fitReason: '市属国企长期做智能电网、虚拟电厂、储能与智慧能源，实施和售前类岗位既接受计算机本科，又能把你的电力场景与B端交付经历直接用起来。',
    riskNote: 'AI研发岗要求硕士，不纳入推荐；本科优先项目实施、研发技术储备、销售工程师或软件岗，并提前确认该岗位面向2027届。',
    degreeGate: '实施/技术储备/软件与销售岗位明确本科可投，接受计算机、软件、自动化等专业；未写985/211限制',
    verifiedAt: '2026-09-07',
    compensation: '6–10K/月（随实施、销售或开发岗位不同）',
  },
  {
    id: 'luoshu-ai-energy-2027',
    company: '洛枢算力',
    role: 'AI全栈 / 电力交易 / 虚拟电厂运营 / AIDC运营',
    tracks: ['能源数字化/央国企', 'AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '成长公司',
    city: '呼和浩特',
    applyUrl: 'https://www.luoshutech.com/careers/',
    sourceUrl: 'https://www.luoshutech.com/careers/',
    sourceLabel: '公司官方2027校园招聘页',
    startDate: null,
    endDate: null,
    deadlineNote: '2027校招当前开放；简历与作品发送至hr@luoshutech.com，招满即止',
    recommendation: 5,
    fitReason: '这是少见的“AI+能源+算力”直交叉机会：真实场景包含电力市场、虚拟电厂、储能、绿电和数字孪生，计算机本科也能通过AI作品切入。',
    riskNote: '团队较新、规模和培养稳定性需要面试反向核验；岗位在呼和浩特，且面试强调现场展示AI协作与可运行作品。',
    degreeGate: '2027届本科及以上；计算机/软件/数学或电气/能源相关专业优先，无名校和研究生硬限制',
    verifiedAt: '2026-09-07',
    compensation: '6–20K/月；五险一金、带薪年假、培训体系',
  },
  {
    id: 'fiberhome-solution-product-2027',
    company: '烽火通信',
    role: '售前经理 / 产品经理 / 技术支持',
    tracks: ['B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '央企',
    scale: '中厂',
    city: '武汉 / 国内及海外',
    applyUrl: 'https://app.mokahr.com/campus-recruitment/whfhtx/73922',
    sourceUrl: 'https://myjob.dlmu.edu.cn/campus/view/id/868302',
    sourceLabel: '官方校招系统 + 高校2027招聘简章',
    startDate: null,
    endDate: '2026-10-13',
    deadlineNote: '高校页面标注10月13日到期；官方校招系统当前可投',
    recommendation: 3,
    fitReason: '央企子公司中少见地把售前经理、产品经理列入解决方案序列，并接受计算机/软件/自动化专业，B端行业方案经验可以复用。',
    riskNote: '不属于电力垂直，且央企ICT竞争仍会偏强；排在能源中厂之后，只投产品/售前/交付等明确本科岗位。',
    degreeGate: '2027届本硕博；解决方案与技术支持序列接受计算机相关专业，整体明确本科开放，未写名校硬限制',
    verifiedAt: '2026-09-07',
    compensation: '约10.5–15K/月（高校页面综合区间）',
  },
  {
    id: 'inspur-datacenter-product-2027',
    company: '浪潮集团',
    role: '数据中心产品经理 / 售前 / 实施工程师',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '国企',
    scale: '大厂',
    city: '济南 / 北京 / 青岛 / 苏州 / 重庆 / 天津',
    applyUrl: 'http://career.inspur.com/campus2027/index.html',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117451.html',
    sourceLabel: '官方2027网申入口 + 高校招聘简章',
    startDate: '2026-09-01',
    endDate: null,
    deadlineNote: '2027校招已开放；官网未公布统一截止，岗位滚动处理',
    recommendation: 3,
    fitReason: '省属国企的B端算力、云和数据中心业务，数据中心产品、售前和实施方向能复用平台产品与企业客户协作经验。',
    riskNote: '属于大平台且非电力垂直，竞争和简历筛选仍会强；只在官网确认具体岗位本科可投后提交，优先数据中心产品/售前而非算法岗。',
    degreeGate: '2027届本硕博统一开放；计算机相关岗位较多，公告未写985/211门槛，具体产品岗位需再核学历',
    verifiedAt: '2026-09-07',
    compensation: '未公开；含租房、午餐等补贴，济南本科人才补贴另按政策申请',
  },
  {
    id: 'cmcc-qinghai-solution-2027',
    company: '中国移动青海',
    role: '交付及解决方案经理 / 产品管理 / 经营分析',
    tracks: ['B端软件/平台', '能源数字化/央国企', 'AI应用产品'],
    ownership: '央企',
    scale: '中厂',
    city: '西宁 / 海东 / 海西 / 格尔木等',
    applyUrl: 'https://job.10086.cn/personal/campus/campus_job_list.html?cId=59',
    sourceUrl: 'https://career.sustech.edu.cn/detail/online?id=3595540',
    sourceLabel: '集团官方岗位入口 + 省公司招聘公告',
    startDate: '2026-09-04',
    endDate: null,
    deadlineNote: '报名为9月至10月中上旬；10月24日统一线上笔试',
    recommendation: 3,
    fitReason: '省公司规模约1000–5000人，本科计算机可直接投解决方案、产品管理和经营分析；同时参与青海绿色算力布局，比集团总部泛岗位更现实。',
    riskNote: '地点选择和全省调剂是主要成本，部分地区高原条件艰苦；只在能接受青海长期发展时投递。',
    degreeGate: '2026/2027届统招本科及以上，计算机、物联网、电子信息等专业可投；无985/211硬门槛',
    verifiedAt: '2026-09-07',
    compensation: '5–8K/月；六险两金、高海拔补贴等',
  },
  {
    id: 'hei-digital-energy-2027',
    company: '哈电国际',
    role: '信息化 / 大数据 / 电力工程数字化',
    tracks: ['能源数字化/央国企', 'B端软件/平台'],
    ownership: '央企',
    scale: '中厂',
    city: '哈尔滨 / 海外项目',
    applyUrl: 'mailto:zhaopin@china-hei.com',
    sourceUrl: 'https://www.fenbi.com/page/exam-information-detail/468638644328449',
    sourceLabel: '2027秋招公告（含学历专业表）',
    startDate: '2026-08-26',
    endDate: null,
    deadlineNote: '邮箱滚动接收；主题为“姓名+学校+专业+学历”',
    recommendation: 4,
    fitReason: '央企能源工程总包与数字化设备场景，明确招收计算机、信息工程和大数据本科，垂直匹配度高于多数泛央企IT岗。',
    riskNote: '公告按专业大类而非具体岗位展示，且国际工程可能有长期出差或驻外；投前邮件确认具体部门、职责与出差比例。',
    degreeGate: '2027届；信息工程/计算机/电子信息/通信/大数据明确本科或硕士可投，未写名校限制',
    verifiedAt: '2026-09-07',
    compensation: '未公开；七险两金、出差补助、宿舍及多项补贴',
  },
  {
    id: 'huadian-zhejiang-digital-2027',
    company: '华电浙江',
    role: '计算机类技术岗（火电 / 水电 / 新能源）',
    tracks: ['能源数字化/央国企', 'B端软件/平台'],
    ownership: '央企',
    scale: '中厂',
    city: '杭州 / 温州 / 衢州 / 湖州 / 台州 / 舟山',
    applyUrl: 'https://v.wjx.cn/vm/eVhjldS.aspx#',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117622.html',
    sourceLabel: '2027校招公告与报名入口',
    startDate: '2026-09-03',
    endDate: null,
    deadlineNote: '报名入口已开放；公告未公布统一截止，建议尽早提交',
    recommendation: 4,
    fitReason: '直接进入火电、水电、海上风电或新能源区域公司，计算机类本科在招聘专业范围；电力行业经历可作为垂直加分，而不是与名校候选人拼泛IT。',
    riskNote: '公告只公布专业大类，未列出计算机岗的具体职责；报名后必须确认是信息化、数据或生产技术方向，避免被分到完全不相关岗位。',
    degreeGate: '2027届本科及以上，计算机类和电子信息类明确在招；未写985/211或研究生硬限制',
    verifiedAt: '2026-09-07',
    compensation: '10–15K/月（高校页面）；六险一金、企业年金、职工公寓，杭州另有人才补贴',
  },
  {
    id: 'neusoft-consulting-2027',
    company: '东软集团',
    role: '咨询顾问 / 实施与技术支持 / 软件开发',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '沈阳 / 大连 / 北京 / 上海 / 武汉 / 全国多地',
    applyUrl: 'https://neusoft-campus.zhiye.com/',
    sourceUrl: 'https://jdjyw.jlu.edu.cn/portal/recruit/details?id=5140aa6678554a09952f75fb06c50fdb',
    sourceLabel: '官方2027网申入口 + 高校招聘简章',
    startDate: '2026-09-01',
    endDate: '2026-11-30',
    deadlineNote: '测评与面试持续到11月30日；Offer沟通至12月31日',
    recommendation: 3,
    fitReason: '中型企业软件与解决方案公司，咨询顾问、实施和技术支持明确向本科开放，适合用B端需求、项目推进与交付经验切入。',
    riskNote: '非能源垂直，产品经理并未单列；优先咨询/实施/技术支持，不要为了“进大公司”去投要求硕士的AI与技术管培生。',
    degreeGate: '2027届；开发测试和咨询/实施/技术支持明确本科及以上，未写985/211限制',
    verifiedAt: '2026-09-07',
    compensation: '未公开；以具体城市与岗位Offer为准',
  },
];
