export type SeedOpportunity = {
  id: string;
  company: string;
  role: string;
  tracks: string[];
  ownership: string;
  scale: string;
  city: string;
  applyUrl: string;
  sourceUrl: string;
  sourceLabel: string;
  startDate: string | null;
  endDate: string | null;
  deadlineNote: string;
  recommendation: number;
  fitReason: string;
  riskNote: string;
  degreeGate: string;
  verifiedAt: string;
  compensation?: string;
};

export const retiredSeedIds = [
  'wondershare-ai-pm-2027',
  'ct-digital-life-pm-2027',
  'cecloud-pm-2027',
  'amazon-program-2027',
  'oppo-display-pm-2027',
  'hello-momo-product-2027',
];

export const seedOpportunities: SeedOpportunity[] = [
  {
    id: 'dji-digital-2027',
    company: '大疆创新',
    role: '数字管理构建者计划',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 上海 / 北京',
    applyUrl: 'https://careers.dji.com/zh-CN/campus/digital-recruitment',
    sourceUrl: 'https://careers.dji.com/zh-CN/campus/digital-recruitment',
    sourceLabel: '官方项目页',
    startDate: '2026-08-07',
    endDate: null,
    deadlineNote: '招满即止；不占常规校招投递次数',
    recommendation: 3,
    fitReason: '规则拆解、复杂B端系统、AI与业务协同都高度贴合清能和达观经历。',
    riskNote: '强调理工背景与把业务逻辑转成可运行规则，需准备可量化案例。',
    degreeGate: '2027届及优秀2026届，理工背景优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'oppo-ai-pm-2027',
    company: 'OPPO',
    role: '互联网产品经理（AI方向）',
    tracks: ['AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 成都',
    applyUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1825?recruitType=Graduate',
    sourceUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1825?recruitType=Graduate',
    sourceLabel: '官方岗位页',
    startDate: '2026-07-15',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 2,
    fitReason: 'AI PRD、Agent、评测和AI Coding要求，能承接达观与个人AI MVP。',
    riskNote: '明确要求能读懂代码并展示AI Coding案例，需补强可运行Demo。',
    degreeGate: '本科及以上；计算机/AI相关专业优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'oppo-internet-pm-2027',
    company: 'OPPO',
    role: '互联网产品经理',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 成都',
    applyUrl: 'https://careers.oppo.com/university/oppo/campus/post/1860',
    sourceUrl: 'https://careers.oppo.com/university/oppo/campus/post/1860',
    sourceLabel: '官方岗位页',
    startDate: '2026-07-15',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 1,
    fitReason:
      '互联网、数据产品与手机软件场景，匹配平台产品和设备—软件协同能力。',
    riskNote: 'C端产品Sense与数据分析要求较强，面试需准备手机/IoT产品拆解。',
    degreeGate: '本科及以上；理工专业优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'baidu-ai-pm-2027',
    company: '百度',
    role: 'AI产品经理（J100665）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '北京',
    applyUrl: 'https://talent.baidu.com/jobs/list?projectType=1',
    sourceUrl: 'https://talent.baidu.com/jobs/list?projectType=1',
    sourceLabel: '官方岗位列表',
    startDate: '2026-07-21',
    endDate: null,
    deadlineNote: '官网未公布，岗位滚动处理',
    recommendation: 2,
    fitReason:
      '大模型产品规划、跨算法研发协作和数据反馈闭环与现有AI经历高度一致。',
    riskNote: '竞争强，需要能讲清RAG质量、Agent边界和核心指标。',
    degreeGate: '2027届；学历要求以岗位页为准',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'alibaba-cloud-product-2027',
    company: '阿里云',
    role: '产品类（2027届应届生）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '杭州 / 北京 / 上海 / 深圳 / 成都 / 广州 / 南京',
    applyUrl:
      'https://campus-talent.alibaba.com/campus/position?batchId=100000760001',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116681.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-11',
    endDate: null,
    deadlineNote: '官网未公布；最多2个意向',
    recommendation: 2,
    fitReason: '云与AI+B端平台是达观、清能两段经历最自然的交集。',
    riskNote: '大厂竞争强，投递后意向不可修改，需先核具体团队JD。',
    degreeGate: '2026.11—2027.10毕业；逐岗核对学历',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'alibaba-group-product-2027',
    company: '阿里巴巴集团',
    role: '产品类（16个业务团队）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '杭州 / 北京 / 上海 / 深圳等',
    applyUrl: 'https://campus-talent.alibaba.com/campus/gov',
    sourceUrl: 'https://campus-talent.alibaba.com/campus/gov',
    sourceLabel: '官方校招页',
    startDate: null,
    endDate: null,
    deadlineNote: '已开放；具体批次时间未公布',
    recommendation: 1,
    fitReason: '产品职类覆盖AI、云与多业务平台，可按具体JD选择B端或AI版简历。',
    riskNote: '业务跨度大，必须逐岗定向；毕业时间口径为2026.11—2027.10。',
    degreeGate: '海内外应届毕业生，逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'xiaomi-product-2027',
    company: '小米集团',
    role: '2027全球校招—产品方向',
    tracks: ['智能硬件/IoT', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京 / 武汉 / 南京 / 深圳等',
    applyUrl: 'https://hr.xiaomi.com/website/campus.html',
    sourceUrl: 'https://hr.xiaomi.com/website/campus.html',
    sourceLabel: '官方校招页',
    startDate: null,
    endDate: null,
    deadlineNote: '已开放；官网未公布统一截止',
    recommendation: 1,
    fitReason: '软硬件、AI与产品方向同时开放，IoT专业和GreenAuto可形成差异化。',
    riskNote:
      '硬件版缺真实量产经历，优先选设备软件/App/IoT平台而非品类负责人。',
    degreeGate: '2026.09.01—2027.08.31毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'pdd-campus-2027',
    company: '拼多多',
    role: '2027校园招聘—产品/运营方向（官网筛选）',
    tracks: ['B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '上海 / 广州等',
    applyUrl: 'https://careers.pddglobalhr.com/campus/',
    sourceUrl: 'https://careers.pddglobalhr.com/campus/',
    sourceLabel: '官方校招页',
    startDate: null,
    endDate: null,
    deadlineNote: '已开放；具体岗位滚动更新',
    recommendation: 1,
    fitReason: '平台与商业产品可使用B端版简历，但现有经历偏产业和知识产品。',
    riskNote: '业务强度与C端/商业化偏好较高，先确认具体产品岗再投。',
    degreeGate: '2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'dji-campus-2027',
    company: '大疆创新',
    role: '拓疆者校招—产品/数字化方向（官网筛选）',
    tracks: ['智能硬件/IoT', 'B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 上海 / 北京',
    applyUrl: 'https://careers.dji.com/zh-CN/campus/recruitment?from=sec_nav',
    sourceUrl: 'https://careers.dji.com/zh-CN/campus/recruitment?from=sec_nav',
    sourceLabel: '官方项目页',
    startDate: '2026-06-25',
    endDate: null,
    deadlineNote: '不设截止，招满即止；限投1个职位',
    recommendation: 1,
    fitReason: '智能硬件、端云协同和数字化场景契合IoT背景。',
    riskNote: '常规校招仅一次投递且不能改，先对比数字管理计划再决定。',
    degreeGate: '2027届高校毕业生',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'anker-campus-2027',
    company: '安克创新',
    role: '2027全球校招—智能硬件产品方向',
    tracks: ['智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 长沙 / 杭州 / 北京等',
    applyUrl: 'https://career.anker.com.cn/universities/recruitment/',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116865.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-21',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 1,
    fitReason: '消费智能硬件赛道与GreenAuto、IoT专业匹配。',
    riskNote: '更看重品类、供应链和量产意识，需突出选型、状态机和测试取舍。',
    degreeGate: '2027届；逐岗核对学历',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'lenovo-product-2027',
    company: '联想集团',
    role: '产品与项目方向',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '混合所有制',
    scale: '大厂',
    city: '北京 / 上海 / 深圳 / 天津 / 武汉等',
    applyUrl: 'https://talent.lenovo.com.cn/home',
    sourceUrl: 'https://job.wzu.edu.cn/campus/view/id/494874',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-05',
    endDate: '2026-11-13',
    deadlineNote: '简章称11月13日结束；建议10月前完成',
    recommendation: 1,
    fitReason: '智能设备、企业服务与项目协同都能承接B端和IoT版简历。',
    riskNote: '岗位差异大，优先找软件产品、设备平台或AI PC相关。',
    degreeGate: '本科及以上；2026.09.01—2027.08.31毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'xiaopeng-ai-product-2027',
    company: '小鹏集团',
    role: 'AI产品经理 / 产品方向',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '广州 / 深圳 / 上海 / 北京 / 武汉',
    applyUrl: 'https://xiaopeng.jobs.feishu.cn/campus',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116251.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-07-07',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 2,
    fitReason: 'AI、Agent、RAG与智能设备理解可同时发挥，物联网专业也加分。',
    riskNote: '汽车/物理AI竞争强，需用可运行AI应用和软硬件链路证明技术理解。',
    degreeGate: '本科及以上；2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'li-auto-product-2027',
    company: '理想汽车',
    role: '产品 / 整车与智能硬件方向',
    tracks: ['智能硬件/IoT', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京 / 上海 / 深圳 / 杭州 / 常州',
    applyUrl: 'https://www.lixiang.com/employ/campus/list.html?fromJob=1',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116875.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-21',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 2,
    fitReason: '产品、智能硬件、软件与具身智能多方向开放。',
    riskNote:
      '缺汽车行业项目，优先选座舱/设备软件/数字化产品，避免整车量产强门槛岗。',
    degreeGate: '本科及以上；2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'wondershare-ai-pm-2027',
    company: '万兴科技',
    role: 'AI产品经理',
    tracks: ['AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '长沙 / 深圳 / 杭州 / 北京 / 东京',
    applyUrl: 'https://bsurl.cn/v2/DBo3MpGj',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116994.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布；含秋招直招与实习转正',
    recommendation: 5,
    fitReason: 'AI Native软件产品、MVP与用户洞察非常贴合AI版简历。',
    riskNote: '部分岗位有产品体验报告，需提前拆解万兴喵影/PDF等产品。',
    degreeGate: '本科及以上；2026.09—2027.12毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'kedacom-pm-2027',
    company: '科达科技',
    role: '产品经理（2027校园招聘）',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '苏州',
    applyUrl: 'https://www.kedacom.com/cn/xyjob_2.jhtml',
    sourceUrl: 'https://www.kedacom.com/cn/xyjob_2.jhtml',
    sourceLabel: '官方岗位列表',
    startDate: '2026-07-22',
    endDate: null,
    deadlineNote: '官网未公布，滚动处理',
    recommendation: 4,
    fitReason: '视讯安防、软件平台与硬件协同，比纯消费硬件更适配现有经历。',
    riskNote: '需补充对视频会议/安防行业和软硬件系统边界的理解。',
    degreeGate: '2027校园招聘；逐岗核对学历',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'spirit-ai-product-2027',
    company: '千寻智能',
    role: '具身智能产品经理 / 机器人产品经理',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '成长公司',
    city: '北京 / 杭州 / 深圳',
    applyUrl: 'https://nwd4iy9rd2s.jobs.feishu.cn/campusofSpiritAI',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116725.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-10',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 2,
    fitReason: 'AI与硬件交叉方向高度相关，GreenAuto可作基础证据。',
    riskNote: '团队门槛很高，偏好顶会/专利或顶级工程项目；作为冲刺项。',
    degreeGate: '本科/硕士/博士；2026.09—2027.12毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'chinatelecom-campus-2027',
    company: '中国电信',
    role: '产品 / 企业信息化 / 产数类',
    tracks: ['B端软件/平台', '能源数字化/央国企'],
    ownership: '央企',
    scale: '大厂',
    city: '全国',
    applyUrl: 'https://job.chinatelecom.com.cn/wt/TELE/web/index?_refluxos=a10',
    sourceUrl: 'https://www.chinatelecom.com.cn/index.html',
    sourceLabel: '集团官网 + 官方网申',
    startDate: '2026-08-21',
    endDate: null,
    deadlineNote: '各分子公司自行确定截止',
    recommendation: 2,
    fitReason: '物联网专业、企业信息化、B端需求和央国企偏好同时匹配。',
    riskNote: '岗位分散，建议优先专业子公司、研究院和广州/成都等城市产品岗。',
    degreeGate: '本科及以上；2027届，部分单位接受未就业2026届',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'ct-digital-life-pm-2027',
    company: '天翼数字生活',
    role: '产品经理 / 产品运营',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '央企',
    scale: '中厂',
    city: '上海 / 南京 / 广州',
    applyUrl: 'https://job.chinatelecom.com.cn/wt/TELE/web/index?_refluxos=a10',
    sourceUrl:
      'https://m.fenbi.com/page/exam-information-detail/468756891196416',
    sourceLabel: '官方网申 + 招聘公告汇总',
    startDate: '2026-08-31',
    endDate: '2026-09-07',
    deadlineNote: '公告口径：9月7日截止',
    recommendation: 1,
    fitReason: '数字家庭、智慧社区和产品运营方向本身契合。',
    riskNote:
      '当前公告标注硕士/博士，与你本科学历不符；仅保留作提醒，不建议投入时间。',
    degreeGate: '硕士/博士（明确硬门槛）',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'cecloud-pm-2027',
    company: '中国电子云',
    role: '产品经理',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '央企',
    scale: '中厂',
    city: '北京 / 武汉 / 南京 / 杭州 / 成都',
    applyUrl: 'https://www.cecloud.com',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407567.htm',
    sourceLabel: '公司入口 + 高校招聘简章',
    startDate: '2026-08-27',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 3,
    fitReason: '政企云、AI平台与本体构建贴合企业知识产品和B端经历。',
    riskNote:
      '公告正文称本科可投，但高校需求表写硕士，必须先在官网核具体产品岗。',
    degreeGate: '口径冲突：招聘范围含本科，需求表写硕士',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'envision-product-2027',
    company: '远景能源',
    role: '产品 / 市场与解决方案',
    tracks: ['能源数字化/央国企', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '上海 / 江阴 / 全国及海外',
    applyUrl: 'https://envision-career.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116772.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-20',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 5,
    fitReason:
      '能源、AIoT、电力系统与产品能力四项重合，是最值得定向准备的机会之一。',
    riskNote: '逐岗区分产品、解决方案和工程岗；避免误投强电气/算法硬门槛职位。',
    degreeGate: '本科/硕士/博士；2027年毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'sungrow-campus-2027',
    company: '阳光电源',
    role: '2027全球校招—产品/解决方案方向（官网筛选）',
    tracks: ['能源数字化/央国企', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '合肥 / 上海 / 南京等',
    applyUrl: 'https://jobs.sungrowpower.com/',
    sourceUrl: 'https://jobs.sungrowpower.com/',
    sourceLabel: '官方招聘页',
    startDate: '2026-08-10',
    endDate: null,
    deadlineNote: '正式批已启动；官网未公布统一截止',
    recommendation: 5,
    fitReason: '新能源硬件、智慧能源和行业数字化与清能经历互补。',
    riskNote: '先筛产品/解决方案/数字化岗位，纯电气研发岗不匹配。',
    degreeGate: '2027届；逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'catl-campus-2027',
    company: '宁德时代',
    role: '计算机与AI / 市场 / 运营方向（官网筛选）',
    tracks: ['能源数字化/央国企', 'B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '宁德 / 上海 / 北京 / 杭州 / 武汉等',
    applyUrl: 'https://talent.catl.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116814.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布；3次志愿机会',
    recommendation: 3,
    fitReason:
      '新能源产业和计算机/AI方向开放，可寻找数字化产品、业务系统或项目岗。',
    riskNote: '公开简章未列明确产品经理，需以岗位列表为准，不要为凑方向盲投。',
    degreeGate: '本科及以上；2026.07—2027.12毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'amazon-program-2027',
    company: '亚马逊中国',
    role: 'Program Manager / Tech Business Developer',
    tracks: ['B端软件/平台'],
    ownership: '外企',
    scale: '大厂',
    city: '北京 / 上海 / 深圳',
    applyUrl:
      'https://www.amazon.jobs/content/zh/career-programs/university?country%5B%5D=CN',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116983.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布；最多申请3个职位',
    recommendation: 3,
    fitReason: '项目管理、技术业务与云服务方向可承接B端系统和跨团队协作。',
    riskNote:
      '不是标准产品经理，英语和学历要求需逐岗位核对；优先看深圳Program Manager。',
    degreeGate: '部分岗位可能偏硕士；逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'oppo-display-pm-2027',
    company: 'OPPO',
    role: '多媒体屏显产品经理',
    tracks: ['智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳',
    applyUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1829?recruitType=Graduate',
    sourceUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1829?recruitType=Graduate',
    sourceLabel: '官方岗位页',
    startDate: '2026-07-15',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 1,
    fitReason: '产品规划与硬件模块协同方向相关。',
    riskNote: '岗位明确要求硕士及以上，与本科学历不符；不建议投。',
    degreeGate: '硕士及以上（明确硬门槛）',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'duxiaoman-ai-pm-2027',
    company: '度小满',
    role: 'AI应用产品经理 / 信贷产品经理',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 上海',
    applyUrl: 'https://campus.duxiaoman.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116782.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-18',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 3,
    fitReason:
      '明确开放AI应用产品经理，金融AI、复杂规则和业务闭环与达观、清能经历都能衔接。',
    riskNote:
      '金融产品强调风险与指标意识，需准备模型能力如何转化为业务收益和合规边界。',
    degreeGate: '本科及以上；2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'insta360-ai-pm-2027',
    company: '影石 Insta360',
    role: 'AI软件产品经理（2027校招）',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'https://www.insta360.com/cn/jobs',
    sourceUrl: 'https://www.shushuqiuzhi.com/position/423563',
    sourceLabel: '官网入口 + 当前岗位页',
    startDate: '2026-06-30',
    endDate: '2026-10-31',
    deadlineNote: '招聘汇总口径10月31日截止，岗位可能提前招满',
    recommendation: 2,
    fitReason:
      'AI工具、App、多端设备体验同时匹配AI MVP、IoT专业和GreenAuto，属于非常好的交叉型中厂机会。',
    riskNote:
      '需要产品作品集与交互敏感度，建议准备AI工作流Demo和影像产品体验拆解。',
    degreeGate: '本科及以上；专业不限，软件/交互/计算机背景优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'emdoor-product-2027',
    company: '亿道数码',
    role: '产品经理（智能终端）',
    tracks: ['智能硬件/IoT', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'mailto:CR@emdoor.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116842.html',
    sourceLabel: '高校官方就业网岗位页',
    startDate: '2026-08-20',
    endDate: null,
    deadlineNote: '邮箱投递；未公布截止时间',
    recommendation: 2,
    fitReason:
      '岗位覆盖需求、规格、量产交付和全生命周期，IoT背景与硬件产品版简历高度对口。',
    riskNote:
      '要求CET-6并重视量产与营销意识，需补充选型、测试、供应链协同案例。',
    degreeGate: '本科及以上；电子/通信/计算机/软件相关，CET-6',
    verifiedAt: '2026-09-01',
    compensation: '15–20K/月（招聘页公开区间）',
  },
  {
    id: 'yangteng-product-2027',
    company: '扬腾创新',
    role: '供应链数智化产品经理',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '福州',
    applyUrl: 'https://yangtenginnovation-compus.zhiye.com',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407468.htm',
    sourceLabel: '网申入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '已正式启动；官网未公布截止',
    recommendation: 4,
    fitReason:
      '明确负责供应链数智化产品、需求与交付，和B端业务系统、数据产品经验直接匹配。',
    riskNote: '跨境汽配场景较陌生，面试前要补供应链、库存和履约指标框架。',
    degreeGate: '本科及以上；计算机/软件工程相关，CET-4',
    verifiedAt: '2026-09-01',
    compensation: '13–20K/月（招聘简章公开区间）',
  },
  {
    id: 'hello-momo-product-2027',
    company: '挚文集团',
    role: '社交 / 商业 / 海外产品经理',
    tracks: ['AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '北京',
    applyUrl: 'https://campus.immomo.com',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407229.htm',
    sourceLabel: '高校招聘简章',
    startDate: '2026-08-10',
    endDate: null,
    deadlineNote: '8月10日网申启动；未公布截止',
    recommendation: 3,
    fitReason:
      '产品岗位明确开放，AI与亿级用户产品能提供产品Sense训练和冲刺机会。',
    riskNote:
      '偏C端社交与商业化，与你当前B端/行业产品证据不完全同构，需要独立准备C端案例。',
    degreeGate: '本科及以上；2026.12—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'metax-product-2027',
    company: '沐曦股份',
    role: '产品管理 / 项目管理（GPU平台）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 北京 / 南京 / 成都',
    applyUrl: 'https://www.metax-tech.com/join.html',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407387.htm',
    sourceLabel: '官方招聘页 + 高校招聘简章',
    startDate: '2026-07-31',
    endDate: null,
    deadlineNote: '7月底起网申，滚动发放Offer',
    recommendation: 3,
    fitReason:
      '国产GPU与AI基础设施是高质量B端产品场景，能发挥技术理解和平台产品能力。',
    riskNote: '产品管理岗位可能偏技术且逐岗学历不同，务必先确认是否接受本科。',
    degreeGate: '招聘范围含本科；具体产品岗需逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'ke-product-2027',
    company: '贝壳找房',
    role: '产品经理 / 策略产品 / 数据产品',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京 / 上海 / 杭州 / 广州等',
    applyUrl: 'https://campus.ke.com/campus/jobs',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117001.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-26',
    endDate: '2026-10-31',
    deadlineNote: '高校就业网标注10月31日；每类招聘项目限投1岗',
    recommendation: 2,
    fitReason:
      '产业互联网、策略与数据产品方向可直接使用B端版简历，业务复杂度也适合需求拆解优势。',
    riskNote:
      '产品细分多且只限投一个岗位，先对比策略、数据和业务产品JD再提交。',
    degreeGate: '本科及以上；2026.09.01—2027.08.31毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'fanruan-product-2027',
    company: '帆软软件',
    role: '产品经理（一体化平台）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '无锡 / 南京 / 杭州',
    applyUrl: 'https://join.fanruan.com/campus/detail?id=9869',
    sourceUrl: 'https://join.fanruan.com/campus/detail?id=9869',
    sourceLabel: '官方岗位页',
    startDate: '2026-08-01',
    endDate: null,
    deadlineNote: '提前批8月31日结束，官方岗位页仍开放，建议立即确认',
    recommendation: 5,
    fitReason:
      '明确偏好ToB软件产品实习，企业BI、流程设计、需求到交付与你的经历直接同构，且不设名校/研究生硬门槛。',
    riskNote: '需要把清能与达观经历讲成客户价值、模块指标和0→1/1→N迭代闭环。',
    degreeGate: '2027届本科及以上，理工科背景；未写985/211限制',
    verifiedAt: '2026-09-01',
    compensation: '16–20.5K/月，SP另议；不含年终奖',
  },
  {
    id: 'hand-ai-consultant-2027',
    company: '汉得信息',
    role: '数智化咨询顾问（AI方向）',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '私企',
    scale: '中厂',
    city: '天津 / 河北 / 武汉 / 成都 / 西安',
    applyUrl: 'https://career.hebut.edu.cn/correcruit/content/id/73275.html',
    sourceUrl: 'https://job.hdu.edu.cn/campus/view?id=9568',
    sourceLabel: '高校招聘简章 + 岗位页',
    startDate: '2026-08-28',
    endDate: null,
    deadlineNote: '已开放，未公布统一截止',
    recommendation: 5,
    fitReason:
      '岗位明确偏好“能源+AI”复合经验，工作本质是B端需求、方案、数据/AI落地，与你的电力交易和AI经历高度重合。',
    riskNote:
      '岗位是咨询顾问而非标准产品经理，出差较多；优势是成功率和垂直复用度更高。',
    degreeGate: '本科及以上；未写985/211限制',
    verifiedAt: '2026-09-01',
    compensation: '转正8–10K/月；实习3–4.5K/月',
  },
  {
    id: 'transwarp-ai-delivery-2027',
    company: '星环科技',
    role: 'AI交付 / 售前（认知数据库与知识图谱）',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 北京 / 南京 / 广州 / 成都',
    applyUrl: 'https://app.mokahr.com/campus_apply/transwarp',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116990.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-18',
    endDate: '2026-12-31',
    deadlineNote: '8月18日—12月31日',
    recommendation: 4,
    fitReason:
      '企业级AI、GPU原生认知数据库、知识图谱及能源行业客户都能复用达观本体构建与B端交付证据。',
    riskNote:
      '当前校招未列产品经理，建议把AI交付/售前作为高匹配曲线救国岗位，不投纯研发。',
    degreeGate: '2027届本科及以上；计算机/通信/电子/网络',
    verifiedAt: '2026-09-01',
    compensation: '薪资未公开；全额五险一金、补充公积金/商保、搬家费与签字费',
  },
];
