export type SeedOpportunity = {
  id: string;
  company: string;
  role: string;
  tracks: string[];
  ownership: string;
  scale: string;
  city: string;
  applyUrl: string;
  sourceUrl: string;
  sourceLabel: string;
  startDate: string | null;
  endDate: string | null;
  deadlineNote: string;
  recommendation: number;
  fitReason: string;
  riskNote: string;
  degreeGate: string;
  verifiedAt: string;
  compensation?: string;
};

export const retiredSeedIds = [
  'wondershare-ai-pm-2027',
  'ct-digital-life-pm-2027',
  'cecloud-pm-2027',
  'amazon-program-2027',
  'oppo-display-pm-2027',
  'hello-momo-product-2027',
  'sungrow-campus-2027',
];

export const seedOpportunities: SeedOpportunity[] = [
  {
    id: 'dji-digital-2027',
    company: '大疆创新',
    role: '数字管理构建者计划',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 上海 / 北京',
    applyUrl: 'https://careers.dji.com/zh-CN/campus/digital-recruitment',
    sourceUrl: 'https://careers.dji.com/zh-CN/campus/digital-recruitment',
    sourceLabel: '官方项目页',
    startDate: '2026-08-07',
    endDate: null,
    deadlineNote: '招满即止；不占常规校招投递次数',
    recommendation: 2,
    fitReason: '规则拆解、复杂B端系统、AI与业务协同都高度贴合清能和达观经历。',
    riskNote: '强调理工背景与把业务逻辑转成可运行规则，需准备可量化案例。',
    degreeGate: '2027届及优秀2026届，理工背景优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'oppo-ai-pm-2027',
    company: 'OPPO',
    role: '互联网产品经理（AI方向）',
    tracks: ['AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 成都',
    applyUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1825?recruitType=Graduate',
    sourceUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1825?recruitType=Graduate',
    sourceLabel: '官方岗位页',
    startDate: '2026-07-15',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 1,
    fitReason: 'AI PRD、Agent、评测和AI Coding要求，能承接达观与个人AI MVP。',
    riskNote: '明确要求能读懂代码并展示AI Coding案例，需补强可运行Demo。',
    degreeGate: '本科及以上；计算机/AI相关专业优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'oppo-internet-pm-2027',
    company: 'OPPO',
    role: '互联网产品经理',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 成都',
    applyUrl: 'https://careers.oppo.com/university/oppo/campus/post/1860',
    sourceUrl: 'https://careers.oppo.com/university/oppo/campus/post/1860',
    sourceLabel: '官方岗位页',
    startDate: '2026-07-15',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 1,
    fitReason:
      '互联网、数据产品与手机软件场景，匹配平台产品和设备—软件协同能力。',
    riskNote: 'C端产品Sense与数据分析要求较强，面试需准备手机/IoT产品拆解。',
    degreeGate: '本科及以上；理工专业优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'baidu-ai-pm-2027',
    company: '百度',
    role: 'AI产品经理（J100665）',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '北京',
    applyUrl: 'https://talent.baidu.com/jobs/list?projectType=1',
    sourceUrl: 'https://talent.baidu.com/jobs/list?projectType=1',
    sourceLabel: '官方岗位列表',
    startDate: '2026-07-21',
    endDate: null,
    deadlineNote: '官网未公布，岗位滚动处理',
    recommendation: 1,
    fitReason:
      '大模型产品规划、跨算法研发协作和数据反馈闭环与现有AI经历高度一致。',
    riskNote: '竞争强，需要能讲清RAG质量、Agent边界和核心指标。',
    degreeGate: '2027届；学历要求以岗位页为准',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'alibaba-cloud-product-2027',
    company: '阿里云',
    role: '产品类（2027届应届生）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '杭州 / 北京 / 上海 / 深圳 / 成都 / 广州 / 南京',
    applyUrl:
      'https://campus-talent.alibaba.com/campus/position?batchId=100000760001',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116681.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-11',
    endDate: null,
    deadlineNote: '官网未公布；最多2个意向',
    recommendation: 1,
    fitReason: '云与AI+B端平台是达观、清能两段经历最自然的交集。',
    riskNote: '大厂竞争强，投递后意向不可修改，需先核具体团队JD。',
    degreeGate: '2026.11—2027.10毕业；逐岗核对学历',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'alibaba-group-product-2027',
    company: '阿里巴巴集团',
    role: '产品类（16个业务团队）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '杭州 / 北京 / 上海 / 深圳等',
    applyUrl: 'https://campus-talent.alibaba.com/campus/gov',
    sourceUrl: 'https://campus-talent.alibaba.com/campus/gov',
    sourceLabel: '官方校招页',
    startDate: null,
    endDate: null,
    deadlineNote: '已开放；具体批次时间未公布',
    recommendation: 1,
    fitReason: '产品职类覆盖AI、云与多业务平台，可按具体JD选择B端或AI版简历。',
    riskNote: '业务跨度大，必须逐岗定向；毕业时间口径为2026.11—2027.10。',
    degreeGate: '海内外应届毕业生，逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'xiaomi-product-2027',
    company: '小米集团',
    role: '2027全球校招—产品方向',
    tracks: ['智能硬件/IoT', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京 / 武汉 / 南京 / 深圳等',
    applyUrl: 'https://hr.xiaomi.com/website/campus.html',
    sourceUrl: 'https://hr.xiaomi.com/website/campus.html',
    sourceLabel: '官方校招页',
    startDate: null,
    endDate: null,
    deadlineNote: '已开放；官网未公布统一截止',
    recommendation: 1,
    fitReason: '软硬件、AI与产品方向同时开放，IoT专业和GreenAuto可形成差异化。',
    riskNote:
      '硬件版缺真实量产经历，优先选设备软件/App/IoT平台而非品类负责人。',
    degreeGate: '2026.09.01—2027.08.31毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'pdd-campus-2027',
    company: '拼多多',
    role: '2027校园招聘—产品/运营方向（官网筛选）',
    tracks: ['B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '上海 / 广州等',
    applyUrl: 'https://careers.pddglobalhr.com/campus/',
    sourceUrl: 'https://careers.pddglobalhr.com/campus/',
    sourceLabel: '官方校招页',
    startDate: null,
    endDate: null,
    deadlineNote: '已开放；具体岗位滚动更新',
    recommendation: 1,
    fitReason: '平台与商业产品可使用B端版简历，但现有经历偏产业和知识产品。',
    riskNote: '业务强度与C端/商业化偏好较高，先确认具体产品岗再投。',
    degreeGate: '2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'dji-campus-2027',
    company: '大疆创新',
    role: '拓疆者校招—产品/数字化方向（官网筛选）',
    tracks: ['智能硬件/IoT', 'B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 上海 / 北京',
    applyUrl: 'https://careers.dji.com/zh-CN/campus/recruitment?from=sec_nav',
    sourceUrl: 'https://careers.dji.com/zh-CN/campus/recruitment?from=sec_nav',
    sourceLabel: '官方项目页',
    startDate: '2026-06-25',
    endDate: null,
    deadlineNote: '不设截止，招满即止；限投1个职位',
    recommendation: 1,
    fitReason: '智能硬件、端云协同和数字化场景契合IoT背景。',
    riskNote: '常规校招仅一次投递且不能改，先对比数字管理计划再决定。',
    degreeGate: '2027届高校毕业生',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'anker-campus-2027',
    company: '安克创新',
    role: '2027全球校招—智能硬件产品方向',
    tracks: ['智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 长沙 / 杭州 / 北京等',
    applyUrl: 'https://career.anker.com.cn/universities/recruitment/',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116865.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-21',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 1,
    fitReason: '消费智能硬件赛道与GreenAuto、IoT专业匹配。',
    riskNote: '更看重品类、供应链和量产意识，需突出选型、状态机和测试取舍。',
    degreeGate: '2027届；逐岗核对学历',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'lenovo-product-2027',
    company: '联想集团',
    role: '产品与项目方向',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '混合所有制',
    scale: '大厂',
    city: '北京 / 上海 / 深圳 / 天津 / 武汉等',
    applyUrl: 'https://talent.lenovo.com.cn/home',
    sourceUrl: 'https://job.wzu.edu.cn/campus/view/id/494874',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-05',
    endDate: '2026-11-13',
    deadlineNote: '简章称11月13日结束；建议10月前完成',
    recommendation: 1,
    fitReason: '智能设备、企业服务与项目协同都能承接B端和IoT版简历。',
    riskNote: '岗位差异大，优先找软件产品、设备平台或AI PC相关。',
    degreeGate: '本科及以上；2026.09.01—2027.08.31毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'xiaopeng-ai-product-2027',
    company: '小鹏集团',
    role: 'AI产品经理 / 产品方向',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '广州 / 深圳 / 上海 / 北京 / 武汉',
    applyUrl: 'https://xiaopeng.jobs.feishu.cn/campus',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116251.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-07-07',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 1,
    fitReason: 'AI、Agent、RAG与智能设备理解可同时发挥，物联网专业也加分。',
    riskNote: '汽车/物理AI竞争强，需用可运行AI应用和软硬件链路证明技术理解。',
    degreeGate: '本科及以上；2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'li-auto-product-2027',
    company: '理想汽车',
    role: '产品 / 整车与智能硬件方向',
    tracks: ['智能硬件/IoT', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京 / 上海 / 深圳 / 杭州 / 常州',
    applyUrl: 'https://www.lixiang.com/employ/campus/list.html?fromJob=1',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116875.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-21',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 1,
    fitReason: '产品、智能硬件、软件与具身智能多方向开放。',
    riskNote:
      '缺汽车行业项目，优先选座舱/设备软件/数字化产品，避免整车量产强门槛岗。',
    degreeGate: '本科及以上；2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'wondershare-ai-pm-2027',
    company: '万兴科技',
    role: 'AI产品经理',
    tracks: ['AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '长沙 / 深圳 / 杭州 / 北京 / 东京',
    applyUrl: 'https://bsurl.cn/v2/DBo3MpGj',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116994.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布；含秋招直招与实习转正',
    recommendation: 5,
    fitReason: 'AI Native软件产品、MVP与用户洞察非常贴合AI版简历。',
    riskNote: '部分岗位有产品体验报告，需提前拆解万兴喵影/PDF等产品。',
    degreeGate: '本科及以上；2026.09—2027.12毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'kedacom-pm-2027',
    company: '科达科技',
    role: '产品经理（2027校园招聘）',
    tracks: ['B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '苏州',
    applyUrl: 'https://www.kedacom.com/cn/xyjob_2.jhtml',
    sourceUrl: 'https://www.kedacom.com/cn/xyjob_2.jhtml',
    sourceLabel: '官方岗位列表',
    startDate: '2026-07-22',
    endDate: null,
    deadlineNote: '官网未公布，滚动处理',
    recommendation: 4,
    fitReason: '视讯安防、软件平台与硬件协同，比纯消费硬件更适配现有经历。',
    riskNote: '需补充对视频会议/安防行业和软硬件系统边界的理解。',
    degreeGate: '2027校园招聘；逐岗核对学历',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'spirit-ai-product-2027',
    company: '千寻智能',
    role: '具身智能产品经理 / 机器人产品经理',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '成长公司',
    city: '北京 / 杭州 / 深圳',
    applyUrl: 'https://nwd4iy9rd2s.jobs.feishu.cn/campusofSpiritAI',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116725.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-10',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 2,
    fitReason: 'AI与硬件交叉方向高度相关，GreenAuto可作基础证据。',
    riskNote: '团队门槛很高，偏好顶会/专利或顶级工程项目；作为冲刺项。',
    degreeGate: '本科/硕士/博士；2026.09—2027.12毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'chinatelecom-campus-2027',
    company: '中国电信',
    role: '行业/区域解决方案经理（产数类）',
    tracks: ['B端软件/平台', '能源数字化/央国企'],
    ownership: '央企',
    scale: '大厂',
    city: '全国',
    applyUrl: 'https://job.chinatelecom.com.cn/wt/TELE/web/index?_refluxos=a10',
    sourceUrl: 'https://www.chinatelecom.com.cn/ct/zp/168256.html',
    sourceLabel: '集团招聘公告 + 官方岗位页',
    startDate: '2026-08-24',
    endDate: null,
    deadlineNote: '各分子公司自行确定截止',
    recommendation: 3,
    fitReason: '岗位直接负责行业客户需求、场景化方案、招投标和售前交付，B端经历与物联网专业都能复用。',
    riskNote: '央企大平台但不是电力垂直，优先投普通产数岗位，避开明确面向重点高校的“优才计划”。',
    degreeGate: '本科及以上；2027届，部分单位接受未就业2026届',
    verifiedAt: '2026-09-02',
    compensation: '未公开；各分子公司口径不同',
  },
  {
    id: 'ct-digital-life-pm-2027',
    company: '天翼数字生活',
    role: '产品经理 / 产品运营',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '央企',
    scale: '中厂',
    city: '上海 / 南京 / 广州',
    applyUrl: 'https://job.chinatelecom.com.cn/wt/TELE/web/index?_refluxos=a10',
    sourceUrl:
      'https://m.fenbi.com/page/exam-information-detail/468756891196416',
    sourceLabel: '官方网申 + 招聘公告汇总',
    startDate: '2026-08-31',
    endDate: '2026-09-07',
    deadlineNote: '公告口径：9月7日截止',
    recommendation: 1,
    fitReason: '数字家庭、智慧社区和产品运营方向本身契合。',
    riskNote:
      '当前公告标注硕士/博士，与你本科学历不符；仅保留作提醒，不建议投入时间。',
    degreeGate: '硕士/博士（明确硬门槛）',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'cecloud-pm-2027',
    company: '中国电子云',
    role: '产品经理',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '央企',
    scale: '中厂',
    city: '北京 / 武汉 / 南京 / 杭州 / 成都',
    applyUrl: 'https://www.cecloud.com',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407567.htm',
    sourceLabel: '公司入口 + 高校招聘简章',
    startDate: '2026-08-27',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 3,
    fitReason: '政企云、AI平台与本体构建贴合企业知识产品和B端经历。',
    riskNote:
      '公告正文称本科可投，但高校需求表写硕士，必须先在官网核具体产品岗。',
    degreeGate: '口径冲突：招聘范围含本科，需求表写硕士',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'envision-product-2027',
    company: '远景能源',
    role: '产品 / 市场与解决方案',
    tracks: ['能源数字化/央国企', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '上海 / 江阴 / 全国及海外',
    applyUrl: 'https://envision-career.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116772.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-20',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 5,
    fitReason:
      '能源、AIoT、电力系统与产品能力四项重合，是最值得定向准备的机会之一。',
    riskNote: '逐岗区分产品、解决方案和工程岗；避免误投强电气/算法硬门槛职位。',
    degreeGate: '本科/硕士/博士；2027年毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'sungrow-campus-2027',
    company: '阳光电源',
    role: '2027全球校招—产品/解决方案方向（官网筛选）',
    tracks: ['能源数字化/央国企', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '合肥 / 上海 / 南京等',
    applyUrl: 'https://jobs.sungrowpower.com/',
    sourceUrl: 'https://jobs.sungrowpower.com/',
    sourceLabel: '官方招聘页',
    startDate: '2026-08-10',
    endDate: null,
    deadlineNote: '正式批已启动；官网未公布统一截止',
    recommendation: 5,
    fitReason: '新能源硬件、智慧能源和行业数字化与清能经历互补。',
    riskNote: '先筛产品/解决方案/数字化岗位，纯电气研发岗不匹配。',
    degreeGate: '2027届；逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'catl-campus-2027',
    company: '宁德时代',
    role: '计算机与AI / 市场 / 运营方向（官网筛选）',
    tracks: ['能源数字化/央国企', 'B端软件/平台'],
    ownership: '私企',
    scale: '大厂',
    city: '宁德 / 上海 / 北京 / 杭州 / 武汉等',
    applyUrl: 'https://talent.catl.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116814.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布；3次志愿机会',
    recommendation: 3,
    fitReason:
      '新能源产业和计算机/AI方向开放，可寻找数字化产品、业务系统或项目岗。',
    riskNote: '公开简章未列明确产品经理，需以岗位列表为准，不要为凑方向盲投。',
    degreeGate: '本科及以上；2026.07—2027.12毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'amazon-program-2027',
    company: '亚马逊中国',
    role: 'Program Manager / Tech Business Developer',
    tracks: ['B端软件/平台'],
    ownership: '外企',
    scale: '大厂',
    city: '北京 / 上海 / 深圳',
    applyUrl:
      'https://www.amazon.jobs/content/zh/career-programs/university?country%5B%5D=CN',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116983.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '官网未公布；最多申请3个职位',
    recommendation: 3,
    fitReason: '项目管理、技术业务与云服务方向可承接B端系统和跨团队协作。',
    riskNote:
      '不是标准产品经理，英语和学历要求需逐岗位核对；优先看深圳Program Manager。',
    degreeGate: '部分岗位可能偏硕士；逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'oppo-display-pm-2027',
    company: 'OPPO',
    role: '多媒体屏显产品经理',
    tracks: ['智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳',
    applyUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1829?recruitType=Graduate',
    sourceUrl:
      'https://careers.oppo.com/university/oppo/campus/post/1829?recruitType=Graduate',
    sourceLabel: '官方岗位页',
    startDate: '2026-07-15',
    endDate: null,
    deadlineNote: '官网未公布，建议尽早',
    recommendation: 1,
    fitReason: '产品规划与硬件模块协同方向相关。',
    riskNote: '岗位明确要求硕士及以上，与本科学历不符；不建议投。',
    degreeGate: '硕士及以上（明确硬门槛）',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'duxiaoman-ai-pm-2027',
    company: '度小满',
    role: 'AI应用产品经理 / 信贷产品经理',
    tracks: ['AI应用产品', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 上海',
    applyUrl: 'https://campus.duxiaoman.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116782.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-18',
    endDate: null,
    deadlineNote: '官网未公布，滚动招聘',
    recommendation: 3,
    fitReason:
      '明确开放AI应用产品经理，金融AI、复杂规则和业务闭环与达观、清能经历都能衔接。',
    riskNote:
      '金融产品强调风险与指标意识，需准备模型能力如何转化为业务收益和合规边界。',
    degreeGate: '本科及以上；2026.09—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'insta360-ai-pm-2027',
    company: '影石 Insta360',
    role: 'AI软件产品经理（2027校招）',
    tracks: ['AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'https://www.insta360.com/cn/jobs',
    sourceUrl: 'https://www.shushuqiuzhi.com/position/423563',
    sourceLabel: '官网入口 + 当前岗位页',
    startDate: '2026-06-30',
    endDate: '2026-10-31',
    deadlineNote: '招聘汇总口径10月31日截止，岗位可能提前招满',
    recommendation: 2,
    fitReason:
      'AI工具、App、多端设备体验同时匹配AI MVP、IoT专业和GreenAuto，属于非常好的交叉型中厂机会。',
    riskNote:
      '需要产品作品集与交互敏感度，建议准备AI工作流Demo和影像产品体验拆解。',
    degreeGate: '本科及以上；专业不限，软件/交互/计算机背景优先',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'emdoor-product-2027',
    company: '亿道数码',
    role: '产品经理（智能终端）',
    tracks: ['智能硬件/IoT', 'B端软件/平台'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'mailto:CR@emdoor.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116842.html',
    sourceLabel: '高校官方就业网岗位页',
    startDate: '2026-08-20',
    endDate: null,
    deadlineNote: '邮箱投递；未公布截止时间',
    recommendation: 2,
    fitReason:
      '岗位覆盖需求、规格、量产交付和全生命周期，IoT背景与硬件产品版简历高度对口。',
    riskNote:
      '要求CET-6并重视量产与营销意识，需补充选型、测试、供应链协同案例。',
    degreeGate: '本科及以上；电子/通信/计算机/软件相关，CET-6',
    verifiedAt: '2026-09-01',
    compensation: '15–20K/月（招聘页公开区间）',
  },
  {
    id: 'yangteng-product-2027',
    company: '扬腾创新',
    role: '供应链数智化产品经理',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '福州',
    applyUrl: 'https://yangtenginnovation-compus.zhiye.com',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407468.htm',
    sourceLabel: '网申入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: null,
    deadlineNote: '已正式启动；官网未公布截止',
    recommendation: 4,
    fitReason:
      '明确负责供应链数智化产品、需求与交付，和B端业务系统、数据产品经验直接匹配。',
    riskNote: '跨境汽配场景较陌生，面试前要补供应链、库存和履约指标框架。',
    degreeGate: '本科及以上；计算机/软件工程相关，CET-4',
    verifiedAt: '2026-09-01',
    compensation: '13–20K/月（招聘简章公开区间）',
  },
  {
    id: 'hello-momo-product-2027',
    company: '挚文集团',
    role: '社交 / 商业 / 海外产品经理',
    tracks: ['AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '北京',
    applyUrl: 'https://campus.immomo.com',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407229.htm',
    sourceLabel: '高校招聘简章',
    startDate: '2026-08-10',
    endDate: null,
    deadlineNote: '8月10日网申启动；未公布截止',
    recommendation: 3,
    fitReason:
      '产品岗位明确开放，AI与亿级用户产品能提供产品Sense训练和冲刺机会。',
    riskNote:
      '偏C端社交与商业化，与你当前B端/行业产品证据不完全同构，需要独立准备C端案例。',
    degreeGate: '本科及以上；2026.12—2027.08毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'metax-product-2027',
    company: '沐曦股份',
    role: '产品管理 / 项目管理（GPU平台）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 北京 / 南京 / 成都',
    applyUrl: 'https://www.metax-tech.com/join.html',
    sourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407387.htm',
    sourceLabel: '官方招聘页 + 高校招聘简章',
    startDate: '2026-07-31',
    endDate: null,
    deadlineNote: '7月底起网申，滚动发放Offer',
    recommendation: 3,
    fitReason:
      '国产GPU与AI基础设施是高质量B端产品场景，能发挥技术理解和平台产品能力。',
    riskNote: '产品管理岗位可能偏技术且逐岗学历不同，务必先确认是否接受本科。',
    degreeGate: '招聘范围含本科；具体产品岗需逐岗核对',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'ke-product-2027',
    company: '贝壳找房',
    role: '产品经理 / 策略产品 / 数据产品',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京 / 上海 / 杭州 / 广州等',
    applyUrl: 'https://campus.ke.com/campus/jobs',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117001.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-26',
    endDate: '2026-10-31',
    deadlineNote: '高校就业网标注10月31日；每类招聘项目限投1岗',
    recommendation: 1,
    fitReason:
      '产业互联网、策略与数据产品方向可直接使用B端版简历，业务复杂度也适合需求拆解优势。',
    riskNote:
      '产品细分多且只限投一个岗位，先对比策略、数据和业务产品JD再提交。',
    degreeGate: '本科及以上；2026.09.01—2027.08.31毕业',
    verifiedAt: '2026-09-01',
  },
  {
    id: 'fanruan-product-2027',
    company: '帆软软件',
    role: '产品经理（一体化平台）',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '无锡 / 南京 / 杭州',
    applyUrl: 'https://join.fanruan.com/campus/detail?id=9869',
    sourceUrl: 'https://join.fanruan.com/campus/detail?id=9869',
    sourceLabel: '官方岗位页',
    startDate: '2026-08-01',
    endDate: null,
    deadlineNote: '提前批8月31日结束，官方岗位页仍开放，建议立即确认',
    recommendation: 5,
    fitReason:
      '明确偏好ToB软件产品实习，企业BI、流程设计、需求到交付与你的经历直接同构，且不设名校/研究生硬门槛。',
    riskNote: '需要把清能与达观经历讲成客户价值、模块指标和0→1/1→N迭代闭环。',
    degreeGate: '2027届本科及以上，理工科背景；未写985/211限制',
    verifiedAt: '2026-09-01',
    compensation: '16–20.5K/月，SP另议；不含年终奖',
  },
  {
    id: 'hand-ai-consultant-2027',
    company: '汉得信息',
    role: '数智化咨询顾问（AI方向）',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '私企',
    scale: '中厂',
    city: '天津 / 河北 / 武汉 / 成都 / 西安',
    applyUrl: 'https://career.hebut.edu.cn/correcruit/content/id/73275.html',
    sourceUrl: 'https://job.hdu.edu.cn/campus/view?id=9568',
    sourceLabel: '高校招聘简章 + 岗位页',
    startDate: '2026-08-28',
    endDate: null,
    deadlineNote: '已开放，未公布统一截止',
    recommendation: 5,
    fitReason:
      '岗位明确偏好“能源+AI”复合经验，工作本质是B端需求、方案、数据/AI落地，与你的电力交易和AI经历高度重合。',
    riskNote:
      '岗位是咨询顾问而非标准产品经理，出差较多；优势是成功率和垂直复用度更高。',
    degreeGate: '本科及以上；未写985/211限制',
    verifiedAt: '2026-09-01',
    compensation: '转正8–10K/月；实习3–4.5K/月',
  },
  {
    id: 'transwarp-ai-delivery-2027',
    company: '星环科技',
    role: 'AI交付 / 售前（认知数据库与知识图谱）',
    tracks: ['B端软件/平台', 'AI应用产品', '能源数字化/央国企'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 北京 / 南京 / 广州 / 成都',
    applyUrl: 'https://app.mokahr.com/campus_apply/transwarp',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116990.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-18',
    endDate: '2026-12-31',
    deadlineNote: '8月18日—12月31日',
    recommendation: 4,
    fitReason:
      '企业级AI、GPU原生认知数据库、知识图谱及能源行业客户都能复用达观本体构建与B端交付证据。',
    riskNote:
      '当前校招未列产品经理，建议把AI交付/售前作为高匹配曲线救国岗位，不投纯研发。',
    degreeGate: '2027届本科及以上；计算机/通信/电子/网络',
    verifiedAt: '2026-09-01',
    compensation: '薪资未公开；全额五险一金、补充公积金/商保、搬家费与签字费',
  },
  {
    id: 'nio-energy-product-2027',
    company: '蔚来',
    role: '产品经理（充电/能源产品，A136978）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '上海',
    applyUrl: 'https://campus.nio.com/',
    sourceUrl:
      'https://www.recruit.net/job/%E4%BA%A7%E5%93%81%E7%BB%8F%E7%90%86-jobs/CFD4273E2B2C0766',
    sourceLabel: '官方校招入口 + 岗位镜像',
    startDate: '2026-08-27',
    endDate: null,
    deadlineNote: '正式批已开放；官网未公布统一截止，建议优先投',
    recommendation: 5,
    fitReason: '岗位同时覆盖充电硬件、能源产品、充电管理系统、PRD与AI/机器学习，和你的电力+产品+AI经历高度同构。',
    riskNote: '要求读懂电力电子基础和硬件规格；面试前补DC/DC、DC/AC、充电拓扑与能源云产品案例。',
    degreeGate: '具体岗位明确本科及以上；电气/新能源优先，计算机/AI且有电力电子经历也可',
    verifiedAt: '2026-09-02',
    compensation: '未公开',
  },
  {
    id: 'ampace-aidc-solution-2027',
    company: 'Ampace新能安',
    role: 'AIDC解决方案售前 / 储能交付',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '厦门',
    applyUrl: 'https://www.ampace.com/join-us',
    sourceUrl: 'https://career.hebut.edu.cn/correcruit/content/id/79145.html',
    sourceLabel: '官网招聘入口 + 高校招聘简章',
    startDate: '2026-08-17',
    endDate: null,
    deadlineNote: '全球校招已开放；招满为止',
    recommendation: 5,
    fitReason: 'AIDC供电、储能系统、EMS/BMS、IoT与客户方案是AI+能源的直接交叉，适合用清能和达观经历组合投递。',
    riskNote: '售前岗要求较强电力电子知识、英语和出差适应度；不要误投明确硕士的嵌入式EMS岗。',
    degreeGate: '项目面向本硕博；AIDC解决方案售前具体岗位明确本科及以上，未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '10K+/月；实习3–4.5K/月（高校页面）',
  },
  {
    id: 'sigenergy-sales-service-2027',
    company: '思格新能源',
    role: 'AI+光储 销售与服务 / 市场营销',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 南通 / 珠海',
    applyUrl: 'https://jobs.sigenergy.com/campus',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116730.html',
    sourceLabel: '官方校招入口 + 高校招聘简章',
    startDate: '2026-08-17',
    endDate: '2026-11-30',
    deadlineNote: '网申8—11月；每人2次投递机会',
    recommendation: 5,
    fitReason: '公司主线就是全场景AI+光储，销售与服务岗位可直接讲电力市场、能源客户需求和AI产品方案。',
    riskNote: '简章只公布职类，投递时优先解决方案、销售支持、客户成功类，逐岗确认专业和学历。',
    degreeGate: '2027届本硕博；校招总项目明确本科开放，未写名校硬限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开',
  },
  {
    id: 'nrec-support-2027',
    company: '南瑞继保',
    role: '技术支持 / 国内营销 / 信息技术',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '国企',
    scale: '中厂',
    city: '南京 / 常州 / 成都 / 西安 / 济南等',
    applyUrl: 'https://nrec.zhiye.com/campus',
    sourceUrl:
      'https://www.wondercv.com/xiaozhao/nanrui-jibao-2027-campus-recruitment-13172-8ca5ea/',
    sourceLabel: '官方招聘入口 + 2027校招公告汇总',
    startDate: '2026-08-24',
    endDate: '2026-10-24',
    deadlineNote: '本科生通常随对应学校宣讲截止；无宣讲学校建议10月前完成',
    recommendation: 4,
    fitReason: '电力系统自动化、储能/氢能与技术支持场景高度垂直，央国企背景不再是唯一卖点，电力实习能真正形成差异。',
    riskNote: '不是标准产品经理，优先技术支持、国内营销、信息技术；研发/设计岗通常更看专业深度。',
    degreeGate: '2027届本科明确开放；本科对应技术支持/营销/信息类方向，未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开；七险二金、宿舍等福利',
  },
  {
    id: 'yonyou-b2b-product-2027',
    company: '用友网络',
    role: '产品经理（B端，高潜）-27届',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '大厂',
    city: '北京',
    applyUrl: 'http://career.yonyou.com',
    sourceUrl:
      'https://www.hotjob.cn/wt/yonyou/mobweb/v8/position/list?brandCode=1&recruitType=1',
    sourceLabel: '官方招聘系统',
    startDate: '2026-08-07',
    endDate: null,
    deadlineNote: '官方岗位仍在更新；未公布统一截止',
    recommendation: 5,
    fitReason: 'JD直接写ToB产品规划、企业需求抽象、应用模型与跨研发推进，和你现有B端产品证据几乎逐项对应。',
    riskNote: '标注“高潜”且抗压要求高；重点准备企业流程抽象、平台化取舍和客户需求标准化案例。',
    degreeGate: '具体岗位明确统招本科及以上；未写985/211或研究生限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开',
  },
  {
    id: 'sitech-ai-product-2027',
    company: '思特奇',
    role: 'AI产品经理 / 产品运营 / 方案经理',
    tracks: ['B端软件/平台', 'AI应用产品'],
    ownership: '私企',
    scale: '中厂',
    city: '北京 / 成都 / 合肥 / 西安 / 广州等',
    applyUrl: 'https://mp.weixin.qq.com/s/nLFzDdUuJujXRJUKf7S1hw',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117169.html',
    sourceLabel: '官方投递说明 + 高校招聘简章',
    startDate: '2026-08-28',
    endDate: null,
    deadlineNote: '官网未公布；可通过公众号或campus邮箱投递',
    recommendation: 5,
    fitReason: '中型企业服务厂商直接开放AI产品与方案岗，B端需求、AI落地和运营闭环都能复用，学历投入产出比高。',
    riskNote: '电信运营商场景较强，面试要把达观/清能经历转成行业解决方案，而不是只讲通用产品方法。',
    degreeGate: '2027届本科/硕士/博士；产品生态类未写名校或研究生硬门槛',
    verifiedAt: '2026-09-02',
    compensation: '15–20K/月（高校页面）',
  },
  {
    id: 'teld-solution-2027',
    company: '特来电',
    role: '售前 / 解决方案 / 项目工程师（电气类）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '青岛 / 西安 / 南京 / 全国大区',
    applyUrl: 'https://hr.teld.cn/recruit',
    sourceUrl: 'https://myjob.dlmu.edu.cn/campus/view/id/868552',
    sourceLabel: '官方招聘入口 + 高校招聘简章',
    startDate: '2026-08-29',
    endDate: '2026-11-20',
    deadlineNote: '高校页面标注11月20日；建议优先总部售前/解决方案',
    recommendation: 5,
    fitReason: '数字化充电网、电力交易、能源业务和B端方案与你的电力产品实习直接同构，是比泛互联网产品更值得优先的岗位。',
    riskNote: '总部售前偏电气技术，部分全国岗位偏销售；根据你对出差和业绩指标的接受度排序。',
    degreeGate: '总部电气类明确招本科；售前/解决方案岗列在本科开放类别，未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '总部电气类10.5–15K/月（高校职位表）',
  },
  {
    id: 'byd-energy-digital-2027',
    company: '比亚迪',
    role: '新能源解决方案 / 数字化 / 产品策略',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 西安 / 长沙 / 合肥等',
    applyUrl: 'https://job.byd.com',
    sourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/117011.html',
    sourceLabel: '官方入口 + 高校招聘简章',
    startDate: '2026-08-26',
    endDate: null,
    deadlineNote: '官网未公布统一截止；岗位量大，建议先锁新能源产业/电池/闪充',
    recommendation: 3,
    fitReason: '虽然是大厂，但储能、光伏、构网、电网技术、闪充运营和数字化方向属于你的垂直例外，可选择性投递。',
    riskNote: '岗位池非常宽且团队差异大；不投泛汽车研发，优先储能解决方案、闪充运营、信息化平台与产品策略。',
    degreeGate: '2027届本科/硕士/博士；项目明确本科开放，具体岗位逐项核专业',
    verifiedAt: '2026-09-02',
    compensation: '10–15K/月（高校页面总区间）',
  },
  {
    id: 'voyah-product-digital-2027',
    company: '岚图汽车',
    role: '产品企划与体验 / 智能产品平台 / 数字化发展',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '央企',
    scale: '中厂',
    city: '武汉 / 北京',
    applyUrl: 'https://app.mokahr.com/campus-recruitment/voyah/146293',
    sourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/79130.html',
    sourceLabel: '官方校招入口 + 高校招聘简章',
    startDate: '2026-08-13',
    endDate: null,
    deadlineNote: '官网未公布统一截止；按岗位滚动处理',
    recommendation: 3,
    fitReason: '央企新能源例外，且明确开放产品企划、智能产品平台和数字化发展，可作为汽车能源方向的补充投递。',
    riskNote: '偏C端汽车和用户体验，竞争与行业门槛仍高；只投与你产品/IoT经历能形成证据链的岗位。',
    degreeGate: '项目明确面向2027届本硕博，高校页面学历要求本科；未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '10.5–15K/月（高校页面）',
  },
  {
    id: 'inovance-b2b-market-2027',
    company: '汇川技术',
    role: '市场类（工业自动化/新能源解决方案）',
    tracks: ['B端软件/平台', '能源数字化/央国企', '智能硬件/IoT'],
    ownership: '私企',
    scale: '大厂',
    city: '深圳 / 苏州 / 东莞 / 西安',
    applyUrl: 'https://recruit.inovance.com/',
    sourceUrl:
      'https://jy.scu.edu.cn/index/index/employjobdetail.html?data=MDAwMDAwMDAwMJG6n3_Ed6imi4qQtLh4Y9yK0dTOs4bddricp9CWi5qikaeWacSdqLqGfaK2w4iil5C4zNbGiL-E',
    sourceLabel: '官方招聘入口 + 高校具体岗位页',
    startDate: '2026-08-18',
    endDate: '2027-08-17',
    deadlineNote: '岗位页有效期至2027年8月17日；校招滚动筛选',
    recommendation: 4,
    fitReason: '面向设备制造商的工业自动化与新能源方案，本质是B端产品理解、客户需求和方案推介，垂直价值高。',
    riskNote: '市场类含销售目标且出差较多，不是纯产品经理；适合接受客户一线和业绩导向时投递。',
    degreeGate: '具体市场类岗位明确本科，电气/自动化/机械/电力电子相关本科或硕士；无名校硬限制',
    verifiedAt: '2026-09-02',
    compensation: '12–20K/月（具体市场类职位页）',
  },
  {
    id: 'foxess-solution-2027',
    company: '麦田能源（FOX ESS）',
    role: '解决方案工程师 / 产品文档 / 项目管理',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '上海 / 无锡 / 温州 / 东莞',
    applyUrl: 'https://fox-ess.zhiye.com/',
    sourceUrl: 'https://career.gdut.edu.cn/campus/view/id/1020697',
    sourceLabel: '官方招聘入口 + 高校招聘简章',
    startDate: '2026-08-24',
    endDate: null,
    deadlineNote: '2027全球校招已开放；官网未公布统一截止',
    recommendation: 4,
    fitReason: '储能逆变器与能源解决方案是明确B端场景，规模适中，比无垂直经验去泛大厂更能利用电力经历。',
    riskNote: '解决方案岗偏电力电子且可能要求英语；高校信息页已到展示期，但官方招聘站仍需再次确认岗位状态。',
    degreeGate: '2027届本硕博；解决方案/产品文档在本科开放校招清单，未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '面议；五险一金、年终奖',
  },
  {
    id: 'kehua-digital-energy-2027',
    company: '科华数据',
    role: '售前技术 / IT产品助理 / 微网EMS',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '厦门 / 深圳 / 漳州',
    applyUrl:
      'https://app.mokahr.com/campus-recruitment/kehua/92510#/jobs?page=1&anchorName=jobsList',
    sourceUrl: 'https://jy.gzhu.edu.cn/web/index/jobs-brief-detail?id=SQUXSVQ',
    sourceLabel: '官方校招入口 + 高校招聘简章',
    startDate: '2026-08-25',
    endDate: '2026-11-25',
    deadlineNote: '高校页面标注11月25日；网申后需完成线上测评',
    recommendation: 5,
    fitReason: '公司定位AI+数字能源，开放微网/EMS、售前技术和IT产品助理，几乎覆盖你想要的AI、电力与B端交集。',
    riskNote: '研发类多偏电力电子；优先IT产品助理、售前技术、运营或微网EMS相关，逐岗确认本科要求。',
    degreeGate: '2027届本硕博；营销/IT职能明确含本科，普通本科亦有地方补贴口径',
    verifiedAt: '2026-09-02',
    compensation: '未公开；月薪+年终奖+利润奖',
  },
  {
    id: 'sac-power-ai-service-2027',
    company: '国电南自',
    role: '调试服务（储能/新能源）/ AI与系统软件',
    tracks: ['能源数字化/央国企', 'B端软件/平台', 'AI应用产品', '智能硬件/IoT'],
    ownership: '央企',
    scale: '中厂',
    city: '南京',
    applyUrl: 'https://sac2027.zhaopin.com/',
    sourceUrl: 'https://nj.bendibao.com/job/2026825/182644.shtm',
    sourceLabel: '官方投递入口 + 2027校招岗位汇总',
    startDate: '2026-08-25',
    endDate: '2026-10-24',
    deadlineNote: '第三方汇总标注10月24日；需同时完成国电南自与华电集团系统投递',
    recommendation: 4,
    fitReason: '央企电力自动化核心场景，储能/新能源调试、AI和系统软件都能放大你的电力与AI交叉经历。',
    riskNote: '不是产品岗，技术实操要求高；优先本科开放的调试服务，AI/研发岗位必须在官网逐岗确认学历。',
    degreeGate: '2027校招面向本科及以上；调试服务（电气/储能/新能源）具体岗位明确本科可投',
    verifiedAt: '2026-09-02',
    compensation: '未公开；六险二金、餐补、住房政策及安家费',
  },
  {
    id: 'wisdom-power-solution-marketing-2027',
    company: '东方威思顿',
    role: '国内方案营销（数字电力 / 智慧能源）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '国企',
    scale: '中厂',
    city: '烟台 / 全国',
    applyUrl: 'http://bjxapp.cn/t/NjM0NDQyNA/',
    sourceUrl: 'https://www.fenbi.com/page/exam-information-detail/468601157997568',
    sourceLabel: '2027校招公告 + 高校具体岗位页',
    startDate: '2026-08-24',
    endDate: null,
    deadlineNote: '2027校招已开放；未公布统一截止，建议优先投',
    recommendation: 5,
    fitReason: '国企中少见的“数字电力+智慧能源+方案营销”本科岗位，客户覆盖电网、能源与工业企业，和清能B端经历高度同构。',
    riskNote: '岗位带市场拓展属性，并要求接受长期驻外或短期出差；适合愿意走客户方案路线时重点投。',
    degreeGate: '具体营销序列明确本科及以上；未写985/211或研究生硬限制',
    verifiedAt: '2026-09-02',
    compensation: '5–10K/月；五险二金（具体岗位页）',
  },
  {
    id: 'wisdri-automation-technical-marketing-2027',
    company: '中冶南方自动化',
    role: '技术工程师 / 营销管培生（工业自动化）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '央企',
    scale: '中厂',
    city: '武汉 / 项目现场',
    applyUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/79331.html',
    sourceUrl: 'https://www.fenbi.com/page/exam-information-detail/468506749195266',
    sourceLabel: '2027校招公告（含岗位学历表）',
    startDate: '2026-08-20',
    endDate: null,
    deadlineNote: '邮箱滚动接收：autohr@wisdri.com',
    recommendation: 4,
    fitReason: '央企工业数字化与电力电子场景，岗位直接做自动化系统设计调试、技术支持或数智化项目市场，能复用B端需求和交付经验。',
    riskNote: '不是标准产品经理，技术岗有现场调试，营销岗有市场目标；不要投明确要求硕士的产品技术研发工程师。',
    degreeGate: '技术工程师、营销管培生均明确本科及以上；一般岗未写名校限制',
    verifiedAt: '2026-09-02',
    compensation: '一般岗未公开；七险一金、绩效奖金、单身公寓等',
  },
  {
    id: 'hoymiles-product-engineer-2027',
    company: '禾迈股份',
    role: '产品工程师 / 技术支持工程师（光伏储能）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '杭州 / 苏州 / 成都 / 海宁 / 丽水',
    applyUrl: 'https://www.hoymiles.com/',
    sourceUrl: 'https://job.hdu.edu.cn/campus/view?id=9558',
    sourceLabel: '2027校招岗位学历明细',
    startDate: '2026-08-24',
    endDate: '2026-11-23',
    deadlineNote: '高校招聘页标注11月23日到期；从官网“招贤纳士”进入校招投递',
    recommendation: 4,
    fitReason: '光伏逆变器与储能系统的产品技术岗，既贴电力能源又面向客户与产品落地，比泛互联网产品更能利用垂直经历。',
    riskNote: '产品工程师偏技术产品，需要电气/自动化/电力电子基础；若专业不完全匹配，优先技术支持或投标管理。',
    degreeGate: '产品工程师、技术支持工程师均明确本科及以上；未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '本科：研发12–33万/年，非研发12–23万/年',
  },
  {
    id: 'ecoflow-presales-2027',
    company: '正浩创新 EcoFlow',
    role: '售前工程师（储能解决方案）',
    tracks: ['能源数字化/央国企', 'B端软件/平台', '智能硬件/IoT'],
    ownership: '私企',
    scale: '中厂',
    city: '深圳',
    applyUrl: 'https://www.nowcoder.com/jobs/detail/464341',
    sourceUrl: 'https://www.nowcoder.com/jobs/detail/464341',
    sourceLabel: '2027校招具体岗位页',
    startDate: '2026-08-31',
    endDate: '2026-11-01',
    deadlineNote: '高校秋招页标注11月1日到期；岗位页当前可投',
    recommendation: 4,
    fitReason: '直接做清洁能源产品演示、客户场景方案、需求反馈与产品迭代，是储能行业里很接近B端产品的本科机会。',
    riskNote: '要求英语可作为工作语言，专业偏电气/电力电子/新能源；若英语或技术基础不足，优先级下调。',
    degreeGate: '具体岗位明确2027届本科及以上；未写985/211限制',
    verifiedAt: '2026-09-02',
    compensation: '14–17K/月 × 12薪（岗位页）',
  },
  {
    id: 'cetc-digital-project-client-2027',
    company: '中电科数字',
    role: '工程/运维项目经理 / 客户经理（数字新基建）',
    tracks: ['B端软件/平台', '能源数字化/央国企', '智能硬件/IoT'],
    ownership: '央企',
    scale: '中厂',
    city: '上海 / 全国',
    applyUrl: 'https://www.shecc.com/job.html',
    sourceUrl: 'https://www.shecc.com/job.html',
    sourceLabel: '公司官方2027校园招聘页',
    startDate: '2026-09-02',
    endDate: null,
    deadlineNote: '官方明确不设统一截止时间，滚动处理；简历投至campus@shecc.com',
    recommendation: 3,
    fitReason: '央企B端数字化平台，数据中心、物联感知与行业解决方案场景明确，可用项目管理和企业客户经历切入。',
    riskNote: '当前开放的是项目/客户岗位而非产品经理，且非电力垂直；作为央企B端补充，不要排在能源中厂之前。',
    degreeGate: '官方岗位页明确2027届本科及以上；未写985/211或双一流限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开；五险一金、补充公积金、商业保险及补贴',
  },
  {
    id: 'chnenergy-xinjiang-digital-2027',
    company: '国能新疆电力',
    role: '专业技术岗T类（软件 / 大数据 / AI）',
    tracks: ['能源数字化/央国企', 'AI应用产品', 'B端软件/平台'],
    ownership: '央企',
    scale: '大厂',
    city: '新疆',
    applyUrl: 'https://zhaopin.chnenergy.com.cn/',
    sourceUrl: 'https://www.fenbi.com/page/exam-information-detail/468777906491392',
    sourceLabel: '2027秋招岗位学历表 + 集团官网入口',
    startDate: '2026-09-01',
    endDate: null,
    deadlineNote: '国家能源集团系统已开放；具体截止以职位页为准',
    recommendation: 3,
    fitReason: '能源央企里明确向本科开放的软件、大数据与AI技术岗，专业与清洁能源经历可形成垂直证据链。',
    riskNote: '不是产品岗且工作地点在新疆；仅在接受地点和技术路线时投，推荐度低于能源产品/解决方案中厂。',
    degreeGate: '专业技术岗T类明确本科/硕士；本科专业含计算机、软件、大数据、人工智能，未写名校硬限制',
    verifiedAt: '2026-09-02',
    compensation: '未公开；央企标准福利以具体单位为准',
  },
];
