export type ScreeningReview = {
  eligible: boolean;
  reason: string;
  salaryKind?: '本届公开' | '招聘转载参考' | '往届参考' | '未公开';
  monthlyMin?: number;
  salarySourceUrl?: string;
  salarySourceLabel?: string;
  exceptionReason?: string;
};

// 2026-09-14：按具体岗位审核；“大厂”仅指互联网超大厂，产业科技企业不因规模自动排除。
const exclusions: [string, string[]][] = [
  ['同公司已有更早的主记录；重复岗位默认隐藏，但已有准备/投递进度仍保留', [
    'cloudview-browser-ai-product-2027', 'autohome-ai-agent-product-2027',
  ]],
  ['互联网超大厂不再新增推荐；已有准备或投递进度继续保留', [
    'baidu-ai-pm-2027', 'alibaba-cloud-product-2027', 'alibaba-group-product-2027',
    'pdd-campus-2027',
  ]],
  ['规模不作为排除理由，但这些旧集团入口或泛岗位尚未通过本科具体产品岗与薪资证据复核', [
    'dji-digital-2027', 'oppo-internet-pm-2027',
    'dji-campus-2027',
    'lenovo-product-2027', 'xiaopeng-ai-product-2027', 'li-auto-product-2027',
    'chinatelecom-campus-2027', 'catl-campus-2027',
    'ke-product-2027', 'yonyou-b2b-product-2027',
    'byd-energy-digital-2027',
    'chnenergy-xinjiang-digital-2027', 'sany-digital-energy-2027',
    'star-net-product-2027', 'inspur-datacenter-product-2027',
  ]],
  ['偏项目管理、实施交付、工程服务或非产品工作，不再主动推荐', [
    'metax-product-2027', 'hand-ai-consultant-2027', 'transwarp-ai-delivery-2027',
    'foxess-solution-2027',
    'cetc-digital-project-client-2027', 'dongfang-electric-solution-2027',
    'neusoft-consulting-2027',
  ]],
  ['私企公开月薪下限不足1万元；不以区间上限判断符合要求', [
    'sifang-power-solution-2027', 'luoshu-ai-energy-2027',
  ]],
  ['尚缺同城市应届产品岗的可靠月薪参考，暂不计入高薪推荐', [
    'duxiaoman-ai-pm-2027', 'insta360-ai-pm-2027',
    'sigenergy-sales-service-2027', 'hoymiles-product-engineer-2027',
  ]],
  ['未核实到计算机本科匹配的具体产品岗，不用专业大类或集团入口代替岗位', [
    'voyah-product-digital-2027',
    'fiberhome-solution-product-2027',
    'hei-digital-energy-2027', 'huadian-zhejiang-digital-2027',
  ]],
];

export const screeningReviews: Record<string, ScreeningReview> = {
  ...Object.fromEntries(exclusions.flatMap(([reason, ids]) =>
    ids.map((id) => [id, { eligible: false, reason }]),
  )),
  'hundsun-requirements-ai-2027': {
    eligible: true,
    reason: '2027需求分析师明确接受计算机本科，职责与B端需求和产品协同直接相关，具体岗位12–25K×14薪',
    salaryKind: '本届公开', monthlyMin: 12000,
    salarySourceUrl: 'https://www.nowcoder.com/jobs/detail/459402',
    salarySourceLabel: '恒生电子2027需求分析师J10368具体岗位',
    exceptionReason: '金融IT产品相邻岗：优先需求分析或AI应用，面试确认版本维护、客户项目与产品需求工作的占比',
  },
  'pylontech-cloud-product-2027': {
    eligible: true,
    reason: '储能云平台具体产品工程师，本科信息技术/AI可投，覆盖需求、原型、路标和APP/WEB产品，12–23K/月',
    salaryKind: '招聘转载参考', monthlyMin: 12000,
    salarySourceUrl: 'https://bebee.com/cn/jobs/2027j11749-shanghai--fj-2387379377',
    salarySourceLabel: '派能科技2027产品工程师J11749招聘转载',
    exceptionReason: 'AI+能源高匹配项：英语和能源云平台经历为偏好，不是电力专业硬门槛；岗位临近10月13日截止',
  },
  'techen-ai-energy-application-2027': {
    eligible: true,
    reason: '2027数字能源校招单列AI应用、AI数据和全球产品工程岗位，本科计算机/软件/AI明确可投，项目口径10K起',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80511.html',
    salarySourceLabel: '青岛乾程科技2027全球校园招聘简章',
    exceptionReason: 'AI+能源高匹配项：只投AI应用/数据/软件产品，明确避开电气、硬件、交付和客户服务岗位',
  },
  'iwhalecloud-product-trainee-2027': {
    eligible: true,
    reason: '2027产品经理管培生明确接受计算机本科，职责覆盖调研、PRD、原型、研发测试上线和数据复盘',
    salaryKind: '招聘转载参考', monthlyMin: 15000,
    salarySourceUrl: 'https://www.jobui.com/company/15458519/salary/j/chanpinjingli/',
    salarySourceLabel: '浩鲸科技当前产品经理15–25K招聘平台参考，非本届Offer承诺',
    exceptionReason: '高匹配通信/政企B端产品：只选产品经理管培，避开海外交付、运营咨询和驻场实施方向',
  },
  'pudurobotics-product-manager-2027': {
    eligible: true,
    reason: '2027商用机器人产品经理，本科开放，职责覆盖B端客户、PRD、软硬件协同和全生命周期，15–30K×14薪',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://www.nowcoder.com/jobs/detail/460236',
    salarySourceLabel: '普渡机器人2027产品经理具体岗位',
    exceptionReason: '高薪智能硬件产品岗：包含客户支持和定制方案，但核心职责仍是产品规划与需求，需确认现场占比',
  },
  'cnnc-huahui-ai-product-2027': {
    eligible: true,
    reason: '中核体系具体AI产品经理，本科计算机/软件/AI可投，大模型、RAG和AI产品项目直接相关',
    salaryKind: '未公开',
    salarySourceUrl: 'https://cnnc.zhiye.com/campus/detail?jobAdId=0d9141c3-c6c5-48eb-a7cd-a548ed7ad4e9',
    salarySourceLabel: '中核人才官方2027 AI产品经理岗位',
    exceptionReason: '央企具体AI产品岗：不以私企薪资门槛筛除，投前核对劳动关系主体、涉密要求和部门业务',
  },
  'sundray-enterprise-ai-development-2027': {
    eligible: true,
    reason: '企业级AI产品应用开发，本科可投，岗位明确面向AI能力在B端产品中的工程落地，20–35K/月',
    salaryKind: '本届公开', monthlyMin: 20000,
    salarySourceUrl: 'https://neau.bysjy.com.cn/detail/job?career_id=709303&id=3226133',
    salarySourceLabel: '信锐技术2027 AI应用开发工程师具体岗位',
    exceptionReason: '高薪B端AI技术路线：不是产品经理，适合用计算机专业和AI项目投递，排在产品/需求岗位之后',
  },
  'rigol-it-ai-application-2027': {
    eligible: true,
    reason: '2027 IT开发工程师明确接受计算机本科，负责业务需求、企业AI应用和智能助手落地，公开转载15–25K/月',
    salaryKind: '招聘转载参考', monthlyMin: 15000,
    salarySourceUrl: 'https://www.recruit.net/job/it--jobs/F0725863D0F6B00E',
    salarySourceLabel: '普源精电2027 IT开发工程师15–25K招聘转载',
    exceptionReason: '企业AI应用相邻岗：包含内部IT运维，投前确认AI应用开发、需求分析与日常运维的比例',
  },
  'streamax-platform-product-2027': {
    eligible: true,
    reason: '2027商用车AI产品工程师，计算机本科明确可投，职责含需求、PRD、原型和新品验证，14–20K/月',
    salaryKind: '本届公开', monthlyMin: 14000,
    salarySourceUrl: 'https://scc.hnu.edu.cn/detail/job?career_id=708727&id=3228523',
    salarySourceLabel: '锐明技术2027产品工程师具体岗位',
    exceptionReason: '高薪B端产品工程岗：比纯PM更强调验证测试和软硬件协同，优先国内平台方向并确认测试占比',
  },
  'chinsoft-requirements-analysis-2027': {
    eligible: true,
    reason: '中国电子旗下央企的2027需求分析师，本科起，信创与行业信息化B端场景，11月19日截止',
    salaryKind: '未公开',
    salarySourceUrl: 'https://mp.weixin.qq.com/s/fLnb3K95tmtNq1FhbNEt9g',
    salarySourceLabel: '中国软件2027届校园招聘官方公告',
    exceptionReason: '央企具体需求分析岗：不以私企薪资门槛筛除，需确认子公司、驻场频率及与实施交付的边界',
  },
  'ztccloud-b2b-product-2027': {
    eligible: true,
    reason: '官方2027 B端产品经理，本科开放，职责含需求、原型、产品逻辑与UAT，12月31日截止',
    salaryKind: '招聘转载参考', monthlyMin: 10000,
    salarySourceUrl: 'https://cn.linkedin.com/jobs/view/%E6%95%99%E8%82%B2%E4%BA%A7%E5%93%81%E7%BB%8F%E7%90%86-at-%E4%B8%AD%E5%85%B4%E6%96%B0%E4%BA%91-4417989844',
    salarySourceLabel: '中兴新云当前初级产品经理10–14K参考，非本届校招承诺',
    exceptionReason: '高匹配B端产品岗：需要中短期出差，面试时确认客户现场频率与产品工作占比',
  },
  'seichitech-product-information-2027': {
    eligible: true,
    reason: '本届半导体B端产品信息工程师，本科开放，覆盖UAT、知识库和AI知识管理，10–20K×13薪',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://www.nowcoder.com/jobs/detail/467167',
    salarySourceLabel: '精智达校招HR发布的2027产品信息工程师岗位',
    exceptionReason: '产品工程相邻岗位：不是项目管理或驻场交付，但技术文档与培训占比较高，并要求英语六级',
  },
  'kingdee-ai-product-2027': {
    eligible: true,
    reason: '金蝶2027校招明确开放AI产品经理、产品经理管培和AI产品体验设计，本科计算机可投',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.cup.edu.cn/job/view/id/622243',
    salarySourceLabel: '金蝶2027校招项目10–15K公开区间，非单一AI产品子岗报价',
    exceptionReason: '企业管理AI大平台：岗位分流较多，只投AI产品/产品管培，不把实施顾问当作产品岗位',
  },
  'goldwind-product-rd-2027': {
    eligible: true,
    reason: '2027产品研发大类明确接受计算机本科，风电/储能/零碳垂直，项目公开薪资10K起',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/81511.html',
    salarySourceLabel: '金风科技2027届校园招聘简章（项目口径）',
    exceptionReason: '能源垂直产品研发：逐岗核对本科要求，避开硕士算法岗和不愿接受的新疆现场岗位',
  },
  'nsfocus-security-product-2027': {
    eligible: true,
    reason: '2027校招明确单列企业级网络安全产品经理，本科开放，当前产品岗公开转载为15–20K/月',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://www.shushuqiuzhi.com/article/232869',
    salarySourceLabel: '绿盟科技2027产品经理岗位15–20K公开转载',
    exceptionReason: '高薪B端安全产品：非电力垂直，但客户覆盖能源/金融/政企，优先级放在AI+能源岗位之后',
  },
  'ygsoft-ai-requirements-2027': {
    eligible: true,
    reason: '国网数科控股智慧能源软件公司，珠海AI应用与武汉需求分析均明确本科，10月30日截止',
    salaryKind: '本届公开', monthlyMin: 9500,
    salarySourceUrl: 'https://yjsjob.91wllm.cn/campus/view/id/1005888',
    salarySourceLabel: '远光软件2027提前批具体岗位薪资表',
    exceptionReason: '央企AI+电力高匹配项：需求分析低于私企10K门槛不影响收录；必须按城市核学历，避开要求硕士的同名岗位',
  },
  'sgdt-ai-energy-digital-2027': {
    eligible: true,
    reason: '国家电网全资数字科技平台，计算机/AI/大数据本科开放，提前批10月30日截止',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/119501.html',
    salarySourceLabel: '国网数科控股2027校园招聘公告（15–20K项目口径）',
    exceptionReason: 'AI+电力能源最高优先级央企项：同一入口也有工程/项目管理，只选电子信息、AI、数据或数字能源岗位',
  },
  'czbank-ai-application-2027': {
    eligible: true,
    reason: '浙商银行总行AI应用研发和智能数据本科开放，官方10月25日截止',
    salaryKind: '未公开',
    salarySourceUrl: 'https://zp.czbank.com.cn/zpweb/zpPostController/planDetailPage.mvc?planId=8a8340e9a033d10501a06502133f0014',
    salarySourceLabel: '浙商银行官方2027校园招聘计划',
    exceptionReason: '国企银行科技岗：偏研发/数据而非纯产品，优先AI应用和智能数据，不把智能运维放在首选',
  },
  'cmbc-tech-ai-development-2027': {
    eligible: true,
    reason: '民生科技启航软件开发方向明确本科计算机可投，覆盖金融科技和AI应用，10月25日截止',
    salaryKind: '未公开',
    salarySourceUrl: 'https://www.yinhangzhaopin.com/msyhzp/2026-09-04/224962.htm',
    salarySourceLabel: '中国民生银行2027民生科技岗位转载（附官方校招原文入口）',
    exceptionReason: '银行科技技术路线补充：这是开发岗且含运维支持，只在愿意以技术切入金融科技时投递',
  },
  'huaneng-beijing-digital-2027': {
    eligible: true,
    reason: '华能北京热电2027本科计算机/电子信息岗位，官方10月31日18:00截止',
    salaryKind: '未公开',
    salarySourceUrl: 'https://zhaopin.chng.com.cn/InternRecruit?aId=2000235',
    salarySourceLabel: '中国华能官方2027校园招聘公告',
    exceptionReason: '央企电力垂直与福利例外：公告按专业大类，投前确认信息化/数字化职责和具体部门',
  },
  'boc-digital-tech-2027': {
    eligible: true,
    reason: '中国银行官方2027全球校招，信息科技/数字金融岗位本科开放，网申10月9日截止',
    salaryKind: '未公开',
    salarySourceUrl: 'https://www.boc.cn/aboutboc/bi4/202609/t20260903_25689311.html',
    salarySourceLabel: '中国银行官方2027全球校园招聘公告',
    exceptionReason: '央企银行保底项：岗位按机构差异很大，需逐岗确认信息科技/数字金融，不把柜面或营销岗当作产品岗位',
  },
  'cmb-chengdu-digital-finance-2027': {
    eligible: true,
    reason: '招商银行成都分行官方数字金融岗，本科可投，10月10日截止，理工科优先',
    salaryKind: '未公开',
    salarySourceUrl: 'https://cmb-recruitment-mobile.paas.cmbchina.com/positionList/school?orgId=102518&recruitmentTypeId=96574F8D-C7ED-4772-AE7C-BAC896D190C',
    salarySourceLabel: '招商银行官方校园招聘岗位列表',
    exceptionReason: '银行数字化岗位破格项：可能有分行轮岗和业务培养，投前确认是否进入数字金融产品/数据团队，排在垂直能源和中厂产品之后',
  },
  'hzbank-ai-tech-2027': {
    eligible: true,
    reason: '杭州银行总行信息技术部培训生，本科开放，人工智能/软件研发/数据研发方向，10月25日截止',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://jobs.tiangong.edu.cn/correcruit/content/id/56188.html',
    salarySourceLabel: '杭州银行2027秋季校园招聘公告（标注10000元以上）',
    exceptionReason: '国企银行科技岗：培训生可能轮岗，投递时优先人工智能/数据研发，确认是否能接触需求分析和平台产品',
  },
  'nbcb-fintech-product-2027': {
    eligible: true,
    reason: '宁波银行总行金融科技定向生，本科计算机/人工智能可投，岗位方向明确含产品经理',
    salaryKind: '未公开',
    salarySourceUrl: 'https://job.zzu.edu.cn/campus/view/id/1018779',
    salarySourceLabel: '宁波银行2027总行金融科技定向生公告',
    exceptionReason: '金融科技B端高匹配项：岗位池含开发、数据和运维，投递时锁定产品经理/数据研发/AI应用；截止日期以官方岗位状态为准',
  },
  'suzhou-bank-ai-tech-2027': {
    eligible: true,
    reason: '苏州银行信息科技类本科岗，明确涉及AI、智能体试点和系统需求分析，10月25日截止',
    salaryKind: '未公开',
    salarySourceUrl: 'https://jy.tust.edu.cn/correcruit/content/id/46770.html',
    salarySourceLabel: '苏州银行2027秋季校园招聘公告',
    exceptionReason: '国企银行AI/需求分析破格项：职责也包含技术支持和项目跟踪，必须面试确认产品/需求分析占比，避免长期运维',
  },
  'citic-card-product-ai-2027': {
    eligible: true,
    reason: '中信银行信用卡中心本科产品经理/AI应用开发岗，网申暂定10月18日截止',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://jobs.tiangong.edu.cn/correcruit/content/id/55652.html',
    salarySourceLabel: '中信银行信用卡中心2027秋季校园招聘公告（标注10000元以上）',
    exceptionReason: '央企金融科技产品岗：优先产品及渠道、AI应用开发，回避纯营销/客服/渠道执行；需确认具体部门和英语四级要求',
  },
  'sf-tech-product-data-2027': {
    eligible: true,
    reason: '顺丰科技官方产品经理/数据产品经理均开放本科，企业物流与AI数据平台方向，公告标注2万元以上',
    salaryKind: '本届公开', monthlyMin: 20000,
    salarySourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/119482.html',
    salarySourceLabel: '顺丰科技2027届秋季校园招聘公告（标注20000元以上）',
    exceptionReason: 'B端数据产品高薪破格项：产业科技而非互联网超大厂，但业务节奏可能偏快；优先产品/数据产品，确认固定薪资和驻场比例',
  },
  'bankcomm-fintech-2027': {
    eligible: true,
    reason: '交通银行官方金融科技岗本科开放，含IT系统、软件开发、数据安全，网申10月18日截止',
    salaryKind: '未公开',
    salarySourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/119027.html',
    salarySourceLabel: '交通银行2027年度校园招聘公告',
    exceptionReason: '央企银行稳定性保底项：岗位偏技术而非纯产品，投递时锁定金融科技/数据安全/系统建设，回避柜面、运营和营销岗',
  },
  'cgb-fintech-product-2027': {
    eligible: true,
    reason: '广发银行官方金融科技、产品管理与广银理财产品类本科开放，总行10月15日截止',
    salaryKind: '招聘转载参考', monthlyMin: 8000,
    salarySourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80750.html',
    salarySourceLabel: '广发银行2027年度校园招聘公告；转载岗位信息标注8–11K，仅作参考',
    exceptionReason: '国有股份制银行破格项：招聘转载薪资可能低于私企月薪基线，但银行不适用私企硬门槛；只投金融科技、产品管理、数据分析和广银理财产品，回避营销岗',
  },
  'bankofbeijing-ai-tech-2027': {
    eligible: true,
    reason: '北京银行科技英才本科开放，覆盖AI产品/软件开发/云计算，公开15–25K，10月15日截止',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://career.cup.edu.cn/campus/view/id/460568',
    salarySourceLabel: '北京银行2027校园招聘公告（科技英才标注15–25K）',
    exceptionReason: '银行科技产品高匹配项：需在官方平台选科技英才/科技研发并核实AI产品职责，避免被分到泛金融英才、柜面或营销岗',
  },
  'mingyang-smart-energy-ai-2027': {
    eligible: true,
    reason: '明阳智慧能源官方27届岗位含本科数据分析工程师、BI算法和智慧能源平台方向，直接覆盖AI+风电数据',
    salaryKind: '往届参考',
    salarySourceUrl: 'https://www.zhipin.com/zhaopin/e99417d2a7c694cb03Fz3NW1GA~~/',
    salarySourceLabel: '同公司26校招智慧能源系统算法岗15–25K；27届BI岗未公开，旧届同类数据岗曾低于10K/月',
    exceptionReason: 'AI+能源最高优先项：学历和场景非常匹配，但27届具体薪资未公开且往届BI岗存在低于10K情况；只投明确本科的数据/AI平台岗，并在HR沟通时先确认固定月薪≥10K与风场出差比例',
  },
  'flypai-ai-agent-product-2027': {
    eligible: true,
    reason: '飞派官方AI Agent产品经理，本科专业不限，明确覆盖企业知识库、RAG、工作流和PRD',
    salaryKind: '未公开',
    salarySourceUrl: 'https://www.flypai.com/jobs.html',
    salarySourceLabel: '飞派科技官方2027校招岗位页（薪资未公开）',
    exceptionReason: 'AI/B端产品高度匹配且官网注明弹性工作、不打卡；私企薪资和转正机制未公开，投前必须核实基本月薪与交付/客户现场比例',
  },
  'xiaopeng-embodied-data-product-2027': {
    eligible: true,
    reason: '小鹏官方具身智能数据硬件产品经理，本科可投，岗位职责包含需求分析、方案和产品验证',
    salaryKind: '招聘转载参考', monthlyMin: 12500,
    salarySourceUrl: 'https://career.hebut.edu.cn/correcruit/content/id/78926.html',
    salarySourceLabel: '小鹏集团公开校招薪资参考（本科应届15–17W，往届口径非本届承诺）',
    exceptionReason: 'AI硬件破格项：大型汽车科技企业且需深入现场、动手验证，薪资用往届本科年薪折算仅作量级参考，投前确认本届Offer与工作节奏',
  },
  'spirit-ai-product-2027': {
    eligible: true,
    reason: '千寻智能2027具身智能/机器人产品经理，本科计算机、软件、电子相关专业可投，产品职责明确',
    salaryKind: '未公开',
    salarySourceUrl: 'https://nwd4iy9rd2s.jobs.feishu.cn/campusofSpiritAI/m/position/7672031985867295002/detail',
    salarySourceLabel: '千寻智能官方2027具身智能产品经理岗位页（薪资未公开）',
    exceptionReason: 'AI/机器人垂直破格项：官方仅写极具竞争力薪酬，岗位门槛和技术理解要求高，投前确认团队学历偏好、薪资与加班节奏；作为冲刺项',
  },
  'hyperstrong-energy-solution-2027': {
    eligible: true,
    reason: '储能/算力能源解决方案与电力交易方向，本科计算机可投，公告标注10K以上',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80177.html',
    salarySourceLabel: '海博思创2027校招公告',
    exceptionReason: '能源垂直B端高匹配：解决方案和电力交易可能有客户/海外支持，优先确认岗位地点和出差比例',
  },
  'bluetti-energy-product-2027': {
    eligible: true,
    reason: '储能/微电网产品经理，本科理工可投，首年本科综合年薪12–25W',
    salaryKind: '本届公开',
    salarySourceUrl: 'https://campus.51job.com/poweroak2027/job.html',
    salarySourceLabel: '德兰明海2027校招官方岗位页（综合年薪口径）',
    exceptionReason: '能源产品高匹配：待遇为综合年薪而非基本月薪，投前确认固定薪资、CET-6和加班节奏',
  },
  'inbo-energy-product-engineer-2027': {
    eligible: true,
    reason: '储能PCS产品/解决方案工程师，本科计算机可投，能源垂直度高',
    salaryKind: '本届公开',
    salarySourceUrl: 'https://career.hebut.edu.cn/recruitment/content/type/2/id/5308.html',
    salarySourceLabel: '英博电气2027秋招公告（院校分档年薪）',
    exceptionReason: '低推荐能源破格项：普通一本本科年薪8–15W可能低于1万/月基线，仅在确认固定薪资和愿意进入储能PCS时投',
  },
  'zhiguang-bms-software-2027': {
    eligible: true,
    reason: '数字能源/储能BMS嵌入式软件，本科计算机可投，能源产品技术路线明确',
    salaryKind: '未公开',
    exceptionReason: '能源技术产品破格项：本届薪资未公开、非纯产品岗；六险一金/双休/宿舍等福利较明确，投前确认薪资和研发节奏',
  },
  'xinyueneng-cim-energy-2027': {
    eligible: true,
    reason: '碳化硅功率半导体数字化工厂IT/CIM，本科计算机可投，服务光伏储能和智能电网',
    salaryKind: '招聘转载参考',
    salarySourceUrl: 'https://gdcs.stu.edu.cn/Job/22992',
    salarySourceLabel: '芯粤能往届同公司校招薪酬参考，非本届承诺',
    exceptionReason: '能源制造B端软件破格项：岗位偏MES/产线系统而非产品经理，但公告强调双休和数字化工厂经验；需确认夜班/现场支持与本届年薪',
  },
  'hkaco-software-solution-2027': {
    eligible: true,
    reason: '企业软件/AI应用解决方案工程师，本科计算机可投，公开区间15–20K/月',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80647.html',
    salarySourceLabel: '虹科2027校园招聘岗位表（高校就业网公开区间）',
    exceptionReason: '高薪B端技术产品相邻岗：售前、客户现场和出差占比高，只投软件方向并先确认交付比例',
  },
  'shining3d-product-reserve-2027': {
    eligible: true,
    reason: '3D视觉/AI工业产品方向，本科开放，产品经理储备与产品应用工程师岗位，公开待遇10K以上',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80710.html',
    salarySourceLabel: '先临三维2027校园招聘公告',
    exceptionReason: '智能制造与AI硬件产品备选：岗位名称和学历口径需官网确认，产品应用可能有客户现场支持，不投项目管理工程师',
  },
  'beisen-ai-saas-product-2027': {
    eligible: true,
    reason: 'AI HR SaaS软件产品经理，本科开放，需求分析与功能设计职责明确，校招15–20K/月',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/89658.html',
    salarySourceLabel: '北森云计算2027软件产品经理校招公告',
  },
  'jiufang-ai-data-product-2027': {
    eligible: true,
    reason: 'AI数据与智能运营中台产品经理，本科开放，岗位页20–30K/月×12薪',
    salaryKind: '本届公开', monthlyMin: 20000,
    salarySourceUrl: 'https://www.nowcoder.com/jobs/detail/466589?urlSource=sitemap',
    salarySourceLabel: '九方云2027 AI产品经理具体岗位页',
    exceptionReason: '高薪AI产品备选：业务偏金融/运营增长而非能源，投递前确认工作节奏与实际产品职责',
  },
  'mingyuan-b2b-ai-product-2027': {
    eligible: true,
    reason: '本届B端SaaS产品经理，本科可投，AI企业管理场景，转正待遇10K以上',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.hebut.edu.cn/correcruit/content/id/80636.html',
    salarySourceLabel: '明源云2027校招产品经理公告',
  },
  'threatbook-ai-product-2027': {
    eligible: true,
    reason: '本届产品经理/产品运营明确本科开放；本科18万起、八险一金与期权，AI安全B端方向',
    salaryKind: '本届公开',
    salarySourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116958.html',
    salarySourceLabel: '微步在线2027校招公告（年薪口径，非月薪承诺）',
    exceptionReason: '高薪AI安全中厂：公告要求党员或团员，投前确认政治面貌；待遇用年薪口径，不强行折算月薪',
  },
  'qiyuan-energy-product-2027': {
    eligible: true,
    reason: '新能源商用车能源服务平台，本科产品经理/产品运营开放，校招待遇10K以上',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.hebut.edu.cn/correcruit/content/id/79135.html',
    salarySourceLabel: '启源芯动力2027校招岗位与待遇公告',
    exceptionReason: '能源平台高度垂直：岗位池混合运营与客户服务，投递时只选产品/产品运营/能源管理',
  },
  'novastar-product-solution-2027': {
    eligible: true,
    reason: '本届产品与解决方案工程师，本科理工科可投，工作含产品规划建议、竞品分析与研发反馈',
    salaryKind: '未公开',
    salarySourceUrl: 'https://www.nowcoder.com/jobs/detail/462610',
    salarySourceLabel: '诺瓦星云2027具体岗位页（薪资面议）',
    exceptionReason: '技术产品相邻岗：薪资待核验且接受全国办事处，确认月薪和出差比例后再决定',
  },
  'sifang-power-service-2027': {
    eligible: true,
    reason: '电力装备与新能源场景，本科计算机可投调试/工程服务，调试岗位10–15K/月',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.cup.edu.cn/campus/view/id/460244',
    salarySourceLabel: '四方股份2027校招岗位与薪资表',
    exceptionReason: '电力垂直保底项：现场调试属性强，只有接受出差/现场时投递，不投项目管理',
  },
  'fanruan-product-2027': {
    eligible: true, reason: '本届官方产品岗：理工本科、ToB产品实习优先，16–20.5K/月',
    salaryKind: '本届公开', monthlyMin: 16000,
    salarySourceUrl: 'https://join.fanruan.com/campus/detail?id=9869',
    salarySourceLabel: '帆软官方2027产品经理岗位',
  },
  'yangteng-product-2027': {
    eligible: true, reason: '本届简章单列技术研发序列产品经理，计算机/软件专业，13–20K/月',
    salaryKind: '本届公开', monthlyMin: 13000,
    salarySourceUrl: 'https://job.hust.edu.cn/zpinfo1/2407468.htm',
    salarySourceLabel: '华科就业网2027简章岗位薪资表',
  },
  'emdoor-product-2027': {
    eligible: true, reason: '产品经理岗位明确接受计算机本科，15–20K/月；另有CET-6要求',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116842.html',
    salarySourceLabel: '南开就业网产品经理独立岗位页',
  },
  'kedacom-pm-2027': {
    eligible: true, reason: '官网2027本科产品岗在招；官网面议，13–23K/月取自同届同岗招聘转载',
    salaryKind: '招聘转载参考', monthlyMin: 13000,
    salarySourceUrl: 'https://fs.jrzp.com/nView_E84FDF39AB5A6F35.shtml',
    salarySourceLabel: '2027产品经理同岗转载，非官网报价',
  },
  'sitech-ai-product-2027': {
    eligible: false, reason: '有2027产品生态招聘及往届成都11–17K参考，但尚未核实具体AI产品岗的本科学历条件；已有准备继续保留',
    salaryKind: '往届参考', monthlyMin: 11000,
    salarySourceUrl: 'https://m.zhipin.com/zhaopin/b3ce09c8e956c20c0nB_0tu5Ew~~/',
    salarySourceLabel: '2026届成都产品经理招聘参考（非2027承诺）',
  },
  'ronds-software-product-2027': {
    eligible: true, reason: '本届独立软件产品岗：计算机本科，14–20K/月，AI工业平台覆盖电力场景',
    salaryKind: '本届公开', monthlyMin: 14000,
    salarySourceUrl: 'https://career.scnu.edu.cn/detail/job?id=2581456&online_id=3591408',
    salarySourceLabel: '华南师大就业网2027软件产品经理岗位',
  },
  'huice-b2b-product-2027': {
    eligible: true, reason: '2027高潜产品经理，本科可投，企业ERP/WMS产品，15–25K×13薪',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://www.nowcoder.com/jobs/detail/459148?urlSource=sitemap',
    salarySourceLabel: '慧策招聘人员发布的2027高潜产品岗',
  },
  'intsig-data-product-2027': {
    eligible: true, reason: '27届秋招J14511：本科、SQL与大模型应用，数据产品需求与设计，13–18K/月',
    salaryKind: '本届公开', monthlyMin: 13000,
    salarySourceUrl: 'https://cn.linkedin.com/jobs/view/27届秋招-数据产品经理-j14511-at-合合信息-4460900438',
    salarySourceLabel: '合合信息岗位薪酬范围（领英/猎聘）',
  },
  'kylin-product-2027': {
    eligible: true, reason: '央企子公司独立2027产品岗，计算机本科可投；薪资不限，不包含科技项目助理岗',
    salaryKind: '未公开',
  },
  'richinfo-ai-product-2027': {
    eligible: true, reason: '本届政企AI产品岗，本科可投；RAG/Agent/知识库方向，公开月薪档下限10.5K',
    salaryKind: '本届公开', monthlyMin: 10500,
    salarySourceUrl: 'https://myjob.dlmu.edu.cn/campus/view/id/868828',
    salarySourceLabel: '高校就业网2027岗位薪资档与年薪表',
  },
  'autohome-b2b-product-2027': {
    eligible: true,
    reason: '本届独立B端产品岗：车商CRM/SaaS/供应链，本科可投，18–22K×16薪',
    salaryKind: '本届公开', monthlyMin: 18000,
    salarySourceUrl: 'https://www.nowcoder.com/jobs/detail/466943',
    salarySourceLabel: '企业校园招聘人员发布的2027具体岗位',
  },
  'cmic-ai-product-2027': {
    eligible: true,
    reason: '中国移动旗下官方2027 AI产品岗，本科计算机可投；知识库/智能体匹配，央企不设薪资下限',
    salaryKind: '未公开',
  },
  'nio-energy-product-2027': {
    eligible: true,
    reason: '本届充电/能源产品独立岗位，本科可投，覆盖充电管理系统与AI；薪资用往届产品岗Offer谨慎参考',
    salaryKind: '往届参考', monthlyMin: 17500,
    salarySourceUrl: 'https://www.nowcoder.com/discuss/455071324004769792',
    salarySourceLabel: '蔚来2023届产品岗Offer分享，非本届承诺',
  },
  'envision-product-2027': {
    eligible: true,
    reason: '2027校招明确开放产品类和本科，能源大模型/新型电力系统高度匹配；20K+为项目公开口径，具体产品子岗需再次确认',
    salaryKind: '本届公开', monthlyMin: 20000,
    salarySourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116772.html',
    salarySourceLabel: '南开就业网远景能源2027校招项目口径（非单一子岗报价）',
  },
  'lalamove-strategy-product-2027': {
    eligible: true,
    reason: '本届具体策略产品岗位，本科可投，16–26K/月；物流产品而非能源方向，因此推荐度靠后',
    salaryKind: '本届公开', monthlyMin: 16000,
    salarySourceUrl: 'https://m.zhipin.com/zhaopin/298301ce32a28e331nV_2tW9FQ~~/',
    salarySourceLabel: '货拉拉当前同届策略产品岗位',
  },
  'ninebot-navimow-product-2027': {
    eligible: true,
    reason: '九号旗下智能机器人子公司本届软件产品岗，计算机本科，15–30K×15薪；非项目管理或客户交付',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://www.nowcoder.com/jobs/detail/465296',
    salarySourceLabel: '未岚大陆招聘人员发布的2027软件产品经理岗位',
  },
  'inovance-b2b-market-2027': {
    eligible: true,
    reason: '本届具体市场类岗位本科可投，工业自动化/新能源B端方案，12–20K/月',
    salaryKind: '本届公开', monthlyMin: 12000,
    salarySourceUrl: 'https://jy.scu.edu.cn/index/index/employjobdetail.html?data=MDAwMDAwMDAwMJG6n3_Ed6imi4qQtLh4Y9yK0dTOs4bddricp9CWi5qikaeWacSdqLqGfaK2w4iil5C4zNbGiL-E',
    salarySourceLabel: '高校就业网2027具体市场类岗位页',
    exceptionReason: '高薪私企工业B端：允许销售/出差属性，但明确排在纯产品与AI+能源岗位之后',
  },
  'vivo-platform-product-2027': {
    eligible: true,
    reason: '你已于9月15日投递平台方向产品经理，作为真实流程保留；后续仅按你填写的日期提醒',
    salaryKind: '未公开',
    exceptionReason: '已投递保留：不再用尚未核实的薪资或竞争强度覆盖你的实际选择',
  },
  'engergy-ai-energy-solution-2027': {
    eligible: true,
    reason: '2027校招AI+能源解决方案岗，计算机/AI/控制/能源专业开放，10–15K/月',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://job.zut.edu.cn/module/position_brief_detail/id-113985/nid-6287',
    salarySourceLabel: '中原工学院就业网2027岗位与待遇页',
    exceptionReason: 'AI+能源高度垂直且双休弹性：可接受部分方案与客户现场工作',
  },
  'fanruan-fde-ai-solution-2027': {
    eligible: true,
    reason: '官方2027 AI解决方案岗，本科计算机可投，职责含需求洞察与产品反馈闭环，13–17K/月',
    salaryKind: '本届公开', monthlyMin: 13000,
    salarySourceUrl: 'https://join.fanruan.com/campus/detail?id=9889',
    salarySourceLabel: '帆软官方FDE解决方案工程师岗位页',
    exceptionReason: '高薪私企AI方案：允许售前、POC和客户赋能，但不是项目经理',
  },
  'siemens-sales100-2027': {
    eligible: true,
    reason: '西门子官方2027本科项目，计算机/AI可投，聚焦工业数字化解决方案',
    salaryKind: '未公开',
    salarySourceUrl: 'https://www.siemens.com/zh-cn/company/jobs/campus-recruiting/',
    salarySourceLabel: '西门子官方2027校园招聘与福利说明',
    exceptionReason: '外企与工作节奏例外：官方注明混合办公、拒绝996和系统培训',
  },
  'kehua-digital-energy-2027': {
    eligible: true,
    reason: '本届产品工程师/IT产品助理/微网EMS岗位，本科开放，项目页标注10K以上',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/80200.html',
    salarySourceLabel: '河北工大就业网科华2027校招与岗位表',
    exceptionReason: 'AI+数字能源垂直：岗位专业分流较细，投递时只选产品工程师、IT产品助理或微网EMS',
  },
  'ampace-aidc-solution-2027': {
    eligible: true,
    reason: 'AIDC供电、储能EMS/BMS解决方案本科开放，校招项目月薪10K起',
    salaryKind: '本届公开', monthlyMin: 10000,
    salarySourceUrl: 'https://career.hebut.edu.cn/correcruit/content/id/79145.html',
    salarySourceLabel: '高校就业网2027校招岗位与待遇页',
    exceptionReason: '高薪私企AI+能源：允许售前/交付，但优先AIDC解决方案而非纯项目管理',
  },
  'teld-solution-2027': {
    eligible: true,
    reason: '总部电气类本科岗位10.5–15K/月，数字充电网、电力交易和能源方案高度匹配',
    salaryKind: '本届公开', monthlyMin: 10500,
    salarySourceUrl: 'https://myjob.dlmu.edu.cn/campus/view/id/868552',
    salarySourceLabel: '高校就业网2027岗位与薪资表',
    exceptionReason: '高薪私企电力垂直：接受售前/方案，避开纯项目管理和强销售岗位',
  },
  'nrec-support-2027': {
    eligible: true,
    reason: '2027届本科开放技术支持与信息技术，电力系统/储能垂直，七险二金',
    salaryKind: '未公开',
    salarySourceUrl: 'https://www.wondercv.com/xiaozhao/nanrui-jibao-2027-campus-recruitment-13172-8ca5ea/',
    salarySourceLabel: '南瑞继保2027校招岗位、学历与福利汇总',
    exceptionReason: '央国企电力与高福利例外：可接受技术支持，但不选择纯现场调试',
  },
  'sac-power-ai-service-2027': {
    eligible: true,
    reason: '2027本科开放，人工智能、系统软件与储能/新能源服务均在招，六险二金',
    salaryKind: '未公开',
    salarySourceUrl: 'https://m.nj.bendibao.com/job/182644.shtm',
    salarySourceLabel: '国电南自2027校招岗位与福利汇总',
    exceptionReason: '央企电力垂直例外：优先AI/系统软件；调试服务仅作保底',
  },
  'wisdom-power-solution-marketing-2027': {
    eligible: true,
    reason: '国企数字电力/智慧能源方案岗位，本科可投，客户覆盖电网与工业企业',
    salaryKind: '本届公开', monthlyMin: 5000,
    salarySourceUrl: 'https://www.fenbi.com/page/exam-information-detail/468601157997568',
    salarySourceLabel: '2027具体岗位与福利页',
    exceptionReason: '国企电力垂直例外：不设私企10K门槛，但需接受驻外/出差',
  },
  'wisdri-automation-technical-marketing-2027': {
    eligible: true,
    reason: '央企工业自动化技术/营销岗位，本科开放，七险一金与单身公寓',
    salaryKind: '未公开',
    salarySourceUrl: 'https://career.hebut.edu.cn/home/correcruit/content/id/79331.html',
    salarySourceLabel: '2027校招岗位学历与福利表',
    exceptionReason: '央企B端与福利例外：技术营销可投，现场调试岗位放在后排',
  },
  'cmcc-qinghai-solution-2027': {
    eligible: true,
    reason: '央企省公司明确开放产品管理、解决方案和经营分析，本科计算机可投',
    salaryKind: '本届公开', monthlyMin: 5000,
    salarySourceUrl: 'https://career.sustech.edu.cn/detail/online?id=3595540',
    salarySourceLabel: '中国移动青海2027校招公告',
    exceptionReason: '央企产品岗位例外：薪资不设下限，仅在能接受青海长期发展时投递',
  },
  'ecoflow-presales-2027': {
    eligible: true,
    reason: '2027本科售前解决方案岗，储能场景含需求反馈与产品迭代，14–17K/月',
    salaryKind: '本届公开', monthlyMin: 14000,
    salarySourceUrl: 'https://www.nowcoder.com/jobs/detail/464341',
    salarySourceLabel: '正浩创新校招HR发布的2027具体岗位',
    exceptionReason: '高薪私企清洁能源：允许售前/客户培训，但不是纯项目交付',
  },
  'oppo-ai-pm-2027': {
    eligible: true,
    reason: '官方2027互联网产品经理（AI方向），计算机本科可投；本届未公开月薪，采用深圳经验不限AI产品岗20–40K参考并降低推荐度',
    salaryKind: '招聘转载参考', monthlyMin: 20000,
    salarySourceUrl: 'https://www.zhipin.com/zhaopin/33e51e8132a7a8381HF92NW7Ew~~/',
    salarySourceLabel: 'OPPO深圳经验不限AI产品岗参考，非本届报价',
  },
  'xiaomi-product-2027': {
    eligible: true,
    reason: '2027具体策略产品岗，计算机本科可投；薪资采用本届校招项目公开区间，因C端且竞争强放在后排',
    salaryKind: '本届公开', monthlyMin: 15000,
    salarySourceUrl: 'https://career.nankai.edu.cn/correcruit/content/id/116728.html',
    salarySourceLabel: '小米集团2027校招项目公开区间（非单一子岗报价）',
  },
  'anker-campus-2027': {
    eligible: true,
    reason: '企业招聘人员发布的2027硬件产品经理，本科理工科；本届面议，采用深圳经验不限同岗18–30K参考',
    salaryKind: '招聘转载参考', monthlyMin: 18000,
    salarySourceUrl: 'https://www.zhipin.com/zhaopin/a1b60e9324c386830XF93tq9/',
    salarySourceLabel: '安克深圳经验不限产品经理同岗参考，非本届报价',
  },
};

type ProgressItem = { id: string; stage: string; isCustom: boolean };
const protectedStages = new Set(['准备中', '已投递', '笔试', '面试', 'Offer', '已拒绝']);

export function isOpportunityInScope(item: ProgressItem, retiredIds: readonly string[]) {
  if (item.stage === '放弃' || retiredIds.includes(item.id)) return false;
  if (protectedStages.has(item.stage)) return true;
  const review = screeningReviews[item.id];
  return review ? review.eligible : item.isCustom;
}

export function isProtectedFromScreening(item: ProgressItem) {
  return protectedStages.has(item.stage) && screeningReviews[item.id]?.eligible === false;
}
